/**
 * 
 */
package com.asaas.test.util;

import java.util.HashMap;

/**
 * @author
 * 
 */
public class AssetBase implements Page {
    // Declare variable
	public Element popUp_countOrder_EPY_month_5;
	public Element popUp_EERBL_GE_title;
	public Element ThreeYearOneTimeAccountBook_nonOperatingExpenseRatio;
	public Element reductionEntryDetailButton;
	public Element popUp_expenseTitleChange_GE_input;
	public Element popUp_assetImportConfirm_first;
	public Element edit_TYOT;
	public Element localTax_currentYearValuation;
	public Element popUp_countOrder_EPY_month_2;
	public Element signify_changeExpenseTitle;
	public Element popUp_countOrder_EPY_month_3;
	public Element accountingResidualRate;
	public Element popUp_countOrder_EPY_month_4;
	public Element specialDprcDetailButton;
	public Element nonOperatingExpenseTextCenter;
	public Element usefulLifeTable_Kind;
	public Element simplePage_MTE;
	public Element popUp_assetImportConfirm_third;
	public Element localTax_decreaseSummary;
	public Element tab_day;
	public Element edit_editExcutingRatioByLump;
	public Element SAAESP_endingBookAmount;
	public Element smallAmountAssetExceptionStatementPage_LUL;
	public Element add_Button;
	public Element executingRate;
	public Element accountingDprcChangeType;
	public Element tab_install_first;
	public Element simplePage_LUL;
	public Element paymentDate_Month;
	public Element ThreeYearOneTimeAccountBook_CPAAOL;
	public Element currentPeriodDprcLimitAmount;
	public Element popUp_assetImport_type;
	public Element reversalTypeOfReservedAmountDuringThePeriod;
	public Element account_List_dis;
	public Element accountingDprcLimitAmount_Input;
	public Element fixedAssets_Simple;
	public Element ThreeYearOneTimeAccountBook_GE;
	public Element right_del;
	public Element popUp_EBRBL_businessRadio_error;
	public Element popUp_countOrder_department;
	public Element popUp_assetImportConfirm_thirdNum;
	public Element acquisitionData_Era;
	public Element popUp_expenseTitleChange_NOE_input;
	public Element ThreeYearOneTimeAccountBook_nonBusiness;
	public Element SAAESP_nonBussiness;
	public Element SAAESP_acquisitionCost;
	public Element popUp_countOrder_AUTYOTDP;
	public Element popUp_assetImport_confirm;
	public Element endingReservedAmount;
	public Element beginningBookAmount;
	public Element statementPage_assetCode;
	public Element ThreeYearOneTimeAccountBook_department;
	public Element SAAESP_dprcRate;
	public Element accountingResidualValue;
	public Element localTax_cYROffice;
	public Element excessAmountCarriedForwardToTheBeforePeriod;
	public Element SAAESP_generalDprcLimitAmount;
	public Element simpleNOM;
	public Element popUp_EERBL_NOE_percent;
	public Element localTax_decreaseCode;
	public Element popUp_createNewPeriod_title;
	public Element commonUseDate_Month;
	public Element popUp_calculate_cancel;
	public Element popUp_countOrder_EPY_year_3;
	public Element popUp_EBRBL_businessRadio;
	public Element popUp_countOrder_EPY_year_2;
	public Element generalExpenseTextLeft;
	public Element reductionEntryAmount;
	public Element popUp_countOrder_EPY_CPFrom;
	public Element legalDprcChangeType;
	public Element legalPaymentTerm;
	public Element detailPage_nonOperatingExpense;
	public Element popUp_editBusinessRatioByLump;
	public Element popUp_countOrder_EPY_year_4;
	public Element generalExpenseTextRight;
	public Element usefulLifeTable_UsefulLifeList;
	public Element popUp_countOrder_EPY_year_5;
	public Element popUp_countOrder_ok;
	public Element signify_changeExpenseTitle2;
	public Element endingBookAmount;
	public Element endingAccumulatedDprcAccount;
	public Element legalCalculatedDprcAmount;
	public Element commonUseDateWarningMes1;
	public Element cancel_Button;
	public Element code;
	public Element revisedUsefulLifeForUsedItems_UsefulLife_Save;
	public Element popUp_TYOT_BEASDC_all_2;
	public Element popUp_countOrder_EPY_error_OK;
	public Element popUp_assetImport_cancel;
	public Element SAAESP_currentPeriodAmountIncludeExpense;
	public Element smallAmountAssetExceptionStatementPage_NOE;
	public Element revisedUsefulLifeForUsedItems_LifeButton;
	public Element paymentDate_Year;
	public Element detailPage;
	public Element tab_month;
	public Element ThreeYearOneTimeAccountBook_EACFTTBP;
	public Element popUp_countOrder_installation_subtotal;
	public Element popUp_countOrder_EPY_month;
	public Element right_add;
	public Element legalDprcRate;
	public Element SAAESP_data;
	public Element name;
	public Element legalUsefulLifeforNewItems;
	public Element accountingDprcLimitAmount_Select;
	public Element tab_movment_second;
	public Element popUp_TYOT_ACSC;
	public Element popUp_TYOT_BRDTC;
	public Element popUp_EERBL_GE_input;
	public Element edit_deleComplete;
	public Element localTax_pYRInstallation;
	public Element popUp_change_GET;
	public Element edit;
	public Element simplePage_nonOperatingExpense;
	public Element right_editBusinessRatioByLump;
	public Element accountAsset_capitalExpense;
	public Element accountingPaymentTerm;
	public Element fixedAssets_Simple_code;
	public Element edit_editBusinessRatioByLump;
	public Element ThreeYearOneTimeAccountBook_MTE;
	public Element legalResidualRate;
	public Element popUp_assetImport_input;
	public Element popUp_countOrder_EPY_day_5;
	public Element popUp_countOrder_EPY_CPTill;
	public Element popUp_countOrder_EPY_day_2;
	public Element accountingCalculatedDprcAmount;
	public Element popUp_countOrder_EPY_day_3;
	public Element popUp_countOrder_EPY_day_4;
	public Element localTax_cYRInstallation;
	public Element popUp_countOrder_EPY_day;
	public Element popUp_assetImportConfirm_firstNum;
	public Element detailPage_assetCode;
	public Element localTax_alllncreaseCode;
	public Element paymentDate_Day;
	public Element right_codeAdd;
	public Element popUp_TYOT_CDA_2;
	public Element localTax_decreaseCause;
	public Element popUp_countOrder_AUSAAEP;
	public Element structure;
	public Element revisedUsefulLifeForUsedItems_Kind;
	public Element save_Button;
	public Element calculationBasicData;
	public Element popUp_countOrder_EPY_errorMessage;
	public Element popUp_TYOT_CDA;
	public Element localTax_pYROffice;
	public Element localTax_limitAmount5Per;
	public Element legalResidualTerm;
	public Element simplePage_NOE;
	public Element specialDprcType;
	public Element popUp_createNewPeriod_cancel2;
	public Element delAsset_Button;
	public Element warningMes1;
	public Element popUp_editExpenseRatioByLump;
	public Element warningMes2;
	public Element acquisitionData_IncreaseAssetTiming;
	public Element simplePage_generalExpense;
	public Element close_Button;
	public Element popUp_TYOT_CDAC_2;
	public Element popUp_assetImport_error;
	public Element localTax_alllncreaseMoveType;
	public Element legalIncreasedDprcAmount;
	public Element ThreeYearOneTimeAccountBook;
	public Element edit_AddTwo;
	public Element popUp_EERBL_MTE_title;
	public Element ThreeYearOneTimeAccountBook_Retirment;
	public Element popUp_assetImport_noData_cancel;
	public Element popUp_TYOT_BEASC_all;
	public Element ThreeYearOneTimeAccountBook_EBA;
	public Element OK;
	public Element popUp_countOrder_account;
	public Element basic_Information;
	public Element accountingFixedRateMethodRevisedAcquisitionCost;
	public Element accountingCurrentPeriodTerm;
	public Element ThreeYearOneTimeAccountBook_nonBusiness_t;
	public Element legalDprcLimitAmount_Input;
	public Element popUp_assetImport_title;
	public Element popUp_expenseTitleChange_error;
	public Element localTax_decreaseMoveCause;
	public Element localTax;
	public Element accountingSpecialDprcAmount;
	public Element detailPage_legalCalculatedDprcAmount;
	public Element recover_Button;
	public Element SAAESP_nonBussiness_title;
	public Element localTax_increaseCause;
	public Element ThreeYearOneTimeAccountBook_assetName;
	public Element popUp_EBRBL_ok;
	public Element businessRatio;
	public Element legalCurrentPeriodTerm;
	public Element fixedAssets_Simple_second;
	public Element ThreeYearOneTimeAccountBook_CPDLA;
	public Element accountingDprcMethod;
	public Element ThreeYearOneTimeAccountBook_EACDA;
	public Element previousPeriodExcessAmountBroughtForward;
	public Element commonUseDate_Day;
	public Element popUp_editExcutingRatioByLump;
	public Element legalDprcLimitAmount_Select;
	public Element smallAmountAssetExceptionStatementPage;
	public Element popUp_assetImportConfirm_cancel;
	public Element popUp_calculate_title;
	public Element popUp_countOrder_accountType;
	public Element accountingCalculatedDprcAmount_DA;
	public Element popUp_TYOT_RBBAF;
	public Element popUp_assetImport_warning_text;
	public Element beginningReservedAmount;
	public Element SAAESP_department;
	public Element ThreeYearOneTimeAccountBook_manufacturingExpenseRatio;
	public Element account_List;
	public Element localTax_usefulLife;
	public Element legalDprcLimitDetailButton;
	public Element SAAESP_legalSpecialDprcAmount;
	public Element ThreeYearOneTimeAccountBook_data;
	public Element tab_month_2;
	public Element popUp_assetImport_execute_get;
	public Element popUp_TYOT_CUPC;
	public Element popUp_EBRBL_businessRadio_format;
	public Element SAAESP_summary;
	public Element legalMemorandumValue;
	public Element popUp_assetImportConfirm_causeError;
	public Element legalFixedRateMethodRevisedAcquisitionCost;
	public Element popUp_countOrder_EPY_CPTill_4;
	public Element smallAmountAssetExceptionStatementPage_MTE;
	public Element popUp_countOrder_EPY_CPTill_3;
	public Element menuBar_input_changeReportScreen;
	public Element popUp_EERBL_MTE_input;
	public Element popUp_countOrder_EPY_CPTill_5;
	public Element popUp_calculate_OK;
	public Element popUp_countOrder_EPY_CPTill_2;
	public Element popUp_countOrder_EPY_CPTill_1;
	public Element commonUseDate_Year;
	public Element detailPage_manufacturingExpense;
	public Element increasedDprcRate;
	public Element popUp_EERBL_NOE_title;
	public Element warningButton2_Y;
	public Element accountingUsefulLife;
	public Element changeOfDprcMethodButton;
	public Element tab_install_second;
	public Element balanceAcquisitionCost;
	public Element simplePage_manufacturingExpense;
	public Element popUp_countOrder_EPY_cancel;
	public Element statementPage_dprcMethod;
	public Element accountingDprcRate;
	public Element popUp_EExRBL_percent;
	public Element summary;
	public Element popUp_change_MTE;
	public Element edit_editExpenseRatioByLump;
	public Element ThreeYearOneTimeAccountBook_generalExpenseRatio;
	public Element detailPage_executingRate;
	public Element usefulLifeTable_DetailList;
	public Element popUp_countOrder_EPY_error;
	public Element SAAESP_manufacturingExpense;
	public Element popUp_countOrder_drcpMethod;
	public Element previousPeriodExcessAndDeficitAmountBroughtForward;
	public Element right_editExpenseRatioByLump;
	public Element popUp_TYOT_BBASC_all_2;
	public Element quantity;
	public Element localTax_decreaseType;
	public Element accountingSpecialDprcLimitAmount;
	public Element acquisitionData_Day;
	public Element acquisitionData_Month;
	public Element generalDprcLimitAmount;
	public Element popUp_expenseTitleChange_GE_title;
	public Element popUp_createNewPeriod_message;
	public Element dprcChange_Save;
	public Element ThreeYearOneTimeAccountBook_PEABF;
	public Element popUp_EERBL_GE_percent;
	public Element localTax_alllncreaseMoveCause;
	public Element deleteData_Button;
	public Element popUp_createNewPeriod_OK;
	public Element localTax_assetName;
	public Element statementNOM;
	public Element legalDprcMethod;
	public Element popUp_assetImport_EPSON_message;
	public Element SAAESP_currentPeriodDprcAmount;
	public Element simplePage;
	public Element edit_addAndCopy;
	public Element specialDprcRate;
	public Element legalSpecialDprcAmount;
	public Element currentPeriodAmountIncludedInExpenses;
	public Element dprcDeficitAmount;
	public Element popUp_assetImportConfirm_get;
	public Element currentPeriodDprcAmount;
	public Element SAAESP_method;
	public Element popUp_createNewPeriod_cancel;
	public Element popUp_EERBL_MTE_percent;
	public Element retirement_Year;
	public Element localTax_assetType;
	public Element detail;
	public Element dprcLiabilityReserveMethod_reserve;
	public Element cancel;
	public Element simpleBusinessRadio;
	public Element popUp_expenseTitleChange_ok;
	public Element ThreeYearOneTimeAccountBook_quantity;
	public Element edit_Add;
	public Element legalCalculatedDprcAmount_DA;
	public Element installationSite_List;
	public Element popUp_EExRBL_input;
	public Element localTax_taxable;
	public Element signify;
	public Element localTax_preciousYearReturnValuation;
	public Element edit_Button;
	public Element ThreeYearOneTimeNOM;
	public Element popUp_countOrder_RST;
	public Element accountingDprcAmount;
	public Element right_recover;
	public Element account_List_firstLine;
	public Element fixedAssets_TYOT_second;
	public Element revisedUsefulLifeForUsedItems_Search;
	public Element popUp_assetImport_warning_title;
	public Element usefulLifeTableButton;
	public Element applicationArtical;
	public Element localTax_residualRate;
	public Element popUp_TYOT_BEASDC_all;
	public Element detailNOM;
	public Element manufacturingExpenseRatio;
	public Element accountAsset_Code;
	public Element revisedUsefulLifeForUsedItems_Save;
	public Element OK_button;
	public Element popUp_expenseTitleChange_NOE_title;
	public Element commonUseDate_Era;
	public Element assetBaseList;
	public Element popUp_TYOT_CDAC;
	public Element nonOperatingExpenseRatio;
	public Element file_save;
	public Element paymentAmount;
	public Element SAAESP_installation;
	public Element menuBar_input;
	public Element popUp_assetImport_JDL_message;
	public Element popUp_expenseTitleChange_title;
	public Element popUp_assetImport_reference;
	public Element manufacturingExpenseTextCenter;
	public Element popUp_EERBL_cancel;
	public Element retirement_Era;
	public Element SAAESP_quantity;
	public Element right_editExcutingRatioByLump;
	public Element usefulLifeTable_Search;
	public Element SAAESP_assetName;
	public Element edit_edit;
	public Element detailPage_NOE;
	public Element popUp_expenseTitleChange_MTE_title;
	public Element file_save2;
	public Element accountingResidualTerm;
	public Element file_import;
	public Element retirement_Month;
	public Element generalDprcAmount;
	public Element popUp_EBRBL_businessRadio_ok;
	public Element tab_day_2;
	public Element popUp_EBRBL_cancel;
	public Element popUp_countOrder_AUTYOTDP_assetList;
	public Element edit_dele;
	public Element popUp_EExRBL_ok;
	public Element tab;
	public Element fixedAssets_Simple_first;
	public Element ThreeYearOneTimeAccountBook_NOE;
	public Element ThreeYearOneTimeAccountBook_summary;
	public Element legalUseLife;
	public Element file;
	public Element popUp_TYOT_BBASC_all_value;
	public Element popUp_TYOT_ACSC_2;
	public Element accountSimple;
	public Element dprcLiabilityReserveMethod_dprc;
	public Element usefulLifeTable_Save;
	public Element dprcRetirement;
	public Element installationSite_Input;
	public Element popUp_TYOT_BBASC_all;
	public Element beginningAccumulatedDprcAccount;
	public Element popUp_countOrder_installation;
	public Element edit_TYOT2;
	public Element reversalAmountOfReservedAmountDuringThePeriod;
	public Element accountingDprcInputFlag;
	public Element right_edit;
	public Element tab_department_second;
	public Element popUp_expenseTitleChange_MTE_input;
	public Element commonUseDate_IncreaseAssetTiming;
	public Element delete_Button;
	public Element department_Input;
	public Element account_Input;
	public Element retirementCause;
	public Element revisedUsefulLifeForUsedItemsButton;
	public Element account_Button;
	public Element popUp_assetImport_execute;
	public Element popUp_TYOT_OTDAMT;
	public Element ThreeYearOneTimeAccountBook_notRetirment;
	public Element popUp_countOrder_ok_list;
	public Element tab_installationSite_2;
	public Element SAAESP_nonOperatingExpense;
	public Element popUp_countOrder_AUSAAEP_assetList;
	public Element detailPage_GE;
	public Element popUp_assetImportConfirm_secondNum;
	public Element acquisitionCost;
	public Element file_createNewPeriod;
	public Element revisedUsefulLifeForUsedItems_Structure;
	public Element tab_year_2;
	public Element accountingRevisedDprcRate;
	public Element department_List;
	public Element popUp_countOrder_AUTYOTDP_TYOTDList;
	public Element popUp_countOrder_EPY_OK;
	public Element SAAESP_decreasedAssetAmount;
	public Element cancel_button;
	public Element accountingMemorandumValue;
	public Element dprcExcessAmount;
	public Element popUp_EExRBL_cancel;
	public Element usefulLifeTable_Structure;
	public Element paymentDate_Era;
	public Element tab_movment_first;
	public Element revisedUsefulLifeForUsedItems_CalcType;
	public Element warningButton_Y;
	public Element popUp_countOrder_AUSAAEP_SAAEDList;
	public Element applicationParagraph;
	public Element fixedAssets_SimpleList;
	public Element popUp_TYOT_BEASDC_all_2_value;
	public Element revisedUsefulLifeForUsedItems_LifeForNewItems;
	public Element acquisitionData_Year;
	public Element popUp_countOrder_editPassedYear;
	public Element popUp_countOrder_EPY_era_5;
	public Element popUp_EBRBL_error;
	public Element popUp_countOrder_EPY_era_4;
	public Element popUp_TYOT_title;
	public Element popUp_countOrder_EPY_era_3;
	public Element accountAsset_Name;
	public Element popUp_countOrder_EPY_era_2;
	public Element localTax_alllncreaseSummary;
	public Element popUp_countOrder_EPY_era_1;
	public Element simplePage_GE;
	public Element currentPeriodApprovedAmountOfLoss;
	public Element tab_year;
	public Element popUp_expenseTitleChange_cancel;
	public Element SAAESP_increasedAssetAmount;
	public Element localTax_levyDate;
	public Element revisedUsefulLifeForUsedItems_SearchInput;
	public Element localTax_decreaseMoveType;
	public Element statementPage;
	public Element popUp_countOrder_EPY_error2_OK;
	public Element SAAESP_beginningBookAmount;
	public Element revisedUsefulLifeForUsedItems_UsefulLifeList;
	public Element smallAmountAssetExceptionStatementPage_GE;
	public Element popUp_TYOT_ACOMC;
	public Element numberOfMonth_small;
	public Element popUp_assetImport_esc;
	public Element SAAESP_generalExpense;
	public Element increaseCause;
	public Element ThreeYearOneTimeAccountBook_acquisitionCost;
	public Element SAAESP_accumulatedDprcAccount;
	public Element popUp_TYOT_BEASC_all_2;
	public Element detailPage_generalExpense;
	public Element popup_Dprc_revisedUsefulLifeInfoTitle;
	public Element retirement_Day;
	public Element popUp_TYOT_clear;
	public Element usefulLifeTable_SearchInput;
	public Element popUp_countOrder_CONP;
	public Element legalDprcContent;
	public Element popUp_EERBL_NOE_input;
	public Element retirementMethod;
	public Element reductionEntryType;
	public Element simplePage_DprcMethod;
	public Element generalExpenseTextCenter;
	public Element popUp_EERBL_ok;
	public Element popUp_assetImportConfirm_second;
	public Element popUp_countOrder;
	public Element generalExpenseRatio;
	public Element popUp_change_NOE;
	public Element legalRevisedDprcRate;
	public Element popup_Dprc_usefulLifeInfoTitle;
	public Element edit_calculate;
	public Element accountAsset_CodeSuffix;
	public Element popUp_countOrder_department_subtotal;
	public Element legalDprcMethod2;
	public Element detailPage_MTE;
	public Element popUp_countOrder_EPY_year;
	public Element legalResidualValue;

    /*
     * @see com.asaas.test.util.Page#init(java.util.HashMap)
     */
    public void init(HashMap<String, Object> elements) {
        // Initialize variable
		this.popUp_countOrder_EPY_month_5 = (Element) elements.get("popUp_countOrder_EPY_month_5");
		this.popUp_EERBL_GE_title = (Element) elements.get("popUp_EERBL_GE_title");
		this.ThreeYearOneTimeAccountBook_nonOperatingExpenseRatio = (Element) elements.get("ThreeYearOneTimeAccountBook_nonOperatingExpenseRatio");
		this.reductionEntryDetailButton = (Element) elements.get("reductionEntryDetailButton");
		this.popUp_expenseTitleChange_GE_input = (Element) elements.get("popUp_expenseTitleChange_GE_input");
		this.popUp_assetImportConfirm_first = (Element) elements.get("popUp_assetImportConfirm_first");
		this.edit_TYOT = (Element) elements.get("edit_TYOT");
		this.localTax_currentYearValuation = (Element) elements.get("localTax_currentYearValuation");
		this.popUp_countOrder_EPY_month_2 = (Element) elements.get("popUp_countOrder_EPY_month_2");
		this.signify_changeExpenseTitle = (Element) elements.get("signify_changeExpenseTitle");
		this.popUp_countOrder_EPY_month_3 = (Element) elements.get("popUp_countOrder_EPY_month_3");
		this.accountingResidualRate = (Element) elements.get("accountingResidualRate");
		this.popUp_countOrder_EPY_month_4 = (Element) elements.get("popUp_countOrder_EPY_month_4");
		this.specialDprcDetailButton = (Element) elements.get("specialDprcDetailButton");
		this.nonOperatingExpenseTextCenter = (Element) elements.get("nonOperatingExpenseTextCenter");
		this.usefulLifeTable_Kind = (Element) elements.get("usefulLifeTable_Kind");
		this.simplePage_MTE = (Element) elements.get("simplePage_MTE");
		this.popUp_assetImportConfirm_third = (Element) elements.get("popUp_assetImportConfirm_third");
		this.localTax_decreaseSummary = (Element) elements.get("localTax_decreaseSummary");
		this.tab_day = (Element) elements.get("tab_day");
		this.edit_editExcutingRatioByLump = (Element) elements.get("edit_editExcutingRatioByLump");
		this.SAAESP_endingBookAmount = (Element) elements.get("SAAESP_endingBookAmount");
		this.smallAmountAssetExceptionStatementPage_LUL = (Element) elements.get("smallAmountAssetExceptionStatementPage_LUL");
		this.add_Button = (Element) elements.get("add_Button");
		this.executingRate = (Element) elements.get("executingRate");
		this.accountingDprcChangeType = (Element) elements.get("accountingDprcChangeType");
		this.tab_install_first = (Element) elements.get("tab_install_first");
		this.simplePage_LUL = (Element) elements.get("simplePage_LUL");
		this.paymentDate_Month = (Element) elements.get("paymentDate_Month");
		this.ThreeYearOneTimeAccountBook_CPAAOL = (Element) elements.get("ThreeYearOneTimeAccountBook_CPAAOL");
		this.currentPeriodDprcLimitAmount = (Element) elements.get("currentPeriodDprcLimitAmount");
		this.popUp_assetImport_type = (Element) elements.get("popUp_assetImport_type");
		this.reversalTypeOfReservedAmountDuringThePeriod = (Element) elements.get("reversalTypeOfReservedAmountDuringThePeriod");
		this.account_List_dis = (Element) elements.get("account_List_dis");
		this.accountingDprcLimitAmount_Input = (Element) elements.get("accountingDprcLimitAmount_Input");
		this.fixedAssets_Simple = (Element) elements.get("fixedAssets_Simple");
		this.ThreeYearOneTimeAccountBook_GE = (Element) elements.get("ThreeYearOneTimeAccountBook_GE");
		this.right_del = (Element) elements.get("right_del");
		this.popUp_EBRBL_businessRadio_error = (Element) elements.get("popUp_EBRBL_businessRadio_error");
		this.popUp_countOrder_department = (Element) elements.get("popUp_countOrder_department");
		this.popUp_assetImportConfirm_thirdNum = (Element) elements.get("popUp_assetImportConfirm_thirdNum");
		this.acquisitionData_Era = (Element) elements.get("acquisitionData_Era");
		this.popUp_expenseTitleChange_NOE_input = (Element) elements.get("popUp_expenseTitleChange_NOE_input");
		this.ThreeYearOneTimeAccountBook_nonBusiness = (Element) elements.get("ThreeYearOneTimeAccountBook_nonBusiness");
		this.SAAESP_nonBussiness = (Element) elements.get("SAAESP_nonBussiness");
		this.SAAESP_acquisitionCost = (Element) elements.get("SAAESP_acquisitionCost");
		this.popUp_countOrder_AUTYOTDP = (Element) elements.get("popUp_countOrder_AUTYOTDP");
		this.popUp_assetImport_confirm = (Element) elements.get("popUp_assetImport_confirm");
		this.endingReservedAmount = (Element) elements.get("endingReservedAmount");
		this.beginningBookAmount = (Element) elements.get("beginningBookAmount");
		this.statementPage_assetCode = (Element) elements.get("statementPage_assetCode");
		this.ThreeYearOneTimeAccountBook_department = (Element) elements.get("ThreeYearOneTimeAccountBook_department");
		this.SAAESP_dprcRate = (Element) elements.get("SAAESP_dprcRate");
		this.accountingResidualValue = (Element) elements.get("accountingResidualValue");
		this.localTax_cYROffice = (Element) elements.get("localTax_cYROffice");
		this.excessAmountCarriedForwardToTheBeforePeriod = (Element) elements.get("excessAmountCarriedForwardToTheBeforePeriod");
		this.SAAESP_generalDprcLimitAmount = (Element) elements.get("SAAESP_generalDprcLimitAmount");
		this.simpleNOM = (Element) elements.get("simpleNOM");
		this.popUp_EERBL_NOE_percent = (Element) elements.get("popUp_EERBL_NOE_percent");
		this.localTax_decreaseCode = (Element) elements.get("localTax_decreaseCode");
		this.popUp_createNewPeriod_title = (Element) elements.get("popUp_createNewPeriod_title");
		this.commonUseDate_Month = (Element) elements.get("commonUseDate_Month");
		this.popUp_calculate_cancel = (Element) elements.get("popUp_calculate_cancel");
		this.popUp_countOrder_EPY_year_3 = (Element) elements.get("popUp_countOrder_EPY_year_3");
		this.popUp_EBRBL_businessRadio = (Element) elements.get("popUp_EBRBL_businessRadio");
		this.popUp_countOrder_EPY_year_2 = (Element) elements.get("popUp_countOrder_EPY_year_2");
		this.generalExpenseTextLeft = (Element) elements.get("generalExpenseTextLeft");
		this.reductionEntryAmount = (Element) elements.get("reductionEntryAmount");
		this.popUp_countOrder_EPY_CPFrom = (Element) elements.get("popUp_countOrder_EPY_CPFrom");
		this.legalDprcChangeType = (Element) elements.get("legalDprcChangeType");
		this.legalPaymentTerm = (Element) elements.get("legalPaymentTerm");
		this.detailPage_nonOperatingExpense = (Element) elements.get("detailPage_nonOperatingExpense");
		this.popUp_editBusinessRatioByLump = (Element) elements.get("popUp_editBusinessRatioByLump");
		this.popUp_countOrder_EPY_year_4 = (Element) elements.get("popUp_countOrder_EPY_year_4");
		this.generalExpenseTextRight = (Element) elements.get("generalExpenseTextRight");
		this.usefulLifeTable_UsefulLifeList = (Element) elements.get("usefulLifeTable_UsefulLifeList");
		this.popUp_countOrder_EPY_year_5 = (Element) elements.get("popUp_countOrder_EPY_year_5");
		this.popUp_countOrder_ok = (Element) elements.get("popUp_countOrder_ok");
		this.signify_changeExpenseTitle2 = (Element) elements.get("signify_changeExpenseTitle2");
		this.endingBookAmount = (Element) elements.get("endingBookAmount");
		this.endingAccumulatedDprcAccount = (Element) elements.get("endingAccumulatedDprcAccount");
		this.legalCalculatedDprcAmount = (Element) elements.get("legalCalculatedDprcAmount");
		this.commonUseDateWarningMes1 = (Element) elements.get("commonUseDateWarningMes1");
		this.cancel_Button = (Element) elements.get("cancel_Button");
		this.code = (Element) elements.get("code");
		this.revisedUsefulLifeForUsedItems_UsefulLife_Save = (Element) elements.get("revisedUsefulLifeForUsedItems_UsefulLife_Save");
		this.popUp_TYOT_BEASDC_all_2 = (Element) elements.get("popUp_TYOT_BEASDC_all_2");
		this.popUp_countOrder_EPY_error_OK = (Element) elements.get("popUp_countOrder_EPY_error_OK");
		this.popUp_assetImport_cancel = (Element) elements.get("popUp_assetImport_cancel");
		this.SAAESP_currentPeriodAmountIncludeExpense = (Element) elements.get("SAAESP_currentPeriodAmountIncludeExpense");
		this.smallAmountAssetExceptionStatementPage_NOE = (Element) elements.get("smallAmountAssetExceptionStatementPage_NOE");
		this.revisedUsefulLifeForUsedItems_LifeButton = (Element) elements.get("revisedUsefulLifeForUsedItems_LifeButton");
		this.paymentDate_Year = (Element) elements.get("paymentDate_Year");
		this.detailPage = (Element) elements.get("detailPage");
		this.tab_month = (Element) elements.get("tab_month");
		this.ThreeYearOneTimeAccountBook_EACFTTBP = (Element) elements.get("ThreeYearOneTimeAccountBook_EACFTTBP");
		this.popUp_countOrder_installation_subtotal = (Element) elements.get("popUp_countOrder_installation_subtotal");
		this.popUp_countOrder_EPY_month = (Element) elements.get("popUp_countOrder_EPY_month");
		this.right_add = (Element) elements.get("right_add");
		this.legalDprcRate = (Element) elements.get("legalDprcRate");
		this.SAAESP_data = (Element) elements.get("SAAESP_data");
		this.name = (Element) elements.get("name");
		this.legalUsefulLifeforNewItems = (Element) elements.get("legalUsefulLifeforNewItems");
		this.accountingDprcLimitAmount_Select = (Element) elements.get("accountingDprcLimitAmount_Select");
		this.tab_movment_second = (Element) elements.get("tab_movment_second");
		this.popUp_TYOT_ACSC = (Element) elements.get("popUp_TYOT_ACSC");
		this.popUp_TYOT_BRDTC = (Element) elements.get("popUp_TYOT_BRDTC");
		this.popUp_EERBL_GE_input = (Element) elements.get("popUp_EERBL_GE_input");
		this.edit_deleComplete = (Element) elements.get("edit_deleComplete");
		this.localTax_pYRInstallation = (Element) elements.get("localTax_pYRInstallation");
		this.popUp_change_GET = (Element) elements.get("popUp_change_GET");
		this.edit = (Element) elements.get("edit");
		this.simplePage_nonOperatingExpense = (Element) elements.get("simplePage_nonOperatingExpense");
		this.right_editBusinessRatioByLump = (Element) elements.get("right_editBusinessRatioByLump");
		this.accountAsset_capitalExpense = (Element) elements.get("accountAsset_capitalExpense");
		this.accountingPaymentTerm = (Element) elements.get("accountingPaymentTerm");
		this.fixedAssets_Simple_code = (Element) elements.get("fixedAssets_Simple_code");
		this.edit_editBusinessRatioByLump = (Element) elements.get("edit_editBusinessRatioByLump");
		this.ThreeYearOneTimeAccountBook_MTE = (Element) elements.get("ThreeYearOneTimeAccountBook_MTE");
		this.legalResidualRate = (Element) elements.get("legalResidualRate");
		this.popUp_assetImport_input = (Element) elements.get("popUp_assetImport_input");
		this.popUp_countOrder_EPY_day_5 = (Element) elements.get("popUp_countOrder_EPY_day_5");
		this.popUp_countOrder_EPY_CPTill = (Element) elements.get("popUp_countOrder_EPY_CPTill");
		this.popUp_countOrder_EPY_day_2 = (Element) elements.get("popUp_countOrder_EPY_day_2");
		this.accountingCalculatedDprcAmount = (Element) elements.get("accountingCalculatedDprcAmount");
		this.popUp_countOrder_EPY_day_3 = (Element) elements.get("popUp_countOrder_EPY_day_3");
		this.popUp_countOrder_EPY_day_4 = (Element) elements.get("popUp_countOrder_EPY_day_4");
		this.localTax_cYRInstallation = (Element) elements.get("localTax_cYRInstallation");
		this.popUp_countOrder_EPY_day = (Element) elements.get("popUp_countOrder_EPY_day");
		this.popUp_assetImportConfirm_firstNum = (Element) elements.get("popUp_assetImportConfirm_firstNum");
		this.detailPage_assetCode = (Element) elements.get("detailPage_assetCode");
		this.localTax_alllncreaseCode = (Element) elements.get("localTax_alllncreaseCode");
		this.paymentDate_Day = (Element) elements.get("paymentDate_Day");
		this.right_codeAdd = (Element) elements.get("right_codeAdd");
		this.popUp_TYOT_CDA_2 = (Element) elements.get("popUp_TYOT_CDA_2");
		this.localTax_decreaseCause = (Element) elements.get("localTax_decreaseCause");
		this.popUp_countOrder_AUSAAEP = (Element) elements.get("popUp_countOrder_AUSAAEP");
		this.structure = (Element) elements.get("structure");
		this.revisedUsefulLifeForUsedItems_Kind = (Element) elements.get("revisedUsefulLifeForUsedItems_Kind");
		this.save_Button = (Element) elements.get("save_Button");
		this.calculationBasicData = (Element) elements.get("calculationBasicData");
		this.popUp_countOrder_EPY_errorMessage = (Element) elements.get("popUp_countOrder_EPY_errorMessage");
		this.popUp_TYOT_CDA = (Element) elements.get("popUp_TYOT_CDA");
		this.localTax_pYROffice = (Element) elements.get("localTax_pYROffice");
		this.localTax_limitAmount5Per = (Element) elements.get("localTax_limitAmount5Per");
		this.legalResidualTerm = (Element) elements.get("legalResidualTerm");
		this.simplePage_NOE = (Element) elements.get("simplePage_NOE");
		this.specialDprcType = (Element) elements.get("specialDprcType");
		this.popUp_createNewPeriod_cancel2 = (Element) elements.get("popUp_createNewPeriod_cancel2");
		this.delAsset_Button = (Element) elements.get("delAsset_Button");
		this.warningMes1 = (Element) elements.get("warningMes1");
		this.popUp_editExpenseRatioByLump = (Element) elements.get("popUp_editExpenseRatioByLump");
		this.warningMes2 = (Element) elements.get("warningMes2");
		this.acquisitionData_IncreaseAssetTiming = (Element) elements.get("acquisitionData_IncreaseAssetTiming");
		this.simplePage_generalExpense = (Element) elements.get("simplePage_generalExpense");
		this.close_Button = (Element) elements.get("close_Button");
		this.popUp_TYOT_CDAC_2 = (Element) elements.get("popUp_TYOT_CDAC_2");
		this.popUp_assetImport_error = (Element) elements.get("popUp_assetImport_error");
		this.localTax_alllncreaseMoveType = (Element) elements.get("localTax_alllncreaseMoveType");
		this.legalIncreasedDprcAmount = (Element) elements.get("legalIncreasedDprcAmount");
		this.ThreeYearOneTimeAccountBook = (Element) elements.get("ThreeYearOneTimeAccountBook");
		this.edit_AddTwo = (Element) elements.get("edit_AddTwo");
		this.popUp_EERBL_MTE_title = (Element) elements.get("popUp_EERBL_MTE_title");
		this.ThreeYearOneTimeAccountBook_Retirment = (Element) elements.get("ThreeYearOneTimeAccountBook_Retirment");
		this.popUp_assetImport_noData_cancel = (Element) elements.get("popUp_assetImport_noData_cancel");
		this.popUp_TYOT_BEASC_all = (Element) elements.get("popUp_TYOT_BEASC_all");
		this.ThreeYearOneTimeAccountBook_EBA = (Element) elements.get("ThreeYearOneTimeAccountBook_EBA");
		this.OK = (Element) elements.get("OK");
		this.popUp_countOrder_account = (Element) elements.get("popUp_countOrder_account");
		this.basic_Information = (Element) elements.get("basic_Information");
		this.accountingFixedRateMethodRevisedAcquisitionCost = (Element) elements.get("accountingFixedRateMethodRevisedAcquisitionCost");
		this.accountingCurrentPeriodTerm = (Element) elements.get("accountingCurrentPeriodTerm");
		this.ThreeYearOneTimeAccountBook_nonBusiness_t = (Element) elements.get("ThreeYearOneTimeAccountBook_nonBusiness_t");
		this.legalDprcLimitAmount_Input = (Element) elements.get("legalDprcLimitAmount_Input");
		this.popUp_assetImport_title = (Element) elements.get("popUp_assetImport_title");
		this.popUp_expenseTitleChange_error = (Element) elements.get("popUp_expenseTitleChange_error");
		this.localTax_decreaseMoveCause = (Element) elements.get("localTax_decreaseMoveCause");
		this.localTax = (Element) elements.get("localTax");
		this.accountingSpecialDprcAmount = (Element) elements.get("accountingSpecialDprcAmount");
		this.detailPage_legalCalculatedDprcAmount = (Element) elements.get("detailPage_legalCalculatedDprcAmount");
		this.recover_Button = (Element) elements.get("recover_Button");
		this.SAAESP_nonBussiness_title = (Element) elements.get("SAAESP_nonBussiness_title");
		this.localTax_increaseCause = (Element) elements.get("localTax_increaseCause");
		this.ThreeYearOneTimeAccountBook_assetName = (Element) elements.get("ThreeYearOneTimeAccountBook_assetName");
		this.popUp_EBRBL_ok = (Element) elements.get("popUp_EBRBL_ok");
		this.businessRatio = (Element) elements.get("businessRatio");
		this.legalCurrentPeriodTerm = (Element) elements.get("legalCurrentPeriodTerm");
		this.fixedAssets_Simple_second = (Element) elements.get("fixedAssets_Simple_second");
		this.ThreeYearOneTimeAccountBook_CPDLA = (Element) elements.get("ThreeYearOneTimeAccountBook_CPDLA");
		this.accountingDprcMethod = (Element) elements.get("accountingDprcMethod");
		this.ThreeYearOneTimeAccountBook_EACDA = (Element) elements.get("ThreeYearOneTimeAccountBook_EACDA");
		this.previousPeriodExcessAmountBroughtForward = (Element) elements.get("previousPeriodExcessAmountBroughtForward");
		this.commonUseDate_Day = (Element) elements.get("commonUseDate_Day");
		this.popUp_editExcutingRatioByLump = (Element) elements.get("popUp_editExcutingRatioByLump");
		this.legalDprcLimitAmount_Select = (Element) elements.get("legalDprcLimitAmount_Select");
		this.smallAmountAssetExceptionStatementPage = (Element) elements.get("smallAmountAssetExceptionStatementPage");
		this.popUp_assetImportConfirm_cancel = (Element) elements.get("popUp_assetImportConfirm_cancel");
		this.popUp_calculate_title = (Element) elements.get("popUp_calculate_title");
		this.popUp_countOrder_accountType = (Element) elements.get("popUp_countOrder_accountType");
		this.accountingCalculatedDprcAmount_DA = (Element) elements.get("accountingCalculatedDprcAmount_DA");
		this.popUp_TYOT_RBBAF = (Element) elements.get("popUp_TYOT_RBBAF");
		this.popUp_assetImport_warning_text = (Element) elements.get("popUp_assetImport_warning_text");
		this.beginningReservedAmount = (Element) elements.get("beginningReservedAmount");
		this.SAAESP_department = (Element) elements.get("SAAESP_department");
		this.ThreeYearOneTimeAccountBook_manufacturingExpenseRatio = (Element) elements.get("ThreeYearOneTimeAccountBook_manufacturingExpenseRatio");
		this.account_List = (Element) elements.get("account_List");
		this.localTax_usefulLife = (Element) elements.get("localTax_usefulLife");
		this.legalDprcLimitDetailButton = (Element) elements.get("legalDprcLimitDetailButton");
		this.SAAESP_legalSpecialDprcAmount = (Element) elements.get("SAAESP_legalSpecialDprcAmount");
		this.ThreeYearOneTimeAccountBook_data = (Element) elements.get("ThreeYearOneTimeAccountBook_data");
		this.tab_month_2 = (Element) elements.get("tab_month_2");
		this.popUp_assetImport_execute_get = (Element) elements.get("popUp_assetImport_execute_get");
		this.popUp_TYOT_CUPC = (Element) elements.get("popUp_TYOT_CUPC");
		this.popUp_EBRBL_businessRadio_format = (Element) elements.get("popUp_EBRBL_businessRadio_format");
		this.SAAESP_summary = (Element) elements.get("SAAESP_summary");
		this.legalMemorandumValue = (Element) elements.get("legalMemorandumValue");
		this.popUp_assetImportConfirm_causeError = (Element) elements.get("popUp_assetImportConfirm_causeError");
		this.legalFixedRateMethodRevisedAcquisitionCost = (Element) elements.get("legalFixedRateMethodRevisedAcquisitionCost");
		this.popUp_countOrder_EPY_CPTill_4 = (Element) elements.get("popUp_countOrder_EPY_CPTill_4");
		this.smallAmountAssetExceptionStatementPage_MTE = (Element) elements.get("smallAmountAssetExceptionStatementPage_MTE");
		this.popUp_countOrder_EPY_CPTill_3 = (Element) elements.get("popUp_countOrder_EPY_CPTill_3");
		this.menuBar_input_changeReportScreen = (Element) elements.get("menuBar_input_changeReportScreen");
		this.popUp_EERBL_MTE_input = (Element) elements.get("popUp_EERBL_MTE_input");
		this.popUp_countOrder_EPY_CPTill_5 = (Element) elements.get("popUp_countOrder_EPY_CPTill_5");
		this.popUp_calculate_OK = (Element) elements.get("popUp_calculate_OK");
		this.popUp_countOrder_EPY_CPTill_2 = (Element) elements.get("popUp_countOrder_EPY_CPTill_2");
		this.popUp_countOrder_EPY_CPTill_1 = (Element) elements.get("popUp_countOrder_EPY_CPTill_1");
		this.commonUseDate_Year = (Element) elements.get("commonUseDate_Year");
		this.detailPage_manufacturingExpense = (Element) elements.get("detailPage_manufacturingExpense");
		this.increasedDprcRate = (Element) elements.get("increasedDprcRate");
		this.popUp_EERBL_NOE_title = (Element) elements.get("popUp_EERBL_NOE_title");
		this.warningButton2_Y = (Element) elements.get("warningButton2_Y");
		this.accountingUsefulLife = (Element) elements.get("accountingUsefulLife");
		this.changeOfDprcMethodButton = (Element) elements.get("changeOfDprcMethodButton");
		this.tab_install_second = (Element) elements.get("tab_install_second");
		this.balanceAcquisitionCost = (Element) elements.get("balanceAcquisitionCost");
		this.simplePage_manufacturingExpense = (Element) elements.get("simplePage_manufacturingExpense");
		this.popUp_countOrder_EPY_cancel = (Element) elements.get("popUp_countOrder_EPY_cancel");
		this.statementPage_dprcMethod = (Element) elements.get("statementPage_dprcMethod");
		this.accountingDprcRate = (Element) elements.get("accountingDprcRate");
		this.popUp_EExRBL_percent = (Element) elements.get("popUp_EExRBL_percent");
		this.summary = (Element) elements.get("summary");
		this.popUp_change_MTE = (Element) elements.get("popUp_change_MTE");
		this.edit_editExpenseRatioByLump = (Element) elements.get("edit_editExpenseRatioByLump");
		this.ThreeYearOneTimeAccountBook_generalExpenseRatio = (Element) elements.get("ThreeYearOneTimeAccountBook_generalExpenseRatio");
		this.detailPage_executingRate = (Element) elements.get("detailPage_executingRate");
		this.usefulLifeTable_DetailList = (Element) elements.get("usefulLifeTable_DetailList");
		this.popUp_countOrder_EPY_error = (Element) elements.get("popUp_countOrder_EPY_error");
		this.SAAESP_manufacturingExpense = (Element) elements.get("SAAESP_manufacturingExpense");
		this.popUp_countOrder_drcpMethod = (Element) elements.get("popUp_countOrder_drcpMethod");
		this.previousPeriodExcessAndDeficitAmountBroughtForward = (Element) elements.get("previousPeriodExcessAndDeficitAmountBroughtForward");
		this.right_editExpenseRatioByLump = (Element) elements.get("right_editExpenseRatioByLump");
		this.popUp_TYOT_BBASC_all_2 = (Element) elements.get("popUp_TYOT_BBASC_all_2");
		this.quantity = (Element) elements.get("quantity");
		this.localTax_decreaseType = (Element) elements.get("localTax_decreaseType");
		this.accountingSpecialDprcLimitAmount = (Element) elements.get("accountingSpecialDprcLimitAmount");
		this.acquisitionData_Day = (Element) elements.get("acquisitionData_Day");
		this.acquisitionData_Month = (Element) elements.get("acquisitionData_Month");
		this.generalDprcLimitAmount = (Element) elements.get("generalDprcLimitAmount");
		this.popUp_expenseTitleChange_GE_title = (Element) elements.get("popUp_expenseTitleChange_GE_title");
		this.popUp_createNewPeriod_message = (Element) elements.get("popUp_createNewPeriod_message");
		this.dprcChange_Save = (Element) elements.get("dprcChange_Save");
		this.ThreeYearOneTimeAccountBook_PEABF = (Element) elements.get("ThreeYearOneTimeAccountBook_PEABF");
		this.popUp_EERBL_GE_percent = (Element) elements.get("popUp_EERBL_GE_percent");
		this.localTax_alllncreaseMoveCause = (Element) elements.get("localTax_alllncreaseMoveCause");
		this.deleteData_Button = (Element) elements.get("deleteData_Button");
		this.popUp_createNewPeriod_OK = (Element) elements.get("popUp_createNewPeriod_OK");
		this.localTax_assetName = (Element) elements.get("localTax_assetName");
		this.statementNOM = (Element) elements.get("statementNOM");
		this.legalDprcMethod = (Element) elements.get("legalDprcMethod");
		this.popUp_assetImport_EPSON_message = (Element) elements.get("popUp_assetImport_EPSON_message");
		this.SAAESP_currentPeriodDprcAmount = (Element) elements.get("SAAESP_currentPeriodDprcAmount");
		this.simplePage = (Element) elements.get("simplePage");
		this.edit_addAndCopy = (Element) elements.get("edit_addAndCopy");
		this.specialDprcRate = (Element) elements.get("specialDprcRate");
		this.legalSpecialDprcAmount = (Element) elements.get("legalSpecialDprcAmount");
		this.currentPeriodAmountIncludedInExpenses = (Element) elements.get("currentPeriodAmountIncludedInExpenses");
		this.dprcDeficitAmount = (Element) elements.get("dprcDeficitAmount");
		this.popUp_assetImportConfirm_get = (Element) elements.get("popUp_assetImportConfirm_get");
		this.currentPeriodDprcAmount = (Element) elements.get("currentPeriodDprcAmount");
		this.SAAESP_method = (Element) elements.get("SAAESP_method");
		this.popUp_createNewPeriod_cancel = (Element) elements.get("popUp_createNewPeriod_cancel");
		this.popUp_EERBL_MTE_percent = (Element) elements.get("popUp_EERBL_MTE_percent");
		this.retirement_Year = (Element) elements.get("retirement_Year");
		this.localTax_assetType = (Element) elements.get("localTax_assetType");
		this.detail = (Element) elements.get("detail");
		this.dprcLiabilityReserveMethod_reserve = (Element) elements.get("dprcLiabilityReserveMethod_reserve");
		this.cancel = (Element) elements.get("cancel");
		this.simpleBusinessRadio = (Element) elements.get("simpleBusinessRadio");
		this.popUp_expenseTitleChange_ok = (Element) elements.get("popUp_expenseTitleChange_ok");
		this.ThreeYearOneTimeAccountBook_quantity = (Element) elements.get("ThreeYearOneTimeAccountBook_quantity");
		this.edit_Add = (Element) elements.get("edit_Add");
		this.legalCalculatedDprcAmount_DA = (Element) elements.get("legalCalculatedDprcAmount_DA");
		this.installationSite_List = (Element) elements.get("installationSite_List");
		this.popUp_EExRBL_input = (Element) elements.get("popUp_EExRBL_input");
		this.localTax_taxable = (Element) elements.get("localTax_taxable");
		this.signify = (Element) elements.get("signify");
		this.localTax_preciousYearReturnValuation = (Element) elements.get("localTax_preciousYearReturnValuation");
		this.edit_Button = (Element) elements.get("edit_Button");
		this.ThreeYearOneTimeNOM = (Element) elements.get("ThreeYearOneTimeNOM");
		this.popUp_countOrder_RST = (Element) elements.get("popUp_countOrder_RST");
		this.accountingDprcAmount = (Element) elements.get("accountingDprcAmount");
		this.right_recover = (Element) elements.get("right_recover");
		this.account_List_firstLine = (Element) elements.get("account_List_firstLine");
		this.fixedAssets_TYOT_second = (Element) elements.get("fixedAssets_TYOT_second");
		this.revisedUsefulLifeForUsedItems_Search = (Element) elements.get("revisedUsefulLifeForUsedItems_Search");
		this.popUp_assetImport_warning_title = (Element) elements.get("popUp_assetImport_warning_title");
		this.usefulLifeTableButton = (Element) elements.get("usefulLifeTableButton");
		this.applicationArtical = (Element) elements.get("applicationArtical");
		this.localTax_residualRate = (Element) elements.get("localTax_residualRate");
		this.popUp_TYOT_BEASDC_all = (Element) elements.get("popUp_TYOT_BEASDC_all");
		this.detailNOM = (Element) elements.get("detailNOM");
		this.manufacturingExpenseRatio = (Element) elements.get("manufacturingExpenseRatio");
		this.accountAsset_Code = (Element) elements.get("accountAsset_Code");
		this.revisedUsefulLifeForUsedItems_Save = (Element) elements.get("revisedUsefulLifeForUsedItems_Save");
		this.OK_button = (Element) elements.get("OK_button");
		this.popUp_expenseTitleChange_NOE_title = (Element) elements.get("popUp_expenseTitleChange_NOE_title");
		this.commonUseDate_Era = (Element) elements.get("commonUseDate_Era");
		this.assetBaseList = (Element) elements.get("assetBaseList");
		this.popUp_TYOT_CDAC = (Element) elements.get("popUp_TYOT_CDAC");
		this.nonOperatingExpenseRatio = (Element) elements.get("nonOperatingExpenseRatio");
		this.file_save = (Element) elements.get("file_save");
		this.paymentAmount = (Element) elements.get("paymentAmount");
		this.SAAESP_installation = (Element) elements.get("SAAESP_installation");
		this.menuBar_input = (Element) elements.get("menuBar_input");
		this.popUp_assetImport_JDL_message = (Element) elements.get("popUp_assetImport_JDL_message");
		this.popUp_expenseTitleChange_title = (Element) elements.get("popUp_expenseTitleChange_title");
		this.popUp_assetImport_reference = (Element) elements.get("popUp_assetImport_reference");
		this.manufacturingExpenseTextCenter = (Element) elements.get("manufacturingExpenseTextCenter");
		this.popUp_EERBL_cancel = (Element) elements.get("popUp_EERBL_cancel");
		this.retirement_Era = (Element) elements.get("retirement_Era");
		this.SAAESP_quantity = (Element) elements.get("SAAESP_quantity");
		this.right_editExcutingRatioByLump = (Element) elements.get("right_editExcutingRatioByLump");
		this.usefulLifeTable_Search = (Element) elements.get("usefulLifeTable_Search");
		this.SAAESP_assetName = (Element) elements.get("SAAESP_assetName");
		this.edit_edit = (Element) elements.get("edit_edit");
		this.detailPage_NOE = (Element) elements.get("detailPage_NOE");
		this.popUp_expenseTitleChange_MTE_title = (Element) elements.get("popUp_expenseTitleChange_MTE_title");
		this.file_save2 = (Element) elements.get("file_save2");
		this.accountingResidualTerm = (Element) elements.get("accountingResidualTerm");
		this.file_import = (Element) elements.get("file_import");
		this.retirement_Month = (Element) elements.get("retirement_Month");
		this.generalDprcAmount = (Element) elements.get("generalDprcAmount");
		this.popUp_EBRBL_businessRadio_ok = (Element) elements.get("popUp_EBRBL_businessRadio_ok");
		this.tab_day_2 = (Element) elements.get("tab_day_2");
		this.popUp_EBRBL_cancel = (Element) elements.get("popUp_EBRBL_cancel");
		this.popUp_countOrder_AUTYOTDP_assetList = (Element) elements.get("popUp_countOrder_AUTYOTDP_assetList");
		this.edit_dele = (Element) elements.get("edit_dele");
		this.popUp_EExRBL_ok = (Element) elements.get("popUp_EExRBL_ok");
		this.tab = (Element) elements.get("tab");
		this.fixedAssets_Simple_first = (Element) elements.get("fixedAssets_Simple_first");
		this.ThreeYearOneTimeAccountBook_NOE = (Element) elements.get("ThreeYearOneTimeAccountBook_NOE");
		this.ThreeYearOneTimeAccountBook_summary = (Element) elements.get("ThreeYearOneTimeAccountBook_summary");
		this.legalUseLife = (Element) elements.get("legalUseLife");
		this.file = (Element) elements.get("file");
		this.popUp_TYOT_BBASC_all_value = (Element) elements.get("popUp_TYOT_BBASC_all_value");
		this.popUp_TYOT_ACSC_2 = (Element) elements.get("popUp_TYOT_ACSC_2");
		this.accountSimple = (Element) elements.get("accountSimple");
		this.dprcLiabilityReserveMethod_dprc = (Element) elements.get("dprcLiabilityReserveMethod_dprc");
		this.usefulLifeTable_Save = (Element) elements.get("usefulLifeTable_Save");
		this.dprcRetirement = (Element) elements.get("dprcRetirement");
		this.installationSite_Input = (Element) elements.get("installationSite_Input");
		this.popUp_TYOT_BBASC_all = (Element) elements.get("popUp_TYOT_BBASC_all");
		this.beginningAccumulatedDprcAccount = (Element) elements.get("beginningAccumulatedDprcAccount");
		this.popUp_countOrder_installation = (Element) elements.get("popUp_countOrder_installation");
		this.edit_TYOT2 = (Element) elements.get("edit_TYOT2");
		this.reversalAmountOfReservedAmountDuringThePeriod = (Element) elements.get("reversalAmountOfReservedAmountDuringThePeriod");
		this.accountingDprcInputFlag = (Element) elements.get("accountingDprcInputFlag");
		this.right_edit = (Element) elements.get("right_edit");
		this.tab_department_second = (Element) elements.get("tab_department_second");
		this.popUp_expenseTitleChange_MTE_input = (Element) elements.get("popUp_expenseTitleChange_MTE_input");
		this.commonUseDate_IncreaseAssetTiming = (Element) elements.get("commonUseDate_IncreaseAssetTiming");
		this.delete_Button = (Element) elements.get("delete_Button");
		this.department_Input = (Element) elements.get("department_Input");
		this.account_Input = (Element) elements.get("account_Input");
		this.retirementCause = (Element) elements.get("retirementCause");
		this.revisedUsefulLifeForUsedItemsButton = (Element) elements.get("revisedUsefulLifeForUsedItemsButton");
		this.account_Button = (Element) elements.get("account_Button");
		this.popUp_assetImport_execute = (Element) elements.get("popUp_assetImport_execute");
		this.popUp_TYOT_OTDAMT = (Element) elements.get("popUp_TYOT_OTDAMT");
		this.ThreeYearOneTimeAccountBook_notRetirment = (Element) elements.get("ThreeYearOneTimeAccountBook_notRetirment");
		this.popUp_countOrder_ok_list = (Element) elements.get("popUp_countOrder_ok_list");
		this.tab_installationSite_2 = (Element) elements.get("tab_installationSite_2");
		this.SAAESP_nonOperatingExpense = (Element) elements.get("SAAESP_nonOperatingExpense");
		this.popUp_countOrder_AUSAAEP_assetList = (Element) elements.get("popUp_countOrder_AUSAAEP_assetList");
		this.detailPage_GE = (Element) elements.get("detailPage_GE");
		this.popUp_assetImportConfirm_secondNum = (Element) elements.get("popUp_assetImportConfirm_secondNum");
		this.acquisitionCost = (Element) elements.get("acquisitionCost");
		this.file_createNewPeriod = (Element) elements.get("file_createNewPeriod");
		this.revisedUsefulLifeForUsedItems_Structure = (Element) elements.get("revisedUsefulLifeForUsedItems_Structure");
		this.tab_year_2 = (Element) elements.get("tab_year_2");
		this.accountingRevisedDprcRate = (Element) elements.get("accountingRevisedDprcRate");
		this.department_List = (Element) elements.get("department_List");
		this.popUp_countOrder_AUTYOTDP_TYOTDList = (Element) elements.get("popUp_countOrder_AUTYOTDP_TYOTDList");
		this.popUp_countOrder_EPY_OK = (Element) elements.get("popUp_countOrder_EPY_OK");
		this.SAAESP_decreasedAssetAmount = (Element) elements.get("SAAESP_decreasedAssetAmount");
		this.cancel_button = (Element) elements.get("cancel_button");
		this.accountingMemorandumValue = (Element) elements.get("accountingMemorandumValue");
		this.dprcExcessAmount = (Element) elements.get("dprcExcessAmount");
		this.popUp_EExRBL_cancel = (Element) elements.get("popUp_EExRBL_cancel");
		this.usefulLifeTable_Structure = (Element) elements.get("usefulLifeTable_Structure");
		this.paymentDate_Era = (Element) elements.get("paymentDate_Era");
		this.tab_movment_first = (Element) elements.get("tab_movment_first");
		this.revisedUsefulLifeForUsedItems_CalcType = (Element) elements.get("revisedUsefulLifeForUsedItems_CalcType");
		this.warningButton_Y = (Element) elements.get("warningButton_Y");
		this.popUp_countOrder_AUSAAEP_SAAEDList = (Element) elements.get("popUp_countOrder_AUSAAEP_SAAEDList");
		this.applicationParagraph = (Element) elements.get("applicationParagraph");
		this.fixedAssets_SimpleList = (Element) elements.get("fixedAssets_SimpleList");
		this.popUp_TYOT_BEASDC_all_2_value = (Element) elements.get("popUp_TYOT_BEASDC_all_2_value");
		this.revisedUsefulLifeForUsedItems_LifeForNewItems = (Element) elements.get("revisedUsefulLifeForUsedItems_LifeForNewItems");
		this.acquisitionData_Year = (Element) elements.get("acquisitionData_Year");
		this.popUp_countOrder_editPassedYear = (Element) elements.get("popUp_countOrder_editPassedYear");
		this.popUp_countOrder_EPY_era_5 = (Element) elements.get("popUp_countOrder_EPY_era_5");
		this.popUp_EBRBL_error = (Element) elements.get("popUp_EBRBL_error");
		this.popUp_countOrder_EPY_era_4 = (Element) elements.get("popUp_countOrder_EPY_era_4");
		this.popUp_TYOT_title = (Element) elements.get("popUp_TYOT_title");
		this.popUp_countOrder_EPY_era_3 = (Element) elements.get("popUp_countOrder_EPY_era_3");
		this.accountAsset_Name = (Element) elements.get("accountAsset_Name");
		this.popUp_countOrder_EPY_era_2 = (Element) elements.get("popUp_countOrder_EPY_era_2");
		this.localTax_alllncreaseSummary = (Element) elements.get("localTax_alllncreaseSummary");
		this.popUp_countOrder_EPY_era_1 = (Element) elements.get("popUp_countOrder_EPY_era_1");
		this.simplePage_GE = (Element) elements.get("simplePage_GE");
		this.currentPeriodApprovedAmountOfLoss = (Element) elements.get("currentPeriodApprovedAmountOfLoss");
		this.tab_year = (Element) elements.get("tab_year");
		this.popUp_expenseTitleChange_cancel = (Element) elements.get("popUp_expenseTitleChange_cancel");
		this.SAAESP_increasedAssetAmount = (Element) elements.get("SAAESP_increasedAssetAmount");
		this.localTax_levyDate = (Element) elements.get("localTax_levyDate");
		this.revisedUsefulLifeForUsedItems_SearchInput = (Element) elements.get("revisedUsefulLifeForUsedItems_SearchInput");
		this.localTax_decreaseMoveType = (Element) elements.get("localTax_decreaseMoveType");
		this.statementPage = (Element) elements.get("statementPage");
		this.popUp_countOrder_EPY_error2_OK = (Element) elements.get("popUp_countOrder_EPY_error2_OK");
		this.SAAESP_beginningBookAmount = (Element) elements.get("SAAESP_beginningBookAmount");
		this.revisedUsefulLifeForUsedItems_UsefulLifeList = (Element) elements.get("revisedUsefulLifeForUsedItems_UsefulLifeList");
		this.smallAmountAssetExceptionStatementPage_GE = (Element) elements.get("smallAmountAssetExceptionStatementPage_GE");
		this.popUp_TYOT_ACOMC = (Element) elements.get("popUp_TYOT_ACOMC");
		this.numberOfMonth_small = (Element) elements.get("numberOfMonth_small");
		this.popUp_assetImport_esc = (Element) elements.get("popUp_assetImport_esc");
		this.SAAESP_generalExpense = (Element) elements.get("SAAESP_generalExpense");
		this.increaseCause = (Element) elements.get("increaseCause");
		this.ThreeYearOneTimeAccountBook_acquisitionCost = (Element) elements.get("ThreeYearOneTimeAccountBook_acquisitionCost");
		this.SAAESP_accumulatedDprcAccount = (Element) elements.get("SAAESP_accumulatedDprcAccount");
		this.popUp_TYOT_BEASC_all_2 = (Element) elements.get("popUp_TYOT_BEASC_all_2");
		this.detailPage_generalExpense = (Element) elements.get("detailPage_generalExpense");
		this.popup_Dprc_revisedUsefulLifeInfoTitle = (Element) elements.get("popup_Dprc_revisedUsefulLifeInfoTitle");
		this.retirement_Day = (Element) elements.get("retirement_Day");
		this.popUp_TYOT_clear = (Element) elements.get("popUp_TYOT_clear");
		this.usefulLifeTable_SearchInput = (Element) elements.get("usefulLifeTable_SearchInput");
		this.popUp_countOrder_CONP = (Element) elements.get("popUp_countOrder_CONP");
		this.legalDprcContent = (Element) elements.get("legalDprcContent");
		this.popUp_EERBL_NOE_input = (Element) elements.get("popUp_EERBL_NOE_input");
		this.retirementMethod = (Element) elements.get("retirementMethod");
		this.reductionEntryType = (Element) elements.get("reductionEntryType");
		this.simplePage_DprcMethod = (Element) elements.get("simplePage_DprcMethod");
		this.generalExpenseTextCenter = (Element) elements.get("generalExpenseTextCenter");
		this.popUp_EERBL_ok = (Element) elements.get("popUp_EERBL_ok");
		this.popUp_assetImportConfirm_second = (Element) elements.get("popUp_assetImportConfirm_second");
		this.popUp_countOrder = (Element) elements.get("popUp_countOrder");
		this.generalExpenseRatio = (Element) elements.get("generalExpenseRatio");
		this.popUp_change_NOE = (Element) elements.get("popUp_change_NOE");
		this.legalRevisedDprcRate = (Element) elements.get("legalRevisedDprcRate");
		this.popup_Dprc_usefulLifeInfoTitle = (Element) elements.get("popup_Dprc_usefulLifeInfoTitle");
		this.edit_calculate = (Element) elements.get("edit_calculate");
		this.accountAsset_CodeSuffix = (Element) elements.get("accountAsset_CodeSuffix");
		this.popUp_countOrder_department_subtotal = (Element) elements.get("popUp_countOrder_department_subtotal");
		this.legalDprcMethod2 = (Element) elements.get("legalDprcMethod2");
		this.detailPage_MTE = (Element) elements.get("detailPage_MTE");
		this.popUp_countOrder_EPY_year = (Element) elements.get("popUp_countOrder_EPY_year");
		this.legalResidualValue = (Element) elements.get("legalResidualValue");
	}
}
