/**
 * 
 */
package com.asaas.test.util;

import java.util.HashMap;

/**
 * @author
 * 
 */
public class BonusPaymentStatements implements Page {
    // Declare variable
	public Element bonusSlipPage;
	public Element popUp_Msg;
	public Element allowanceName;
	public Element payGeneralBonus_dis;
	public Element recipient;
	public Element payGeneralBonus_input;
	public Element bonusPayment;
	public Element bonusAllowanceDeductionSetting;
	public Element twotime_slip;
	public Element taxRate;
	public Element bonusMoneyTypeTable;
	public Element fee2;
	public Element deduction4;
	public Element deduction3;
	public Element socialInsurance_disp;
	public Element deduction2;
	public Element adjustmentAmount;
	public Element lockMonth;
	public Element fee;
	public Element employee3;
	public Element deduction9;
	public Element employee2;
	public Element employee1;
	public Element deduction7;
	public Element generalBonusAmount10;
	public Element deduction8;
	public Element generalBonusAmount11;
	public Element deduction5;
	public Element deduction6;
	public Element incomeTax;
	public Element adjustmentAmount2;
	public Element nursingInsrance_dis;
	public Element deductionName;
	public Element allowanceSet;
	public Element bonusForms_SubmissionForms;
	public Element generalBonusAmountThisTime;
	public Element bonusPaymentSlip;
	public Element unemploymentInsurance2;
	public Element useTwoThousandBills;
	public Element twotime;
	public Element menuBar;
	public Element socialSecurity_dis;
	public Element unemployeeBenefit5;
	public Element recaculaeMenuBar;
	public Element unemployeeBenefit4;
	public Element unemployeeBenefit7;
	public Element unemployeeBenefit6;
	public Element editMenu_dele;
	public Element unemployeeBenefit1;
	public Element unemployeeBenefit3;
	public Element allowanceName10;
	public Element unemployeeBenefit2;
	public Element allowanceName11;
	public Element unemployeeBenefit9;
	public Element unemployeeBenefit8;
	public Element socialInsrance_Sum;
	public Element socialInsurance;
	public Element cancel;
	public Element listofBonuses;
	public Element balancePayment;
	public Element close;
	public Element calculationBasePeriod_dis;
	public Element insertExcessiveDeficitAmount;
	public Element twoThousandBillsInput;
	public Element payGeneralBonus;
	public Element dateSettingNoButton;
	public Element GeneralBonus;
	public Element GeneralBonus2;
	public Element annualAdjustment_disp;
	public Element paymentByCash;
	public Element allowanceValue1;
	public Element taxablePayment3;
	public Element taxablePayment2;
	public Element threetime;
	public Element bonusMoneyTypeTablePage;
	public Element fourtime;
	public Element allowanceName1_dis;
	public Element name;
	public Element bonusEmployeeName;
	public Element socialInsranceSum;
	public Element balancePayment3;
	public Element balancePayment2;
	public Element taxablePayment;
	public Element twoTime_Lock;
	public Element healthInsrance;
	public Element insertExcessive_choose;
	public Element withholdingIncomeTax11;
	public Element withholdingIncomeTax10;
	public Element edit;
	public Element withholdingIncomeTax4;
	public Element withholdingIncomeTax3;
	public Element withholdingIncomeTax2;
	public Element withholdingIncomeTax1;
	public Element onetime_slip;
	public Element withholdingIncomeTax9;
	public Element persionFunds;
	public Element annualAdjustment;
	public Element listofBonusesPage;
	public Element withholdingIncomeTax7;
	public Element withholdingIncomeTax8;
	public Element withholdingIncomeTax5;
	public Element bonusPayment_disp;
	public Element withholdingIncomeTax6;
	public Element deductionValue;
	public Element adjustmentAmount2_disp;
	public Element deductionButton;
	public Element exitOption;
	public Element deductionSum;
	public Element socialSecurity;
	public Element fileMenu_lockMonth;
	public Element definition2;
	public Element bonusTransferRequestPage;
	public Element nursingInsrance;
	public Element allowanceValue1_dispValue;
	public Element insertEmployeeAll;
	public Element transferRequest_button;
	public Element threetime_slip;
	public Element bonusTransferRequest;
	public Element salary_button;
	public Element calculationBasePeriod;
	public Element insertExcessive_change;
	public Element sumData1;
	public Element socialInsrance_Sum2;
	public Element socialInsrance_Sum3;
	public Element memo;
	public Element totalNumberOfFees;
	public Element fileMenu;
	public Element adjustmentAmount_disp;
	public Element delete;
	public Element bonusSlipTitle;
	public Element onetime;
	public Element deduction12;
	public Element deduction13;
	public Element deduction10;
	public Element deduction11;
	public Element persionFunds_dis;
	public Element totalPaymentTax;
	public Element foundAmount_dis;
	public Element lessAllowance_disp;
	public Element deduction18;
	public Element socialInsranceSum2;
	public Element deduction16;
	public Element deduction17;
	public Element deduction14;
	public Element deduction15;
	public Element saveOption;
	public Element popup_save;
	public Element settingOfFixed3;
	public Element sumData_disp;
	public Element settingOfFixed4;
	public Element oneTime_Lock;
	public Element generalBonusAmount9;
	public Element generalBonusAmount7;
	public Element generalBonusAmount8;
	public Element save;
	public Element calculationBasePeriod_disp;
	public Element generalBonusAmount1;
	public Element generalBonusAmount2;
	public Element paymentAmountEtc;
	public Element generalBonusAmount5;
	public Element generalBonusAmount6;
	public Element generalBonusAmount3;
	public Element generalBonusAmount4;
	public Element bonusEmployeeInf;
	public Element undefinPayment;
	public Element insertEmployee2;
	public Element insertEmployee1;
	public Element insertEmployee3;
	public Element dateSettingYesButton;
	public Element fee2_disp;
	public Element totalPaymentNonTax;
	public Element bottomMenu;
	public Element deductionValue_disp;
	public Element fourtime_slip;
	public Element allowanceName2;
	public Element allowanceName6;
	public Element allowanceName5;
	public Element allowanceName4;
	public Element unemploymentInsurance;
	public Element allowanceName3;
	public Element allowanceName9;
	public Element allowanceName8;
	public Element allowanceName7;
	public Element allowanceName_dipName;
	public Element insertExcessiveTitle;
	public Element healthInsrance_disp;
	public Element threeTime_Lock;
	public Element popUp;
	public Element editOption;
	public Element recaculate;
	public Element unemployeeBenefit10;
	public Element editMenu;
	public Element totalTableLegalRecordSalaryIncome;
	public Element unemployeeBenefit11;
	public Element deduction;
	public Element fee_disp;
	public Element deductionName3;
	public Element deductionName2;
	public Element deductionName5;
	public Element definition;
	public Element deductionName4;
	public Element payment2;
	public Element deductionName7;
	public Element deductionName6;
	public Element excute;
	public Element synchronization;
	public Element totalAmountOfFees;
	public Element cancelPayment;
	public Element bonusFormsButton;
	public Element deductionData_dispName;

    /*
     * @see com.asaas.test.util.Page#init(java.util.HashMap)
     */
    public void init(HashMap<String, Object> elements) {
        // Initialize variable
		this.bonusSlipPage = (Element) elements.get("bonusSlipPage");
		this.popUp_Msg = (Element) elements.get("popUp_Msg");
		this.allowanceName = (Element) elements.get("allowanceName");
		this.payGeneralBonus_dis = (Element) elements.get("payGeneralBonus_dis");
		this.recipient = (Element) elements.get("recipient");
		this.payGeneralBonus_input = (Element) elements.get("payGeneralBonus_input");
		this.bonusPayment = (Element) elements.get("bonusPayment");
		this.bonusAllowanceDeductionSetting = (Element) elements.get("bonusAllowanceDeductionSetting");
		this.twotime_slip = (Element) elements.get("twotime_slip");
		this.taxRate = (Element) elements.get("taxRate");
		this.bonusMoneyTypeTable = (Element) elements.get("bonusMoneyTypeTable");
		this.fee2 = (Element) elements.get("fee2");
		this.deduction4 = (Element) elements.get("deduction4");
		this.deduction3 = (Element) elements.get("deduction3");
		this.socialInsurance_disp = (Element) elements.get("socialInsurance_disp");
		this.deduction2 = (Element) elements.get("deduction2");
		this.adjustmentAmount = (Element) elements.get("adjustmentAmount");
		this.lockMonth = (Element) elements.get("lockMonth");
		this.fee = (Element) elements.get("fee");
		this.employee3 = (Element) elements.get("employee3");
		this.deduction9 = (Element) elements.get("deduction9");
		this.employee2 = (Element) elements.get("employee2");
		this.employee1 = (Element) elements.get("employee1");
		this.deduction7 = (Element) elements.get("deduction7");
		this.generalBonusAmount10 = (Element) elements.get("generalBonusAmount10");
		this.deduction8 = (Element) elements.get("deduction8");
		this.generalBonusAmount11 = (Element) elements.get("generalBonusAmount11");
		this.deduction5 = (Element) elements.get("deduction5");
		this.deduction6 = (Element) elements.get("deduction6");
		this.incomeTax = (Element) elements.get("incomeTax");
		this.adjustmentAmount2 = (Element) elements.get("adjustmentAmount2");
		this.nursingInsrance_dis = (Element) elements.get("nursingInsrance_dis");
		this.deductionName = (Element) elements.get("deductionName");
		this.allowanceSet = (Element) elements.get("allowanceSet");
		this.bonusForms_SubmissionForms = (Element) elements.get("bonusForms_SubmissionForms");
		this.generalBonusAmountThisTime = (Element) elements.get("generalBonusAmountThisTime");
		this.bonusPaymentSlip = (Element) elements.get("bonusPaymentSlip");
		this.unemploymentInsurance2 = (Element) elements.get("unemploymentInsurance2");
		this.useTwoThousandBills = (Element) elements.get("useTwoThousandBills");
		this.twotime = (Element) elements.get("twotime");
		this.menuBar = (Element) elements.get("menuBar");
		this.socialSecurity_dis = (Element) elements.get("socialSecurity_dis");
		this.unemployeeBenefit5 = (Element) elements.get("unemployeeBenefit5");
		this.recaculaeMenuBar = (Element) elements.get("recaculaeMenuBar");
		this.unemployeeBenefit4 = (Element) elements.get("unemployeeBenefit4");
		this.unemployeeBenefit7 = (Element) elements.get("unemployeeBenefit7");
		this.unemployeeBenefit6 = (Element) elements.get("unemployeeBenefit6");
		this.editMenu_dele = (Element) elements.get("editMenu_dele");
		this.unemployeeBenefit1 = (Element) elements.get("unemployeeBenefit1");
		this.unemployeeBenefit3 = (Element) elements.get("unemployeeBenefit3");
		this.allowanceName10 = (Element) elements.get("allowanceName10");
		this.unemployeeBenefit2 = (Element) elements.get("unemployeeBenefit2");
		this.allowanceName11 = (Element) elements.get("allowanceName11");
		this.unemployeeBenefit9 = (Element) elements.get("unemployeeBenefit9");
		this.unemployeeBenefit8 = (Element) elements.get("unemployeeBenefit8");
		this.socialInsrance_Sum = (Element) elements.get("socialInsrance_Sum");
		this.socialInsurance = (Element) elements.get("socialInsurance");
		this.cancel = (Element) elements.get("cancel");
		this.listofBonuses = (Element) elements.get("listofBonuses");
		this.balancePayment = (Element) elements.get("balancePayment");
		this.close = (Element) elements.get("close");
		this.calculationBasePeriod_dis = (Element) elements.get("calculationBasePeriod_dis");
		this.insertExcessiveDeficitAmount = (Element) elements.get("insertExcessiveDeficitAmount");
		this.twoThousandBillsInput = (Element) elements.get("twoThousandBillsInput");
		this.payGeneralBonus = (Element) elements.get("payGeneralBonus");
		this.dateSettingNoButton = (Element) elements.get("dateSettingNoButton");
		this.GeneralBonus = (Element) elements.get("GeneralBonus");
		this.GeneralBonus2 = (Element) elements.get("GeneralBonus2");
		this.annualAdjustment_disp = (Element) elements.get("annualAdjustment_disp");
		this.paymentByCash = (Element) elements.get("paymentByCash");
		this.allowanceValue1 = (Element) elements.get("allowanceValue1");
		this.taxablePayment3 = (Element) elements.get("taxablePayment3");
		this.taxablePayment2 = (Element) elements.get("taxablePayment2");
		this.threetime = (Element) elements.get("threetime");
		this.bonusMoneyTypeTablePage = (Element) elements.get("bonusMoneyTypeTablePage");
		this.fourtime = (Element) elements.get("fourtime");
		this.allowanceName1_dis = (Element) elements.get("allowanceName1_dis");
		this.name = (Element) elements.get("name");
		this.bonusEmployeeName = (Element) elements.get("bonusEmployeeName");
		this.socialInsranceSum = (Element) elements.get("socialInsranceSum");
		this.balancePayment3 = (Element) elements.get("balancePayment3");
		this.balancePayment2 = (Element) elements.get("balancePayment2");
		this.taxablePayment = (Element) elements.get("taxablePayment");
		this.twoTime_Lock = (Element) elements.get("twoTime_Lock");
		this.healthInsrance = (Element) elements.get("healthInsrance");
		this.insertExcessive_choose = (Element) elements.get("insertExcessive_choose");
		this.withholdingIncomeTax11 = (Element) elements.get("withholdingIncomeTax11");
		this.withholdingIncomeTax10 = (Element) elements.get("withholdingIncomeTax10");
		this.edit = (Element) elements.get("edit");
		this.withholdingIncomeTax4 = (Element) elements.get("withholdingIncomeTax4");
		this.withholdingIncomeTax3 = (Element) elements.get("withholdingIncomeTax3");
		this.withholdingIncomeTax2 = (Element) elements.get("withholdingIncomeTax2");
		this.withholdingIncomeTax1 = (Element) elements.get("withholdingIncomeTax1");
		this.onetime_slip = (Element) elements.get("onetime_slip");
		this.withholdingIncomeTax9 = (Element) elements.get("withholdingIncomeTax9");
		this.persionFunds = (Element) elements.get("persionFunds");
		this.annualAdjustment = (Element) elements.get("annualAdjustment");
		this.listofBonusesPage = (Element) elements.get("listofBonusesPage");
		this.withholdingIncomeTax7 = (Element) elements.get("withholdingIncomeTax7");
		this.withholdingIncomeTax8 = (Element) elements.get("withholdingIncomeTax8");
		this.withholdingIncomeTax5 = (Element) elements.get("withholdingIncomeTax5");
		this.bonusPayment_disp = (Element) elements.get("bonusPayment_disp");
		this.withholdingIncomeTax6 = (Element) elements.get("withholdingIncomeTax6");
		this.deductionValue = (Element) elements.get("deductionValue");
		this.adjustmentAmount2_disp = (Element) elements.get("adjustmentAmount2_disp");
		this.deductionButton = (Element) elements.get("deductionButton");
		this.exitOption = (Element) elements.get("exitOption");
		this.deductionSum = (Element) elements.get("deductionSum");
		this.socialSecurity = (Element) elements.get("socialSecurity");
		this.fileMenu_lockMonth = (Element) elements.get("fileMenu_lockMonth");
		this.definition2 = (Element) elements.get("definition2");
		this.bonusTransferRequestPage = (Element) elements.get("bonusTransferRequestPage");
		this.nursingInsrance = (Element) elements.get("nursingInsrance");
		this.allowanceValue1_dispValue = (Element) elements.get("allowanceValue1_dispValue");
		this.insertEmployeeAll = (Element) elements.get("insertEmployeeAll");
		this.transferRequest_button = (Element) elements.get("transferRequest_button");
		this.threetime_slip = (Element) elements.get("threetime_slip");
		this.bonusTransferRequest = (Element) elements.get("bonusTransferRequest");
		this.salary_button = (Element) elements.get("salary_button");
		this.calculationBasePeriod = (Element) elements.get("calculationBasePeriod");
		this.insertExcessive_change = (Element) elements.get("insertExcessive_change");
		this.sumData1 = (Element) elements.get("sumData1");
		this.socialInsrance_Sum2 = (Element) elements.get("socialInsrance_Sum2");
		this.socialInsrance_Sum3 = (Element) elements.get("socialInsrance_Sum3");
		this.memo = (Element) elements.get("memo");
		this.totalNumberOfFees = (Element) elements.get("totalNumberOfFees");
		this.fileMenu = (Element) elements.get("fileMenu");
		this.adjustmentAmount_disp = (Element) elements.get("adjustmentAmount_disp");
		this.delete = (Element) elements.get("delete");
		this.bonusSlipTitle = (Element) elements.get("bonusSlipTitle");
		this.onetime = (Element) elements.get("onetime");
		this.deduction12 = (Element) elements.get("deduction12");
		this.deduction13 = (Element) elements.get("deduction13");
		this.deduction10 = (Element) elements.get("deduction10");
		this.deduction11 = (Element) elements.get("deduction11");
		this.persionFunds_dis = (Element) elements.get("persionFunds_dis");
		this.totalPaymentTax = (Element) elements.get("totalPaymentTax");
		this.foundAmount_dis = (Element) elements.get("foundAmount_dis");
		this.lessAllowance_disp = (Element) elements.get("lessAllowance_disp");
		this.deduction18 = (Element) elements.get("deduction18");
		this.socialInsranceSum2 = (Element) elements.get("socialInsranceSum2");
		this.deduction16 = (Element) elements.get("deduction16");
		this.deduction17 = (Element) elements.get("deduction17");
		this.deduction14 = (Element) elements.get("deduction14");
		this.deduction15 = (Element) elements.get("deduction15");
		this.saveOption = (Element) elements.get("saveOption");
		this.popup_save = (Element) elements.get("popup_save");
		this.settingOfFixed3 = (Element) elements.get("settingOfFixed3");
		this.sumData_disp = (Element) elements.get("sumData_disp");
		this.settingOfFixed4 = (Element) elements.get("settingOfFixed4");
		this.oneTime_Lock = (Element) elements.get("oneTime_Lock");
		this.generalBonusAmount9 = (Element) elements.get("generalBonusAmount9");
		this.generalBonusAmount7 = (Element) elements.get("generalBonusAmount7");
		this.generalBonusAmount8 = (Element) elements.get("generalBonusAmount8");
		this.save = (Element) elements.get("save");
		this.calculationBasePeriod_disp = (Element) elements.get("calculationBasePeriod_disp");
		this.generalBonusAmount1 = (Element) elements.get("generalBonusAmount1");
		this.generalBonusAmount2 = (Element) elements.get("generalBonusAmount2");
		this.paymentAmountEtc = (Element) elements.get("paymentAmountEtc");
		this.generalBonusAmount5 = (Element) elements.get("generalBonusAmount5");
		this.generalBonusAmount6 = (Element) elements.get("generalBonusAmount6");
		this.generalBonusAmount3 = (Element) elements.get("generalBonusAmount3");
		this.generalBonusAmount4 = (Element) elements.get("generalBonusAmount4");
		this.bonusEmployeeInf = (Element) elements.get("bonusEmployeeInf");
		this.undefinPayment = (Element) elements.get("undefinPayment");
		this.insertEmployee2 = (Element) elements.get("insertEmployee2");
		this.insertEmployee1 = (Element) elements.get("insertEmployee1");
		this.insertEmployee3 = (Element) elements.get("insertEmployee3");
		this.dateSettingYesButton = (Element) elements.get("dateSettingYesButton");
		this.fee2_disp = (Element) elements.get("fee2_disp");
		this.totalPaymentNonTax = (Element) elements.get("totalPaymentNonTax");
		this.bottomMenu = (Element) elements.get("bottomMenu");
		this.deductionValue_disp = (Element) elements.get("deductionValue_disp");
		this.fourtime_slip = (Element) elements.get("fourtime_slip");
		this.allowanceName2 = (Element) elements.get("allowanceName2");
		this.allowanceName6 = (Element) elements.get("allowanceName6");
		this.allowanceName5 = (Element) elements.get("allowanceName5");
		this.allowanceName4 = (Element) elements.get("allowanceName4");
		this.unemploymentInsurance = (Element) elements.get("unemploymentInsurance");
		this.allowanceName3 = (Element) elements.get("allowanceName3");
		this.allowanceName9 = (Element) elements.get("allowanceName9");
		this.allowanceName8 = (Element) elements.get("allowanceName8");
		this.allowanceName7 = (Element) elements.get("allowanceName7");
		this.allowanceName_dipName = (Element) elements.get("allowanceName_dipName");
		this.insertExcessiveTitle = (Element) elements.get("insertExcessiveTitle");
		this.healthInsrance_disp = (Element) elements.get("healthInsrance_disp");
		this.threeTime_Lock = (Element) elements.get("threeTime_Lock");
		this.popUp = (Element) elements.get("popUp");
		this.editOption = (Element) elements.get("editOption");
		this.recaculate = (Element) elements.get("recaculate");
		this.unemployeeBenefit10 = (Element) elements.get("unemployeeBenefit10");
		this.editMenu = (Element) elements.get("editMenu");
		this.totalTableLegalRecordSalaryIncome = (Element) elements.get("totalTableLegalRecordSalaryIncome");
		this.unemployeeBenefit11 = (Element) elements.get("unemployeeBenefit11");
		this.deduction = (Element) elements.get("deduction");
		this.fee_disp = (Element) elements.get("fee_disp");
		this.deductionName3 = (Element) elements.get("deductionName3");
		this.deductionName2 = (Element) elements.get("deductionName2");
		this.deductionName5 = (Element) elements.get("deductionName5");
		this.definition = (Element) elements.get("definition");
		this.deductionName4 = (Element) elements.get("deductionName4");
		this.payment2 = (Element) elements.get("payment2");
		this.deductionName7 = (Element) elements.get("deductionName7");
		this.deductionName6 = (Element) elements.get("deductionName6");
		this.excute = (Element) elements.get("excute");
		this.synchronization = (Element) elements.get("synchronization");
		this.totalAmountOfFees = (Element) elements.get("totalAmountOfFees");
		this.cancelPayment = (Element) elements.get("cancelPayment");
		this.bonusFormsButton = (Element) elements.get("bonusFormsButton");
		this.deductionData_dispName = (Element) elements.get("deductionData_dispName");
	}
}
