/**
 * 
 */
package com.asaas.test.util;

import java.util.HashMap;

/**
 * @author
 * 
 */
public class ClientSettingPage implements Page {
    // Declare variable
	public Element overFourtyHourWorkPremiumRate;
	public Element socialSecurityNewPersonPaymentPr;
	public Element dprc_BS_FiveYear;
	public Element dprc_EditMenu_Add_PopUp_Cancel;
	public Element AssetsSubjectOk;
	public Element insuredPersonPaymentProportion;
	public Element companyDisplayName;
	public Element informationSubmitted_TaxCode;
	public Element pensionFundApplying_old_insuredPersonPaymentProportion;
	public Element dailyAndHourEmployeeSetting;
	public Element companyAddressStreet_name;
	public Element dprc_popUp_cancel;
	public Element absenceAndNowork;
	public Element dprc_popUp_message2;
	public Element pensionFundsAmount_year;
	public Element dprc_EditMenu_Add_PopUp_AdrsCity;
	public Element yearTargetPayrollMonthBonus;
	public Element dprc_BS_BusinessPeriod_EndEra;
	public Element companyName;
	public Element companyAddressTwonKana1;
	public Element memorandumValueType_quantity;
	public Element companyAddressTwonKana2;
	public Element otherCompanyType_name;
	public Element fullWidthWornForm;
	public Element healthInsuranceType1;
	public Element clientFileClose;
	public Element insuranceRate;
	public Element healthInsuranceType2;
	public Element insuredPersonPaymentProportion_other_dis;
	public Element careInsranceNewAmountMonth;
	public Element paymentDateMonth;
	public Element healthInsurance_paymentMonth_new;
	public Element statutoryHolidayLateNight;
	public Element installationSiteSet;
	public Element healthInsurance_paymentYear_new;
	public Element healthInsNewAmountDay;
	public Element companyKana_name;
	public Element careOldPersonPaymentPr;
	public Element dprc_EditMenu_Add_PopUp_ZipCode_Search;
	public Element yes;
	public Element monthTargetPayrollMonthBonus2;
	public Element usageFlagOne;
	public Element beforOrAfterCorporateStatus_name;
	public Element dprc_BS_BusinessPeriod_StartMonth;
	public Element individualAddressStreet_name;
	public Element paymentDateMonth_dis;
	public Element healthInsNewAmountMonth;
	public Element dprc_BS_BusinessPeriod_title;
	public Element dprc_BS_AssetCodeAuto_NotDo;
	public Element clientEcsButton;
	public Element monthTargetPayrollMonthBonus;
	public Element companyType_name;
	public Element dprc_BS_CarryingAmountInput_BookAmount;
	public Element dprc_EditMenu_Edit;
	public Element companyAddressCity_name;
	public Element careInsranceStartDate_new;
	public Element individualAddressProvinceKana1;
	public Element close;
	public Element dataOfSalaryPayment;
	public Element companyAddressProvince_name;
	public Element payrollCaculationBasicInf;
	public Element laborInsuranceOwnership;
	public Element healthInsuranceProportion_other_dis;
	public Element currentYear;
	public Element personObligedCollectNumber;
	public Element hourlyEmployeeOvertime;
	public Element paymentDateYear2;
	public Element holidaynormal;
	public Element companyAddressCityKana2;
	public Element fourthTimeTit_InDateSet;
	public Element companyAddressCityKana1;
	public Element dprc_BS_BusinessPeriod_StartYear;
	public Element dateSettingNoButton;
	public Element dprc_Right_Edit;
	public Element informationSubmitted_TaxOffice;
	public Element socialSecurityStartApplying_new;
	public Element statutoryHolidayNormal;
	public Element availableNumber_Msg;
	public Element insuredPersonPaymentPr_dis;
	public Element dprc_BS_BusinessPeriod_StartDate_Disp;
	public Element individualNextMonth;
	public Element dprc_BS_CompanyDispName_Disp;
	public Element familyNameKana;
	public Element dprc_EditMenu_Add_PopUp_LocalGC;
	public Element companyAddressBuildingKana2;
	public Element assets_systemMethod;
	public Element paymentDay_Feb_dis;
	public Element companyAddressBuildingKana1;
	public Element name;
	public Element editAssetAccountSetting_Cancel;
	public Element annualAdjustmnetBasicSetting;
	public Element overSixtyHourWorkPremiumRate;
	public Element careInsranceOldAmountDay;
	public Element edit;
	public Element theRemainingPercentage;
	public Element individualName_dis;
	public Element dprc_BS_BusinessPeriod_startDate;
	public Element clientTaxNumber;
	public Element clientEditButton2;
	public Element bankInformation;
	public Element dprc_EditMenu_Add_PopUp_InstSiteName;
	public Element specialPaymentPeriodFlag;
	public Element asset_PopUp_OK;
	public Element governmentCode;
	public Element pensionFund_paymentMonth_new;
	public Element dprcCountOfMonthType_dis;
	public Element individualBasicInformation;
	public Element assetAccount_Tab_Investment;
	public Element socialSecurityNewPersonPaymentPr_dis;
	public Element perfectureType;
	public Element companyAddressStreetKana1;
	public Element companyAddressStreetKana2;
	public Element dprc_BS_BusinessPeriod_StartDay;
	public Element diplayScreenTittle;
	public Element healthInsStartDate_old;
	public Element branchName;
	public Element clientFileSave;
	public Element assetAccount_Tab_Other;
	public Element basicSettingPage;
	public Element careInsranceStartDate_old;
	public Element careOldPersonPaymentPr_dis;
	public Element familyName_name;
	public Element dprc_BS_OneTime;
	public Element capitalExpenseType_ATEOAC;
	public Element otherPeriodFlag;
	public Element dprcCountOfMonthType_calender;
	public Element dailyEmployeeNoWork;
	public Element assetAccount_Tab_Deferred;
	public Element accumulatedDprcAccount;
	public Element fullName_dis;
	public Element assetAccount_Tab_Intagible_List;
	public Element otherCompanyTypekana_name;
	public Element dprc_BS_LimitParRound;
	public Element careInsuranceRate_new;
	public Element dprc_BS_AssetCodeAuto_Disp;
	public Element assetAccount_Tab_Tanglible;
	public Element individualTelephoneNumber1;
	public Element dprc_EditMenu_Add_PopUp_AdrsPre;
	public Element individualTelephoneNumber3;
	public Element individualTelephoneNumber2;
	public Element fullNameKana_dis;
	public Element Ok;
	public Element CalcRoundingMethodOfHealthInsurance_dis;
	public Element assetAccountSet;
	public Element pensionFund_paymentMonth;
	public Element dprc_popUp_list;
	public Element dprc_BS_ByMonthMethod;
	public Element save;
	public Element twiceYear_disp;
	public Element healthInsStartDate_new;
	public Element pensionFundRate_new;
	public Element clientEditButton;
	public Element dprc_BS_AssetCodeAuto_WholeAssets;
	public Element depreciationMethod;
	public Element individualPaymentDay;
	public Element overFourtyHourWorkPremiumRate2;
	public Element depreciationLimit_dis;
	public Element thirdTimeYear_disp;
	public Element dprc_BS_BusinessPeriod_change;
	public Element closingDay;
	public Element careInsurance_paymentMonth_new;
	public Element hourlyEmployeeNoWork;
	public Element pensionFundsAmount_month;
	public Element dprc_BS_CapitalExpense_Disp;
	public Element dprcManufacturingExpenseAccount;
	public Element editDepSetting_UsageType;
	public Element payment_Jan_Day;
	public Element socialSecurityOldPersonPaymentPr2_dis;
	public Element individualZipCode1;
	public Element careInsStartApplying;
	public Element healthInsuranceProportion_other;
	public Element individualZipCode2;
	public Element pensionFund_paymentYear;
	public Element dprc_BS_AccountByMon_Disp;
	public Element yearPayrollMonthBonusDisp;
	public Element dprc_SM_Space;
	public Element assetsSubjectCodeTwo;
	public Element insuredPersonPaymentProportion_input;
	public Element popUp;
	public Element individualCode;
	public Element totalTableLegalRecordSalaryIncome;
	public Element clientForms_SubmissionForms;
	public Element twiceTit_InDateSet;
	public Element manufacturingExpenseAccount;
	public Element CalcRoundingMethodOfHealthInsurance;
	public Element typesOfLocalTax;
	public Element careNewPersonDependency_dis;
	public Element dprc_EditMenu;
	public Element dprcFiveYearCalculationRoundingType_dis;
	public Element firstNameKana_name;
	public Element dprc_BS_FiveYear_Disp;
	public Element CalcRoundingMethodOfLaborInsurance_dis;
	public Element editDepSetting_ExpenseType;
	public Element companyAddressBuilding_name;
	public Element companyCode;
	public Element careNewPersonDependency;
	public Element paymentDateDay2;
	public Element paymentDateDay3;
	public Element dprcExecutingRate_dis;
	public Element paymentDateDay4;
	public Element healthInsOldAmountDay;
	public Element editDepSetting_Title;
	public Element noWork2;
	public Element dprc_BS_AccountByMon;
	public Element otherCompanyTypekana;
	public Element yearTargetPayrollMonthBonus2;
	public Element healthInsStartApplying_old;
	public Element yearTargetPayrollMonthBonus3;
	public Element pensionFundApplying_old;
	public Element pensionFundApplying_new_insuredPersonPaymentProportion;
	public Element dprc_BS_Code_Disp;
	public Element otherCompanyType;
	public Element absenceAndNowork_dis;
	public Element dprc_EditMenu_Add_PopUp_AdrsROP;
	public Element dprc_BS_AssetCodeAuto_Account;
	public Element insuredPersonPaymentProportion_pensionFund;
	public Element editDepSetting_Cancel;
	public Element depreciationLimit;
	public Element paymentDateDay;
	public Element dprc_BS_DeferredAsset_Disp;
	public Element editDepSetting_InstallationSite_List;
	public Element dprc_BS_BusinessPeriod_EndDay;
	public Element dprc_BS_BusinessPeriod_EndDate_Disp;
	public Element dprc_EditMenu_Add_PopUp_AdrsSN;
	public Element socialSecurityAmountModule;
	public Element assets_systemCode;
	public Element memorandumValueType_oneEn;
	public Element socialInsuranceRateSetting;
	public Element informationSubmitted;
	public Element weekdaylateNight;
	public Element dprc_BS_ByMonthMethod_Disp;
	public Element editAssetAccountSetting_Title;
	public Element individualAddressBuilding_name;
	public Element companyAddressTwon_name;
	public Element dprc_BS_DprcContentSummaryType;
	public Element dprc_EditMenu_Add_PopUp_AdrsRO;
	public Element individualAddressProvince_name;
	public Element monthlyEmployeeNoWork;
	public Element dprc_BS_CarryingAmountInput_Disp;
	public Element individualPaymentYear;
	public Element dprc_BS_CarryingAmountInput_Accumulate;
	public Element individualAddressTwon_name;
	public Element individualAddressProvinceKana;
	public Element paymentDay;
	public Element dprc_BS_CompanyKanaName_Disp;
	public Element specialEquipmentCalc;
	public Element careInsurance_paymentYear_new;
	public Element errorHint;
	public Element dprcCountOfMonthType_corprateTax;
	public Element excessiveDeficitAmountAdjustmentType;
	public Element overSixtyHourWorkPremiumRate2;
	public Element dprc_BS_War_Ok;
	public Element dprcManufacturingExpenseAccount_Button;
	public Element oneTimeTit_InDateSet;
	public Element firstNameKana;
	public Element menuBar;
	public Element editUsageFlag;
	public Element healthInsuranceRate_new;
	public Element dprcExecutingRate;
	public Element healthInsurance_paymentYear;
	public Element telephoneNumber1;
	public Element telephoneNumber2;
	public Element telephoneNumber3;
	public Element MethodOfSalaryPayment;
	public Element typesOfLocalTax_dis;
	public Element dprc_BS_BusinessPeriod_EndMonth;
	public Element operatingExpenseAccount;
	public Element dprc_BS_Code_Disp_Ind;
	public Element individualAddressCityKana1;
	public Element pensionFundsAmount_input_dis;
	public Element individualAddressCityKana2;
	public Element dprc_EditMenu_Delete;
	public Element companyBasicInformation;
	public Element oneTimeYear_disp;
	public Element editDepSetting_InstallationSite;
	public Element pensionFoundAmountModule;
	public Element afterButton;
	public Element healthInsuranceType;
	public Element dprc_popUp_OK2;
	public Element zipCode1;
	public Element telephoneNumber_disp;
	public Element dprcBaseSet;
	public Element dprc_FileMenu_Save;
	public Element zipCode2;
	public Element individualDisplayCode;
	public Element dailyEmployeeOvertime;
	public Element monthlyEmployeeAbsence;
	public Element clientFileButton;
	public Element socialSecurityNewPersonPaymentPr2;
	public Element pensionFoundAmount;
	public Element dprc_BS_CalcRound_Disp;
	public Element healthInsuranceProportion_input;
	public Element dprc_FileMenu_Logout;
	public Element theRemainingPercentage_dis;
	public Element companyName_name;
	public Element familyNameKana_name;
	public Element SelectTaxOffice_Cancel;
	public Element companyKana;
	public Element careInsranceNewAmountDay;
	public Element monthlyTable;
	public Element SelectTaxOffice_Select;
	public Element addressNameKana_dis;
	public Element healthInsuranceProportion;
	public Element dprc_FileMenu_Close;
	public Element firstLine;
	public Element editDepSetting_Save;
	public Element overtimeAndNoWork;
	public Element dprc_BS_CapitalExpense_Apply;
	public Element individualNameKana_dis;
	public Element careInsranceOldAmountMonth;
	public Element dprc_BS_DeferredAsset;
	public Element individualAddressStreetKana1;
	public Element dprc_EditMenu_Add_PopUp_telephone3;
	public Element individualAddressStreetKana2;
	public Element careNewPersonPaymentPr;
	public Element dprc_EditMenu_Add_PopUp_telephone1;
	public Element lengthThanSixtyWornForm;
	public Element dprc_EditMenu_Add_PopUp_telephone2;
	public Element clientTaxNumber_dis;
	public Element dprc_FileMenu_Cancel;
	public Element asset_PopUp_method;
	public Element individualAddress_dis;
	public Element bankName_dis;
	public Element dprc_popUp_message;
	public Element socialSecuritySwitch;
	public Element depreciationMethod_dis;
	public Element dprc_EditMenu_Add_PopUp_AdrsTown;
	public Element dprc_SM_F5;
	public Element dprc_SM_F4;
	public Element socialSecurityOldPersonPaymentPr;
	public Element dprc_BS_CapitalExpense_NotApply;
	public Element individualAddressBuildingKana1;
	public Element file;
	public Element individualAddressBuildingKana2;
	public Element dprc_SM_ESC;
	public Element thirdTimeTit_InDateSet;
	public Element holidaylateNight;
	public Element overtimeWork_dis;
	public Element manageOvertimeNoWorkFlag;
	public Element careInsStartApplying_old;
	public Element insuredPersonPaymentPr2_dis;
	public Element pensionFundsAmount_input;
	public Element insuredPersonPaymentProportion_other;
	public Element healthInsurance_paymentMonth;
	public Element bankName;
	public Element individualAddressCity_name;
	public Element beforeButton;
	public Element companyDisplayNameKana;
	public Element assetsSubjectCodeOne;
	public Element dprc_BS_BusinessPeriod_Months;
	public Element healthInsStartApplying;
	public Element pageTitle;
	public Element saving;
	public Element socialInsuranceJoin;
	public Element memorandumValueType_dis;
	public Element careInsurance_paymentYear;
	public Element installationAddButton;
	public Element overtimeWork;
	public Element dprc_EditMenu_Add_PopUp_Save;
	public Element familyName;
	public Element bonusPaymentDateSetting_page;
	public Element dprc_BS_CalcRound;
	public Element CalcRoundingMethodOfLaborInsurance;
	public Element dailyAndHourEmployeeSetting_dis;
	public Element dprc_FileMenu;
	public Element dprc_EditMenu_Add_PopUp_InstSiteCode;
	public Element dprc_EditMenu_Add_PopUp_NextInput;
	public Element file_createNewPeriod;
	public Element dprc_EditMenu_Add_PopUp_ZipCode2;
	public Element dprc_popUp_cancel2;
	public Element dprc_EditMenu_Add_PopUp_ZipCode1;
	public Element paymentDateMonth4;
	public Element dprc_popUp_cancel3;
	public Element paymentDateMonth3;
	public Element governmentCode_indiv;
	public Element paymentDateMonth2;
	public Element payrollPeriod;
	public Element insuredPersonPaymentPr2;
	public Element socialSecurityNewPersonPaymentPr2dis;
	public Element pensionFundApplying_new;
	public Element healthInsOldAmountMonth;
	public Element holidayWornForm;
	public Element assetAccount_Tab_Intagible;
	public Element editDepSetting_NextInput;
	public Element individualAddressTwonKana1;
	public Element paymentDay_Feb;
	public Element individualAddressTwonKana2;
	public Element editDepSetting_DepName;
	public Element careNewPersonPaymentPr_dis;
	public Element tradeName;
	public Element dprc_EditMenu_Add_PopUp_AdrsRO_List;
	public Element dprc_EditMenu_Add;
	public Element socialSecurityOldPersonPaymentPr2;
	public Element monthlyEmployeeOvertime;
	public Element socialSecurityStartApplying_old;
	public Element excessiveDeficitAmountAdjustmentMonth;
	public Element dprc_BS_BusinessPeriod_StartEra;
	public Element individualAddressKana_dis;
	public Element dateSettingYesButton;
	public Element dprc_popUp_OK;
	public Element bottomMenu;
	public Element nextMonth;
	public Element careInsurance_paymentMonth;
	public Element weekdayNormal;
	public Element perfectureType_dis;
	public Element socialSecurityAmount;
	public Element assetListCount;
	public Element addressName_dis;
	public Element firstName_name;
	public Element absence1;
	public Element usedBankTransferRequest;
	public Element individualZipCode_dis;
	public Element dprc_BS_FiveYearCalcRound;
	public Element sequenceRecord_Msg;
	public Element pensionFund_paymentYear_new;
	public Element SelectTaxOffice_FirstLine;
	public Element dprc_BS_OneTime_Disp;
	public Element dprc_BS_BusinessPeriod_endDate;
	public Element dpmSet;
	public Element firstName;
	public Element dprc_SM_F12;
	public Element insuredPersonPaymentPr;
	public Element SelectTaxOfficeButton;
	public Element check;
	public Element manageHoliday;
	public Element definition;
	public Element thisMonth;
	public Element tradeName2;
	public Element dprc_EditMenu_Add_PopUp_AdrsBuilding;
	public Element paymentMonth_Feb;
	public Element editDepSetting_DepCode;
	public Element clientFormsButton;
	public Element zipCode_disp;
	public Element generalExpenseAccount;
	public Element socialSecurityOldPersonPaymentPr_dis;
	public Element dprc_BS_LimitParRound_Disp;
	public Element paymentDateSetting;
	public Element fourthTimeYear_disp;
	public Element dprc_InstList;
	public Element constructionPeriodFlag;
	public Element companyAddressProvinceKana;
	public Element companyType;
	public Element fullName;
	public Element assetsSubjectCode;
	public Element dprc_BS_BusinessPeriod_EndYear;

    /*
     * @see com.asaas.test.util.Page#init(java.util.HashMap)
     */
    public void init(HashMap<String, Object> elements) {
        // Initialize variable
		this.overFourtyHourWorkPremiumRate = (Element) elements.get("overFourtyHourWorkPremiumRate");
		this.socialSecurityNewPersonPaymentPr = (Element) elements.get("socialSecurityNewPersonPaymentPr");
		this.dprc_BS_FiveYear = (Element) elements.get("dprc_BS_FiveYear");
		this.dprc_EditMenu_Add_PopUp_Cancel = (Element) elements.get("dprc_EditMenu_Add_PopUp_Cancel");
		this.AssetsSubjectOk = (Element) elements.get("AssetsSubjectOk");
		this.insuredPersonPaymentProportion = (Element) elements.get("insuredPersonPaymentProportion");
		this.companyDisplayName = (Element) elements.get("companyDisplayName");
		this.informationSubmitted_TaxCode = (Element) elements.get("informationSubmitted_TaxCode");
		this.pensionFundApplying_old_insuredPersonPaymentProportion = (Element) elements.get("pensionFundApplying_old_insuredPersonPaymentProportion");
		this.dailyAndHourEmployeeSetting = (Element) elements.get("dailyAndHourEmployeeSetting");
		this.companyAddressStreet_name = (Element) elements.get("companyAddressStreet_name");
		this.dprc_popUp_cancel = (Element) elements.get("dprc_popUp_cancel");
		this.absenceAndNowork = (Element) elements.get("absenceAndNowork");
		this.dprc_popUp_message2 = (Element) elements.get("dprc_popUp_message2");
		this.pensionFundsAmount_year = (Element) elements.get("pensionFundsAmount_year");
		this.dprc_EditMenu_Add_PopUp_AdrsCity = (Element) elements.get("dprc_EditMenu_Add_PopUp_AdrsCity");
		this.yearTargetPayrollMonthBonus = (Element) elements.get("yearTargetPayrollMonthBonus");
		this.dprc_BS_BusinessPeriod_EndEra = (Element) elements.get("dprc_BS_BusinessPeriod_EndEra");
		this.companyName = (Element) elements.get("companyName");
		this.companyAddressTwonKana1 = (Element) elements.get("companyAddressTwonKana1");
		this.memorandumValueType_quantity = (Element) elements.get("memorandumValueType_quantity");
		this.companyAddressTwonKana2 = (Element) elements.get("companyAddressTwonKana2");
		this.otherCompanyType_name = (Element) elements.get("otherCompanyType_name");
		this.fullWidthWornForm = (Element) elements.get("fullWidthWornForm");
		this.healthInsuranceType1 = (Element) elements.get("healthInsuranceType1");
		this.clientFileClose = (Element) elements.get("clientFileClose");
		this.insuranceRate = (Element) elements.get("insuranceRate");
		this.healthInsuranceType2 = (Element) elements.get("healthInsuranceType2");
		this.insuredPersonPaymentProportion_other_dis = (Element) elements.get("insuredPersonPaymentProportion_other_dis");
		this.careInsranceNewAmountMonth = (Element) elements.get("careInsranceNewAmountMonth");
		this.paymentDateMonth = (Element) elements.get("paymentDateMonth");
		this.healthInsurance_paymentMonth_new = (Element) elements.get("healthInsurance_paymentMonth_new");
		this.statutoryHolidayLateNight = (Element) elements.get("statutoryHolidayLateNight");
		this.installationSiteSet = (Element) elements.get("installationSiteSet");
		this.healthInsurance_paymentYear_new = (Element) elements.get("healthInsurance_paymentYear_new");
		this.healthInsNewAmountDay = (Element) elements.get("healthInsNewAmountDay");
		this.companyKana_name = (Element) elements.get("companyKana_name");
		this.careOldPersonPaymentPr = (Element) elements.get("careOldPersonPaymentPr");
		this.dprc_EditMenu_Add_PopUp_ZipCode_Search = (Element) elements.get("dprc_EditMenu_Add_PopUp_ZipCode_Search");
		this.yes = (Element) elements.get("yes");
		this.monthTargetPayrollMonthBonus2 = (Element) elements.get("monthTargetPayrollMonthBonus2");
		this.usageFlagOne = (Element) elements.get("usageFlagOne");
		this.beforOrAfterCorporateStatus_name = (Element) elements.get("beforOrAfterCorporateStatus_name");
		this.dprc_BS_BusinessPeriod_StartMonth = (Element) elements.get("dprc_BS_BusinessPeriod_StartMonth");
		this.individualAddressStreet_name = (Element) elements.get("individualAddressStreet_name");
		this.paymentDateMonth_dis = (Element) elements.get("paymentDateMonth_dis");
		this.healthInsNewAmountMonth = (Element) elements.get("healthInsNewAmountMonth");
		this.dprc_BS_BusinessPeriod_title = (Element) elements.get("dprc_BS_BusinessPeriod_title");
		this.dprc_BS_AssetCodeAuto_NotDo = (Element) elements.get("dprc_BS_AssetCodeAuto_NotDo");
		this.clientEcsButton = (Element) elements.get("clientEcsButton");
		this.monthTargetPayrollMonthBonus = (Element) elements.get("monthTargetPayrollMonthBonus");
		this.companyType_name = (Element) elements.get("companyType_name");
		this.dprc_BS_CarryingAmountInput_BookAmount = (Element) elements.get("dprc_BS_CarryingAmountInput_BookAmount");
		this.dprc_EditMenu_Edit = (Element) elements.get("dprc_EditMenu_Edit");
		this.companyAddressCity_name = (Element) elements.get("companyAddressCity_name");
		this.careInsranceStartDate_new = (Element) elements.get("careInsranceStartDate_new");
		this.individualAddressProvinceKana1 = (Element) elements.get("individualAddressProvinceKana1");
		this.close = (Element) elements.get("close");
		this.dataOfSalaryPayment = (Element) elements.get("dataOfSalaryPayment");
		this.companyAddressProvince_name = (Element) elements.get("companyAddressProvince_name");
		this.payrollCaculationBasicInf = (Element) elements.get("payrollCaculationBasicInf");
		this.laborInsuranceOwnership = (Element) elements.get("laborInsuranceOwnership");
		this.healthInsuranceProportion_other_dis = (Element) elements.get("healthInsuranceProportion_other_dis");
		this.currentYear = (Element) elements.get("currentYear");
		this.personObligedCollectNumber = (Element) elements.get("personObligedCollectNumber");
		this.hourlyEmployeeOvertime = (Element) elements.get("hourlyEmployeeOvertime");
		this.paymentDateYear2 = (Element) elements.get("paymentDateYear2");
		this.holidaynormal = (Element) elements.get("holidaynormal");
		this.companyAddressCityKana2 = (Element) elements.get("companyAddressCityKana2");
		this.fourthTimeTit_InDateSet = (Element) elements.get("fourthTimeTit_InDateSet");
		this.companyAddressCityKana1 = (Element) elements.get("companyAddressCityKana1");
		this.dprc_BS_BusinessPeriod_StartYear = (Element) elements.get("dprc_BS_BusinessPeriod_StartYear");
		this.dateSettingNoButton = (Element) elements.get("dateSettingNoButton");
		this.dprc_Right_Edit = (Element) elements.get("dprc_Right_Edit");
		this.informationSubmitted_TaxOffice = (Element) elements.get("informationSubmitted_TaxOffice");
		this.socialSecurityStartApplying_new = (Element) elements.get("socialSecurityStartApplying_new");
		this.statutoryHolidayNormal = (Element) elements.get("statutoryHolidayNormal");
		this.availableNumber_Msg = (Element) elements.get("availableNumber_Msg");
		this.insuredPersonPaymentPr_dis = (Element) elements.get("insuredPersonPaymentPr_dis");
		this.dprc_BS_BusinessPeriod_StartDate_Disp = (Element) elements.get("dprc_BS_BusinessPeriod_StartDate_Disp");
		this.individualNextMonth = (Element) elements.get("individualNextMonth");
		this.dprc_BS_CompanyDispName_Disp = (Element) elements.get("dprc_BS_CompanyDispName_Disp");
		this.familyNameKana = (Element) elements.get("familyNameKana");
		this.dprc_EditMenu_Add_PopUp_LocalGC = (Element) elements.get("dprc_EditMenu_Add_PopUp_LocalGC");
		this.companyAddressBuildingKana2 = (Element) elements.get("companyAddressBuildingKana2");
		this.assets_systemMethod = (Element) elements.get("assets_systemMethod");
		this.paymentDay_Feb_dis = (Element) elements.get("paymentDay_Feb_dis");
		this.companyAddressBuildingKana1 = (Element) elements.get("companyAddressBuildingKana1");
		this.name = (Element) elements.get("name");
		this.editAssetAccountSetting_Cancel = (Element) elements.get("editAssetAccountSetting_Cancel");
		this.annualAdjustmnetBasicSetting = (Element) elements.get("annualAdjustmnetBasicSetting");
		this.overSixtyHourWorkPremiumRate = (Element) elements.get("overSixtyHourWorkPremiumRate");
		this.careInsranceOldAmountDay = (Element) elements.get("careInsranceOldAmountDay");
		this.edit = (Element) elements.get("edit");
		this.theRemainingPercentage = (Element) elements.get("theRemainingPercentage");
		this.individualName_dis = (Element) elements.get("individualName_dis");
		this.dprc_BS_BusinessPeriod_startDate = (Element) elements.get("dprc_BS_BusinessPeriod_startDate");
		this.clientTaxNumber = (Element) elements.get("clientTaxNumber");
		this.clientEditButton2 = (Element) elements.get("clientEditButton2");
		this.bankInformation = (Element) elements.get("bankInformation");
		this.dprc_EditMenu_Add_PopUp_InstSiteName = (Element) elements.get("dprc_EditMenu_Add_PopUp_InstSiteName");
		this.specialPaymentPeriodFlag = (Element) elements.get("specialPaymentPeriodFlag");
		this.asset_PopUp_OK = (Element) elements.get("asset_PopUp_OK");
		this.governmentCode = (Element) elements.get("governmentCode");
		this.pensionFund_paymentMonth_new = (Element) elements.get("pensionFund_paymentMonth_new");
		this.dprcCountOfMonthType_dis = (Element) elements.get("dprcCountOfMonthType_dis");
		this.individualBasicInformation = (Element) elements.get("individualBasicInformation");
		this.assetAccount_Tab_Investment = (Element) elements.get("assetAccount_Tab_Investment");
		this.socialSecurityNewPersonPaymentPr_dis = (Element) elements.get("socialSecurityNewPersonPaymentPr_dis");
		this.perfectureType = (Element) elements.get("perfectureType");
		this.companyAddressStreetKana1 = (Element) elements.get("companyAddressStreetKana1");
		this.companyAddressStreetKana2 = (Element) elements.get("companyAddressStreetKana2");
		this.dprc_BS_BusinessPeriod_StartDay = (Element) elements.get("dprc_BS_BusinessPeriod_StartDay");
		this.diplayScreenTittle = (Element) elements.get("diplayScreenTittle");
		this.healthInsStartDate_old = (Element) elements.get("healthInsStartDate_old");
		this.branchName = (Element) elements.get("branchName");
		this.clientFileSave = (Element) elements.get("clientFileSave");
		this.assetAccount_Tab_Other = (Element) elements.get("assetAccount_Tab_Other");
		this.basicSettingPage = (Element) elements.get("basicSettingPage");
		this.careInsranceStartDate_old = (Element) elements.get("careInsranceStartDate_old");
		this.careOldPersonPaymentPr_dis = (Element) elements.get("careOldPersonPaymentPr_dis");
		this.familyName_name = (Element) elements.get("familyName_name");
		this.dprc_BS_OneTime = (Element) elements.get("dprc_BS_OneTime");
		this.capitalExpenseType_ATEOAC = (Element) elements.get("capitalExpenseType_ATEOAC");
		this.otherPeriodFlag = (Element) elements.get("otherPeriodFlag");
		this.dprcCountOfMonthType_calender = (Element) elements.get("dprcCountOfMonthType_calender");
		this.dailyEmployeeNoWork = (Element) elements.get("dailyEmployeeNoWork");
		this.assetAccount_Tab_Deferred = (Element) elements.get("assetAccount_Tab_Deferred");
		this.accumulatedDprcAccount = (Element) elements.get("accumulatedDprcAccount");
		this.fullName_dis = (Element) elements.get("fullName_dis");
		this.assetAccount_Tab_Intagible_List = (Element) elements.get("assetAccount_Tab_Intagible_List");
		this.otherCompanyTypekana_name = (Element) elements.get("otherCompanyTypekana_name");
		this.dprc_BS_LimitParRound = (Element) elements.get("dprc_BS_LimitParRound");
		this.careInsuranceRate_new = (Element) elements.get("careInsuranceRate_new");
		this.dprc_BS_AssetCodeAuto_Disp = (Element) elements.get("dprc_BS_AssetCodeAuto_Disp");
		this.assetAccount_Tab_Tanglible = (Element) elements.get("assetAccount_Tab_Tanglible");
		this.individualTelephoneNumber1 = (Element) elements.get("individualTelephoneNumber1");
		this.dprc_EditMenu_Add_PopUp_AdrsPre = (Element) elements.get("dprc_EditMenu_Add_PopUp_AdrsPre");
		this.individualTelephoneNumber3 = (Element) elements.get("individualTelephoneNumber3");
		this.individualTelephoneNumber2 = (Element) elements.get("individualTelephoneNumber2");
		this.fullNameKana_dis = (Element) elements.get("fullNameKana_dis");
		this.Ok = (Element) elements.get("Ok");
		this.CalcRoundingMethodOfHealthInsurance_dis = (Element) elements.get("CalcRoundingMethodOfHealthInsurance_dis");
		this.assetAccountSet = (Element) elements.get("assetAccountSet");
		this.pensionFund_paymentMonth = (Element) elements.get("pensionFund_paymentMonth");
		this.dprc_popUp_list = (Element) elements.get("dprc_popUp_list");
		this.dprc_BS_ByMonthMethod = (Element) elements.get("dprc_BS_ByMonthMethod");
		this.save = (Element) elements.get("save");
		this.twiceYear_disp = (Element) elements.get("twiceYear_disp");
		this.healthInsStartDate_new = (Element) elements.get("healthInsStartDate_new");
		this.pensionFundRate_new = (Element) elements.get("pensionFundRate_new");
		this.clientEditButton = (Element) elements.get("clientEditButton");
		this.dprc_BS_AssetCodeAuto_WholeAssets = (Element) elements.get("dprc_BS_AssetCodeAuto_WholeAssets");
		this.depreciationMethod = (Element) elements.get("depreciationMethod");
		this.individualPaymentDay = (Element) elements.get("individualPaymentDay");
		this.overFourtyHourWorkPremiumRate2 = (Element) elements.get("overFourtyHourWorkPremiumRate2");
		this.depreciationLimit_dis = (Element) elements.get("depreciationLimit_dis");
		this.thirdTimeYear_disp = (Element) elements.get("thirdTimeYear_disp");
		this.dprc_BS_BusinessPeriod_change = (Element) elements.get("dprc_BS_BusinessPeriod_change");
		this.closingDay = (Element) elements.get("closingDay");
		this.careInsurance_paymentMonth_new = (Element) elements.get("careInsurance_paymentMonth_new");
		this.hourlyEmployeeNoWork = (Element) elements.get("hourlyEmployeeNoWork");
		this.pensionFundsAmount_month = (Element) elements.get("pensionFundsAmount_month");
		this.dprc_BS_CapitalExpense_Disp = (Element) elements.get("dprc_BS_CapitalExpense_Disp");
		this.dprcManufacturingExpenseAccount = (Element) elements.get("dprcManufacturingExpenseAccount");
		this.editDepSetting_UsageType = (Element) elements.get("editDepSetting_UsageType");
		this.payment_Jan_Day = (Element) elements.get("payment_Jan_Day");
		this.socialSecurityOldPersonPaymentPr2_dis = (Element) elements.get("socialSecurityOldPersonPaymentPr2_dis");
		this.individualZipCode1 = (Element) elements.get("individualZipCode1");
		this.careInsStartApplying = (Element) elements.get("careInsStartApplying");
		this.healthInsuranceProportion_other = (Element) elements.get("healthInsuranceProportion_other");
		this.individualZipCode2 = (Element) elements.get("individualZipCode2");
		this.pensionFund_paymentYear = (Element) elements.get("pensionFund_paymentYear");
		this.dprc_BS_AccountByMon_Disp = (Element) elements.get("dprc_BS_AccountByMon_Disp");
		this.yearPayrollMonthBonusDisp = (Element) elements.get("yearPayrollMonthBonusDisp");
		this.dprc_SM_Space = (Element) elements.get("dprc_SM_Space");
		this.assetsSubjectCodeTwo = (Element) elements.get("assetsSubjectCodeTwo");
		this.insuredPersonPaymentProportion_input = (Element) elements.get("insuredPersonPaymentProportion_input");
		this.popUp = (Element) elements.get("popUp");
		this.individualCode = (Element) elements.get("individualCode");
		this.totalTableLegalRecordSalaryIncome = (Element) elements.get("totalTableLegalRecordSalaryIncome");
		this.clientForms_SubmissionForms = (Element) elements.get("clientForms_SubmissionForms");
		this.twiceTit_InDateSet = (Element) elements.get("twiceTit_InDateSet");
		this.manufacturingExpenseAccount = (Element) elements.get("manufacturingExpenseAccount");
		this.CalcRoundingMethodOfHealthInsurance = (Element) elements.get("CalcRoundingMethodOfHealthInsurance");
		this.typesOfLocalTax = (Element) elements.get("typesOfLocalTax");
		this.careNewPersonDependency_dis = (Element) elements.get("careNewPersonDependency_dis");
		this.dprc_EditMenu = (Element) elements.get("dprc_EditMenu");
		this.dprcFiveYearCalculationRoundingType_dis = (Element) elements.get("dprcFiveYearCalculationRoundingType_dis");
		this.firstNameKana_name = (Element) elements.get("firstNameKana_name");
		this.dprc_BS_FiveYear_Disp = (Element) elements.get("dprc_BS_FiveYear_Disp");
		this.CalcRoundingMethodOfLaborInsurance_dis = (Element) elements.get("CalcRoundingMethodOfLaborInsurance_dis");
		this.editDepSetting_ExpenseType = (Element) elements.get("editDepSetting_ExpenseType");
		this.companyAddressBuilding_name = (Element) elements.get("companyAddressBuilding_name");
		this.companyCode = (Element) elements.get("companyCode");
		this.careNewPersonDependency = (Element) elements.get("careNewPersonDependency");
		this.paymentDateDay2 = (Element) elements.get("paymentDateDay2");
		this.paymentDateDay3 = (Element) elements.get("paymentDateDay3");
		this.dprcExecutingRate_dis = (Element) elements.get("dprcExecutingRate_dis");
		this.paymentDateDay4 = (Element) elements.get("paymentDateDay4");
		this.healthInsOldAmountDay = (Element) elements.get("healthInsOldAmountDay");
		this.editDepSetting_Title = (Element) elements.get("editDepSetting_Title");
		this.noWork2 = (Element) elements.get("noWork2");
		this.dprc_BS_AccountByMon = (Element) elements.get("dprc_BS_AccountByMon");
		this.otherCompanyTypekana = (Element) elements.get("otherCompanyTypekana");
		this.yearTargetPayrollMonthBonus2 = (Element) elements.get("yearTargetPayrollMonthBonus2");
		this.healthInsStartApplying_old = (Element) elements.get("healthInsStartApplying_old");
		this.yearTargetPayrollMonthBonus3 = (Element) elements.get("yearTargetPayrollMonthBonus3");
		this.pensionFundApplying_old = (Element) elements.get("pensionFundApplying_old");
		this.pensionFundApplying_new_insuredPersonPaymentProportion = (Element) elements.get("pensionFundApplying_new_insuredPersonPaymentProportion");
		this.dprc_BS_Code_Disp = (Element) elements.get("dprc_BS_Code_Disp");
		this.otherCompanyType = (Element) elements.get("otherCompanyType");
		this.absenceAndNowork_dis = (Element) elements.get("absenceAndNowork_dis");
		this.dprc_EditMenu_Add_PopUp_AdrsROP = (Element) elements.get("dprc_EditMenu_Add_PopUp_AdrsROP");
		this.dprc_BS_AssetCodeAuto_Account = (Element) elements.get("dprc_BS_AssetCodeAuto_Account");
		this.insuredPersonPaymentProportion_pensionFund = (Element) elements.get("insuredPersonPaymentProportion_pensionFund");
		this.editDepSetting_Cancel = (Element) elements.get("editDepSetting_Cancel");
		this.depreciationLimit = (Element) elements.get("depreciationLimit");
		this.paymentDateDay = (Element) elements.get("paymentDateDay");
		this.dprc_BS_DeferredAsset_Disp = (Element) elements.get("dprc_BS_DeferredAsset_Disp");
		this.editDepSetting_InstallationSite_List = (Element) elements.get("editDepSetting_InstallationSite_List");
		this.dprc_BS_BusinessPeriod_EndDay = (Element) elements.get("dprc_BS_BusinessPeriod_EndDay");
		this.dprc_BS_BusinessPeriod_EndDate_Disp = (Element) elements.get("dprc_BS_BusinessPeriod_EndDate_Disp");
		this.dprc_EditMenu_Add_PopUp_AdrsSN = (Element) elements.get("dprc_EditMenu_Add_PopUp_AdrsSN");
		this.socialSecurityAmountModule = (Element) elements.get("socialSecurityAmountModule");
		this.assets_systemCode = (Element) elements.get("assets_systemCode");
		this.memorandumValueType_oneEn = (Element) elements.get("memorandumValueType_oneEn");
		this.socialInsuranceRateSetting = (Element) elements.get("socialInsuranceRateSetting");
		this.informationSubmitted = (Element) elements.get("informationSubmitted");
		this.weekdaylateNight = (Element) elements.get("weekdaylateNight");
		this.dprc_BS_ByMonthMethod_Disp = (Element) elements.get("dprc_BS_ByMonthMethod_Disp");
		this.editAssetAccountSetting_Title = (Element) elements.get("editAssetAccountSetting_Title");
		this.individualAddressBuilding_name = (Element) elements.get("individualAddressBuilding_name");
		this.companyAddressTwon_name = (Element) elements.get("companyAddressTwon_name");
		this.dprc_BS_DprcContentSummaryType = (Element) elements.get("dprc_BS_DprcContentSummaryType");
		this.dprc_EditMenu_Add_PopUp_AdrsRO = (Element) elements.get("dprc_EditMenu_Add_PopUp_AdrsRO");
		this.individualAddressProvince_name = (Element) elements.get("individualAddressProvince_name");
		this.monthlyEmployeeNoWork = (Element) elements.get("monthlyEmployeeNoWork");
		this.dprc_BS_CarryingAmountInput_Disp = (Element) elements.get("dprc_BS_CarryingAmountInput_Disp");
		this.individualPaymentYear = (Element) elements.get("individualPaymentYear");
		this.dprc_BS_CarryingAmountInput_Accumulate = (Element) elements.get("dprc_BS_CarryingAmountInput_Accumulate");
		this.individualAddressTwon_name = (Element) elements.get("individualAddressTwon_name");
		this.individualAddressProvinceKana = (Element) elements.get("individualAddressProvinceKana");
		this.paymentDay = (Element) elements.get("paymentDay");
		this.dprc_BS_CompanyKanaName_Disp = (Element) elements.get("dprc_BS_CompanyKanaName_Disp");
		this.specialEquipmentCalc = (Element) elements.get("specialEquipmentCalc");
		this.careInsurance_paymentYear_new = (Element) elements.get("careInsurance_paymentYear_new");
		this.errorHint = (Element) elements.get("errorHint");
		this.dprcCountOfMonthType_corprateTax = (Element) elements.get("dprcCountOfMonthType_corprateTax");
		this.excessiveDeficitAmountAdjustmentType = (Element) elements.get("excessiveDeficitAmountAdjustmentType");
		this.overSixtyHourWorkPremiumRate2 = (Element) elements.get("overSixtyHourWorkPremiumRate2");
		this.dprc_BS_War_Ok = (Element) elements.get("dprc_BS_War_Ok");
		this.dprcManufacturingExpenseAccount_Button = (Element) elements.get("dprcManufacturingExpenseAccount_Button");
		this.oneTimeTit_InDateSet = (Element) elements.get("oneTimeTit_InDateSet");
		this.firstNameKana = (Element) elements.get("firstNameKana");
		this.menuBar = (Element) elements.get("menuBar");
		this.editUsageFlag = (Element) elements.get("editUsageFlag");
		this.healthInsuranceRate_new = (Element) elements.get("healthInsuranceRate_new");
		this.dprcExecutingRate = (Element) elements.get("dprcExecutingRate");
		this.healthInsurance_paymentYear = (Element) elements.get("healthInsurance_paymentYear");
		this.telephoneNumber1 = (Element) elements.get("telephoneNumber1");
		this.telephoneNumber2 = (Element) elements.get("telephoneNumber2");
		this.telephoneNumber3 = (Element) elements.get("telephoneNumber3");
		this.MethodOfSalaryPayment = (Element) elements.get("MethodOfSalaryPayment");
		this.typesOfLocalTax_dis = (Element) elements.get("typesOfLocalTax_dis");
		this.dprc_BS_BusinessPeriod_EndMonth = (Element) elements.get("dprc_BS_BusinessPeriod_EndMonth");
		this.operatingExpenseAccount = (Element) elements.get("operatingExpenseAccount");
		this.dprc_BS_Code_Disp_Ind = (Element) elements.get("dprc_BS_Code_Disp_Ind");
		this.individualAddressCityKana1 = (Element) elements.get("individualAddressCityKana1");
		this.pensionFundsAmount_input_dis = (Element) elements.get("pensionFundsAmount_input_dis");
		this.individualAddressCityKana2 = (Element) elements.get("individualAddressCityKana2");
		this.dprc_EditMenu_Delete = (Element) elements.get("dprc_EditMenu_Delete");
		this.companyBasicInformation = (Element) elements.get("companyBasicInformation");
		this.oneTimeYear_disp = (Element) elements.get("oneTimeYear_disp");
		this.editDepSetting_InstallationSite = (Element) elements.get("editDepSetting_InstallationSite");
		this.pensionFoundAmountModule = (Element) elements.get("pensionFoundAmountModule");
		this.afterButton = (Element) elements.get("afterButton");
		this.healthInsuranceType = (Element) elements.get("healthInsuranceType");
		this.dprc_popUp_OK2 = (Element) elements.get("dprc_popUp_OK2");
		this.zipCode1 = (Element) elements.get("zipCode1");
		this.telephoneNumber_disp = (Element) elements.get("telephoneNumber_disp");
		this.dprcBaseSet = (Element) elements.get("dprcBaseSet");
		this.dprc_FileMenu_Save = (Element) elements.get("dprc_FileMenu_Save");
		this.zipCode2 = (Element) elements.get("zipCode2");
		this.individualDisplayCode = (Element) elements.get("individualDisplayCode");
		this.dailyEmployeeOvertime = (Element) elements.get("dailyEmployeeOvertime");
		this.monthlyEmployeeAbsence = (Element) elements.get("monthlyEmployeeAbsence");
		this.clientFileButton = (Element) elements.get("clientFileButton");
		this.socialSecurityNewPersonPaymentPr2 = (Element) elements.get("socialSecurityNewPersonPaymentPr2");
		this.pensionFoundAmount = (Element) elements.get("pensionFoundAmount");
		this.dprc_BS_CalcRound_Disp = (Element) elements.get("dprc_BS_CalcRound_Disp");
		this.healthInsuranceProportion_input = (Element) elements.get("healthInsuranceProportion_input");
		this.dprc_FileMenu_Logout = (Element) elements.get("dprc_FileMenu_Logout");
		this.theRemainingPercentage_dis = (Element) elements.get("theRemainingPercentage_dis");
		this.companyName_name = (Element) elements.get("companyName_name");
		this.familyNameKana_name = (Element) elements.get("familyNameKana_name");
		this.SelectTaxOffice_Cancel = (Element) elements.get("SelectTaxOffice_Cancel");
		this.companyKana = (Element) elements.get("companyKana");
		this.careInsranceNewAmountDay = (Element) elements.get("careInsranceNewAmountDay");
		this.monthlyTable = (Element) elements.get("monthlyTable");
		this.SelectTaxOffice_Select = (Element) elements.get("SelectTaxOffice_Select");
		this.addressNameKana_dis = (Element) elements.get("addressNameKana_dis");
		this.healthInsuranceProportion = (Element) elements.get("healthInsuranceProportion");
		this.dprc_FileMenu_Close = (Element) elements.get("dprc_FileMenu_Close");
		this.firstLine = (Element) elements.get("firstLine");
		this.editDepSetting_Save = (Element) elements.get("editDepSetting_Save");
		this.overtimeAndNoWork = (Element) elements.get("overtimeAndNoWork");
		this.dprc_BS_CapitalExpense_Apply = (Element) elements.get("dprc_BS_CapitalExpense_Apply");
		this.individualNameKana_dis = (Element) elements.get("individualNameKana_dis");
		this.careInsranceOldAmountMonth = (Element) elements.get("careInsranceOldAmountMonth");
		this.dprc_BS_DeferredAsset = (Element) elements.get("dprc_BS_DeferredAsset");
		this.individualAddressStreetKana1 = (Element) elements.get("individualAddressStreetKana1");
		this.dprc_EditMenu_Add_PopUp_telephone3 = (Element) elements.get("dprc_EditMenu_Add_PopUp_telephone3");
		this.individualAddressStreetKana2 = (Element) elements.get("individualAddressStreetKana2");
		this.careNewPersonPaymentPr = (Element) elements.get("careNewPersonPaymentPr");
		this.dprc_EditMenu_Add_PopUp_telephone1 = (Element) elements.get("dprc_EditMenu_Add_PopUp_telephone1");
		this.lengthThanSixtyWornForm = (Element) elements.get("lengthThanSixtyWornForm");
		this.dprc_EditMenu_Add_PopUp_telephone2 = (Element) elements.get("dprc_EditMenu_Add_PopUp_telephone2");
		this.clientTaxNumber_dis = (Element) elements.get("clientTaxNumber_dis");
		this.dprc_FileMenu_Cancel = (Element) elements.get("dprc_FileMenu_Cancel");
		this.asset_PopUp_method = (Element) elements.get("asset_PopUp_method");
		this.individualAddress_dis = (Element) elements.get("individualAddress_dis");
		this.bankName_dis = (Element) elements.get("bankName_dis");
		this.dprc_popUp_message = (Element) elements.get("dprc_popUp_message");
		this.socialSecuritySwitch = (Element) elements.get("socialSecuritySwitch");
		this.depreciationMethod_dis = (Element) elements.get("depreciationMethod_dis");
		this.dprc_EditMenu_Add_PopUp_AdrsTown = (Element) elements.get("dprc_EditMenu_Add_PopUp_AdrsTown");
		this.dprc_SM_F5 = (Element) elements.get("dprc_SM_F5");
		this.dprc_SM_F4 = (Element) elements.get("dprc_SM_F4");
		this.socialSecurityOldPersonPaymentPr = (Element) elements.get("socialSecurityOldPersonPaymentPr");
		this.dprc_BS_CapitalExpense_NotApply = (Element) elements.get("dprc_BS_CapitalExpense_NotApply");
		this.individualAddressBuildingKana1 = (Element) elements.get("individualAddressBuildingKana1");
		this.file = (Element) elements.get("file");
		this.individualAddressBuildingKana2 = (Element) elements.get("individualAddressBuildingKana2");
		this.dprc_SM_ESC = (Element) elements.get("dprc_SM_ESC");
		this.thirdTimeTit_InDateSet = (Element) elements.get("thirdTimeTit_InDateSet");
		this.holidaylateNight = (Element) elements.get("holidaylateNight");
		this.overtimeWork_dis = (Element) elements.get("overtimeWork_dis");
		this.manageOvertimeNoWorkFlag = (Element) elements.get("manageOvertimeNoWorkFlag");
		this.careInsStartApplying_old = (Element) elements.get("careInsStartApplying_old");
		this.insuredPersonPaymentPr2_dis = (Element) elements.get("insuredPersonPaymentPr2_dis");
		this.pensionFundsAmount_input = (Element) elements.get("pensionFundsAmount_input");
		this.insuredPersonPaymentProportion_other = (Element) elements.get("insuredPersonPaymentProportion_other");
		this.healthInsurance_paymentMonth = (Element) elements.get("healthInsurance_paymentMonth");
		this.bankName = (Element) elements.get("bankName");
		this.individualAddressCity_name = (Element) elements.get("individualAddressCity_name");
		this.beforeButton = (Element) elements.get("beforeButton");
		this.companyDisplayNameKana = (Element) elements.get("companyDisplayNameKana");
		this.assetsSubjectCodeOne = (Element) elements.get("assetsSubjectCodeOne");
		this.dprc_BS_BusinessPeriod_Months = (Element) elements.get("dprc_BS_BusinessPeriod_Months");
		this.healthInsStartApplying = (Element) elements.get("healthInsStartApplying");
		this.pageTitle = (Element) elements.get("pageTitle");
		this.saving = (Element) elements.get("saving");
		this.socialInsuranceJoin = (Element) elements.get("socialInsuranceJoin");
		this.memorandumValueType_dis = (Element) elements.get("memorandumValueType_dis");
		this.careInsurance_paymentYear = (Element) elements.get("careInsurance_paymentYear");
		this.installationAddButton = (Element) elements.get("installationAddButton");
		this.overtimeWork = (Element) elements.get("overtimeWork");
		this.dprc_EditMenu_Add_PopUp_Save = (Element) elements.get("dprc_EditMenu_Add_PopUp_Save");
		this.familyName = (Element) elements.get("familyName");
		this.bonusPaymentDateSetting_page = (Element) elements.get("bonusPaymentDateSetting_page");
		this.dprc_BS_CalcRound = (Element) elements.get("dprc_BS_CalcRound");
		this.CalcRoundingMethodOfLaborInsurance = (Element) elements.get("CalcRoundingMethodOfLaborInsurance");
		this.dailyAndHourEmployeeSetting_dis = (Element) elements.get("dailyAndHourEmployeeSetting_dis");
		this.dprc_FileMenu = (Element) elements.get("dprc_FileMenu");
		this.dprc_EditMenu_Add_PopUp_InstSiteCode = (Element) elements.get("dprc_EditMenu_Add_PopUp_InstSiteCode");
		this.dprc_EditMenu_Add_PopUp_NextInput = (Element) elements.get("dprc_EditMenu_Add_PopUp_NextInput");
		this.file_createNewPeriod = (Element) elements.get("file_createNewPeriod");
		this.dprc_EditMenu_Add_PopUp_ZipCode2 = (Element) elements.get("dprc_EditMenu_Add_PopUp_ZipCode2");
		this.dprc_popUp_cancel2 = (Element) elements.get("dprc_popUp_cancel2");
		this.dprc_EditMenu_Add_PopUp_ZipCode1 = (Element) elements.get("dprc_EditMenu_Add_PopUp_ZipCode1");
		this.paymentDateMonth4 = (Element) elements.get("paymentDateMonth4");
		this.dprc_popUp_cancel3 = (Element) elements.get("dprc_popUp_cancel3");
		this.paymentDateMonth3 = (Element) elements.get("paymentDateMonth3");
		this.governmentCode_indiv = (Element) elements.get("governmentCode_indiv");
		this.paymentDateMonth2 = (Element) elements.get("paymentDateMonth2");
		this.payrollPeriod = (Element) elements.get("payrollPeriod");
		this.insuredPersonPaymentPr2 = (Element) elements.get("insuredPersonPaymentPr2");
		this.socialSecurityNewPersonPaymentPr2dis = (Element) elements.get("socialSecurityNewPersonPaymentPr2dis");
		this.pensionFundApplying_new = (Element) elements.get("pensionFundApplying_new");
		this.healthInsOldAmountMonth = (Element) elements.get("healthInsOldAmountMonth");
		this.holidayWornForm = (Element) elements.get("holidayWornForm");
		this.assetAccount_Tab_Intagible = (Element) elements.get("assetAccount_Tab_Intagible");
		this.editDepSetting_NextInput = (Element) elements.get("editDepSetting_NextInput");
		this.individualAddressTwonKana1 = (Element) elements.get("individualAddressTwonKana1");
		this.paymentDay_Feb = (Element) elements.get("paymentDay_Feb");
		this.individualAddressTwonKana2 = (Element) elements.get("individualAddressTwonKana2");
		this.editDepSetting_DepName = (Element) elements.get("editDepSetting_DepName");
		this.careNewPersonPaymentPr_dis = (Element) elements.get("careNewPersonPaymentPr_dis");
		this.tradeName = (Element) elements.get("tradeName");
		this.dprc_EditMenu_Add_PopUp_AdrsRO_List = (Element) elements.get("dprc_EditMenu_Add_PopUp_AdrsRO_List");
		this.dprc_EditMenu_Add = (Element) elements.get("dprc_EditMenu_Add");
		this.socialSecurityOldPersonPaymentPr2 = (Element) elements.get("socialSecurityOldPersonPaymentPr2");
		this.monthlyEmployeeOvertime = (Element) elements.get("monthlyEmployeeOvertime");
		this.socialSecurityStartApplying_old = (Element) elements.get("socialSecurityStartApplying_old");
		this.excessiveDeficitAmountAdjustmentMonth = (Element) elements.get("excessiveDeficitAmountAdjustmentMonth");
		this.dprc_BS_BusinessPeriod_StartEra = (Element) elements.get("dprc_BS_BusinessPeriod_StartEra");
		this.individualAddressKana_dis = (Element) elements.get("individualAddressKana_dis");
		this.dateSettingYesButton = (Element) elements.get("dateSettingYesButton");
		this.dprc_popUp_OK = (Element) elements.get("dprc_popUp_OK");
		this.bottomMenu = (Element) elements.get("bottomMenu");
		this.nextMonth = (Element) elements.get("nextMonth");
		this.careInsurance_paymentMonth = (Element) elements.get("careInsurance_paymentMonth");
		this.weekdayNormal = (Element) elements.get("weekdayNormal");
		this.perfectureType_dis = (Element) elements.get("perfectureType_dis");
		this.socialSecurityAmount = (Element) elements.get("socialSecurityAmount");
		this.assetListCount = (Element) elements.get("assetListCount");
		this.addressName_dis = (Element) elements.get("addressName_dis");
		this.firstName_name = (Element) elements.get("firstName_name");
		this.absence1 = (Element) elements.get("absence1");
		this.usedBankTransferRequest = (Element) elements.get("usedBankTransferRequest");
		this.individualZipCode_dis = (Element) elements.get("individualZipCode_dis");
		this.dprc_BS_FiveYearCalcRound = (Element) elements.get("dprc_BS_FiveYearCalcRound");
		this.sequenceRecord_Msg = (Element) elements.get("sequenceRecord_Msg");
		this.pensionFund_paymentYear_new = (Element) elements.get("pensionFund_paymentYear_new");
		this.SelectTaxOffice_FirstLine = (Element) elements.get("SelectTaxOffice_FirstLine");
		this.dprc_BS_OneTime_Disp = (Element) elements.get("dprc_BS_OneTime_Disp");
		this.dprc_BS_BusinessPeriod_endDate = (Element) elements.get("dprc_BS_BusinessPeriod_endDate");
		this.dpmSet = (Element) elements.get("dpmSet");
		this.firstName = (Element) elements.get("firstName");
		this.dprc_SM_F12 = (Element) elements.get("dprc_SM_F12");
		this.insuredPersonPaymentPr = (Element) elements.get("insuredPersonPaymentPr");
		this.SelectTaxOfficeButton = (Element) elements.get("SelectTaxOfficeButton");
		this.check = (Element) elements.get("check");
		this.manageHoliday = (Element) elements.get("manageHoliday");
		this.definition = (Element) elements.get("definition");
		this.thisMonth = (Element) elements.get("thisMonth");
		this.tradeName2 = (Element) elements.get("tradeName2");
		this.dprc_EditMenu_Add_PopUp_AdrsBuilding = (Element) elements.get("dprc_EditMenu_Add_PopUp_AdrsBuilding");
		this.paymentMonth_Feb = (Element) elements.get("paymentMonth_Feb");
		this.editDepSetting_DepCode = (Element) elements.get("editDepSetting_DepCode");
		this.clientFormsButton = (Element) elements.get("clientFormsButton");
		this.zipCode_disp = (Element) elements.get("zipCode_disp");
		this.generalExpenseAccount = (Element) elements.get("generalExpenseAccount");
		this.socialSecurityOldPersonPaymentPr_dis = (Element) elements.get("socialSecurityOldPersonPaymentPr_dis");
		this.dprc_BS_LimitParRound_Disp = (Element) elements.get("dprc_BS_LimitParRound_Disp");
		this.paymentDateSetting = (Element) elements.get("paymentDateSetting");
		this.fourthTimeYear_disp = (Element) elements.get("fourthTimeYear_disp");
		this.dprc_InstList = (Element) elements.get("dprc_InstList");
		this.constructionPeriodFlag = (Element) elements.get("constructionPeriodFlag");
		this.companyAddressProvinceKana = (Element) elements.get("companyAddressProvinceKana");
		this.companyType = (Element) elements.get("companyType");
		this.fullName = (Element) elements.get("fullName");
		this.assetsSubjectCode = (Element) elements.get("assetsSubjectCode");
		this.dprc_BS_BusinessPeriod_EndYear = (Element) elements.get("dprc_BS_BusinessPeriod_EndYear");
	}
}
