/**
 * 
 */
package com.asaas.test.util;

import java.util.HashMap;

/**
 * @author
 * 
 */
public class PaymentStatements implements Page {
    // Declare variable
	public Element attendanceDays_monthly_3;
	public Element attendanceDays_monthly_2;
	public Element attendanceDays_monthly_1;
	public Element overFourtyFiveHours;
	public Element list_noWork_Hours;
	public Element allowanceName;
	public Element menu_File_CreatPayrollPeriod;
	public Element sum_healthInsurance_careInsurance;
	public Element travelAllowance;
	public Element thirdLockIcon;
	public Element ordinaryHolidayHour;
	public Element normalWeekdayHour;
	public Element noWork_Mins_disp;
	public Element paymentMoneyType;
	public Element employeePension;
	public Element fee2;
	public Element fileMenu_Edit_restoreModify;
	public Element socialInsurance_disp;
	public Element totalAmountPaidTaxable;
	public Element lockMonth;
	public Element fee;
	public Element unitPriceOfOverWork10;
	public Element unitPriceOfOverWork11;
	public Element fileMenu_print;
	public Element cashPayment;
	public Element cashPayment_dis;
	public Element deductionName;
	public Element list_midnightOnWeekdaysHour;
	public Element noWork_Hours_disp;
	public Element paymentTransferRequest;
	public Element clientName;
	public Element noWork_Hours;
	public Element attendanceMins;
	public Element baseSalaryAllowance10;
	public Element totalSocialInsurance;
	public Element baseSalaryAllowance11;
	public Element list_exceedSixMinute;
	public Element nonTaxablePayment;
	public Element fixedPyroll5;
	public Element unemployeeBenefit5;
	public Element fixedPyroll4;
	public Element unemployeeBenefit4;
	public Element fixedPyroll3;
	public Element unemployeeBenefit7;
	public Element fixedPyroll2;
	public Element unemployeeBenefit6;
	public Element fixedPyroll9;
	public Element unemployeeBenefit1;
	public Element fixedPyroll8;
	public Element requestForSalaryTransfer;
	public Element fixedPyroll7;
	public Element unemployeeBenefit3;
	public Element fixedPyroll6;
	public Element unemployeeBenefit2;
	public Element absenceDays;
	public Element totalDeduction;
	public Element fixedPyroll1;
	public Element unemployeeBenefit9;
	public Element unemployeeBenefit8;
	public Element employee1_InList;
	public Element socialInsurance;
	public Element fileMenu_Edit_edit;
	public Element allowanceDeductionSettingPage;
	public Element cancel;
	public Element paymentForms_SubmissionForms;
	public Element close;
	public Element midnightStatutoryHolidayMinute;
	public Element employeePageSumm;
	public Element weekdayMins_disp;
	public Element insertExcessiveDeficitAmount;
	public Element nonEmploymentDeduction;
	public Element adjustmentTwo;
	public Element list_attendanceHours;
	public Element overtimePay_Disp;
	public Element paymentFormsButton;
	public Element exceedSixMinute;
	public Element list_midnightOnWeekdaysMinute;
	public Element attendanceDays_disp;
	public Element firstLockIcon;
	public Element unlockmonth1;
	public Element unlockmonth2;
	public Element unlockmonth3;
	public Element unlockmonth4;
	public Element unlockmonth5;
	public Element unlockmonth6;
	public Element unlockmonth7;
	public Element unlockmonth8;
	public Element unlockmonth9;
	public Element reCalc;
	public Element name;
	public Element taxablePayment;
	public Element insertExcessive_choose;
	public Element withholdingIncomeTax11;
	public Element withholdingIncomeTax10;
	public Element offHoursHour;
	public Element edit;
	public Element withholdingIncomeTax4;
	public Element list_ordinaryStatutoryHolidayHour;
	public Element withholdingIncomeTax3;
	public Element withholdingIncomeTax2;
	public Element withholdingIncomeTax1;
	public Element ordinaryStatutoryHolidayHour;
	public Element normalWeekdayMinute;
	public Element deductionName_Name6;
	public Element withholdingIncomeTax9;
	public Element deductionName_Name7;
	public Element attendanceHours;
	public Element deductionName_Name4;
	public Element withholdingIncomeTax7;
	public Element deductionName_Name5;
	public Element withholdingIncomeTax8;
	public Element deductionName_Name2;
	public Element withholdingIncomeTax5;
	public Element deductionName_Name3;
	public Element withholdingIncomeTax6;
	public Element fileMenu_Edit_edit2;
	public Element list_overFourtyFiveMinute;
	public Element transferRequest_payeeCode;
	public Element ordinaryStatutoryHolidayMinute;
	public Element careInsurance;
	public Element Deduction1_dispName;
	public Element sumPay;
	public Element restoreModifyForm;
	public Element deductionName1_disp;
	public Element list_attendanceDays;
	public Element moneyTypeEmployeeName;
	public Element fileMenu_Edit_recalculate;
	public Element attendanceMinute_dayly_1;
	public Element fileMenu_lockMonth;
	public Element attendanceMinute_dayly_3;
	public Element attendanceMinute_dayly_2;
	public Element ordinaryHolidayMinute;
	public Element employee2_InList;
	public Element allowanceName_Name8;
	public Element exceedSixHours;
	public Element allowanceName_Name7;
	public Element allowanceName_Name9;
	public Element list_absenceDays;
	public Element insertEmployeeAll;
	public Element transferRequest_button;
	public Element noWork_Mins;
	public Element secondLockIcon;
	public Element list_attendanceMins;
	public Element welfarePensionFund;
	public Element lateNightHolidayHour;
	public Element salary_button;
	public Element tax;
	public Element enterPayslip;
	public Element lessPayment;
	public Element bankTransfer_dis;
	public Element allowanceName_Name2;
	public Element insertExcessive_change;
	public Element allowanceName_Name3;
	public Element allowanceName_Name4;
	public Element employeeInsurance_dis;
	public Element allowanceName_Name5;
	public Element allowanceName_Name6;
	public Element list_noWork_Mins;
	public Element totalNumberOfFees;
	public Element salaryEmployeeInf;
	public Element fileMenu;
	public Element list_ordinaryStatutoryHolidayMinute;
	public Element list_exceedSixHours;
	public Element weekdayHours_disp;
	public Element del;
	public Element sum_social_insurance;
	public Element list_overFourtyFiveHours;
	public Element salaryFirstMonth;
	public Element attendanceDays2;
	public Element attendanceDays3;
	public Element attendanceDays1;
	public Element allowanceName_Name11;
	public Element fixedPyroll10;
	public Element allowanceName_Name10;
	public Element fixedPyroll11;
	public Element absenceAndNoWork10;
	public Element absenceAndNoWork4;
	public Element absenceAndNoWork5;
	public Element absenceAndNoWork6;
	public Element absenceAndNoWork7;
	public Element settingOfFixed7;
	public Element absenceAndNoWork8;
	public Element absenceAndNoWork9;
	public Element settingOfFixed5;
	public Element absenceDays_disp;
	public Element settingOfFixed6;
	public Element absenceAndNoWork11;
	public Element settingOfFixed3;
	public Element baseSalaryAllowance;
	public Element settingOfFixed4;
	public Element settingOfFixed1;
	public Element settingOfFixed2;
	public Element absenceAndNoWork1;
	public Element list_midnightStatutoryHolidayHour;
	public Element absenceAndNoWork2;
	public Element absenceAndNoWork3;
	public Element save;
	public Element paymentStatementPrint;
	public Element list_ordinaryHolidayHour;
	public Element list_normalWeekdayHour;
	public Element baseSalary;
	public Element undefinPayment;
	public Element list_normalWeekdayMinute;
	public Element insertEmployee2;
	public Element insertEmployee1;
	public Element paySlipPage;
	public Element annualAdjustmentAmount;
	public Element insertEmployee3;
	public Element fee2_disp;
	public Element midnightStatutoryHolidayHour;
	public Element employee3_InList;
	public Element allowanceDeductionSetting;
	public Element midnightOnWeekdaysHour;
	public Element allowanceName1;
	public Element lateNightHolidayMinute;
	public Element totalDeduction_input;
	public Element healthInsurance;
	public Element adjustmentOne;
	public Element salaryList;
	public Element overFourtyFiveMinute;
	public Element attendanceDays;
	public Element residentTax;
	public Element insertExcessiveTitle;
	public Element overtimePay;
	public Element payrollDeduction1;
	public Element payrollDeduction2;
	public Element offHoursMinute;
	public Element payrollDeduction3;
	public Element payrollDeduction4;
	public Element payrollDeduction5;
	public Element payrollDeduction6;
	public Element bankTransfer;
	public Element payrollDeduction7;
	public Element unemployeeBenefit10;
	public Element totalTableLegalRecordSalaryIncome;
	public Element unemployeeBenefit11;
	public Element employeeInsurance;
	public Element attendanceHour_dayly_2;
	public Element deduction;
	public Element attendanceHour_dayly_3;
	public Element allowanceName1_dispName;
	public Element list_lateNightHolidayMinute;
	public Element midnightOnWeekdaysMinute;
	public Element attendanceHour_dayly_1;
	public Element list_lateNightHolidayHour;
	public Element fee_disp;
	public Element deductionName1;
	public Element definition;
	public Element fileMenu_Edit;
	public Element allowanceName1_disp;
	public Element excute;
	public Element synchronization;
	public Element totalAmountOfFees;
	public Element print;
	public Element allowanceName_dis;
	public Element unlockmonth10;
	public Element unitPriceOfOverWork9;
	public Element baseSalaryAllowance4;
	public Element baseSalaryAllowance3;
	public Element unlockmonth11;
	public Element list_midnightStatutoryHolidayMinute;
	public Element printPopUp_cancel;
	public Element baseSalaryAllowance2;
	public Element cancelPayment;
	public Element list_ordinaryHolidayMinute;
	public Element unitPriceOfOverWork4;
	public Element baseSalaryAllowance8;
	public Element unitPriceOfOverWork3;
	public Element baseSalaryAllowance7;
	public Element unitPriceOfOverWork2;
	public Element baseSalaryAllowance6;
	public Element unitPriceOfOverWork1;
	public Element baseSalaryAllowance5;
	public Element unitPriceOfOverWork8;
	public Element unitPriceOfOverWork7;
	public Element unitPriceOfOverWork6;
	public Element unitPriceOfOverWork5;
	public Element baseSalaryAllowance9;

    /*
     * @see com.asaas.test.util.Page#init(java.util.HashMap)
     */
    public void init(HashMap<String, Object> elements) {
        // Initialize variable
		this.attendanceDays_monthly_3 = (Element) elements.get("attendanceDays_monthly_3");
		this.attendanceDays_monthly_2 = (Element) elements.get("attendanceDays_monthly_2");
		this.attendanceDays_monthly_1 = (Element) elements.get("attendanceDays_monthly_1");
		this.overFourtyFiveHours = (Element) elements.get("overFourtyFiveHours");
		this.list_noWork_Hours = (Element) elements.get("list_noWork_Hours");
		this.allowanceName = (Element) elements.get("allowanceName");
		this.menu_File_CreatPayrollPeriod = (Element) elements.get("menu_File_CreatPayrollPeriod");
		this.sum_healthInsurance_careInsurance = (Element) elements.get("sum_healthInsurance_careInsurance");
		this.travelAllowance = (Element) elements.get("travelAllowance");
		this.thirdLockIcon = (Element) elements.get("thirdLockIcon");
		this.ordinaryHolidayHour = (Element) elements.get("ordinaryHolidayHour");
		this.normalWeekdayHour = (Element) elements.get("normalWeekdayHour");
		this.noWork_Mins_disp = (Element) elements.get("noWork_Mins_disp");
		this.paymentMoneyType = (Element) elements.get("paymentMoneyType");
		this.employeePension = (Element) elements.get("employeePension");
		this.fee2 = (Element) elements.get("fee2");
		this.fileMenu_Edit_restoreModify = (Element) elements.get("fileMenu_Edit_restoreModify");
		this.socialInsurance_disp = (Element) elements.get("socialInsurance_disp");
		this.totalAmountPaidTaxable = (Element) elements.get("totalAmountPaidTaxable");
		this.lockMonth = (Element) elements.get("lockMonth");
		this.fee = (Element) elements.get("fee");
		this.unitPriceOfOverWork10 = (Element) elements.get("unitPriceOfOverWork10");
		this.unitPriceOfOverWork11 = (Element) elements.get("unitPriceOfOverWork11");
		this.fileMenu_print = (Element) elements.get("fileMenu_print");
		this.cashPayment = (Element) elements.get("cashPayment");
		this.cashPayment_dis = (Element) elements.get("cashPayment_dis");
		this.deductionName = (Element) elements.get("deductionName");
		this.list_midnightOnWeekdaysHour = (Element) elements.get("list_midnightOnWeekdaysHour");
		this.noWork_Hours_disp = (Element) elements.get("noWork_Hours_disp");
		this.paymentTransferRequest = (Element) elements.get("paymentTransferRequest");
		this.clientName = (Element) elements.get("clientName");
		this.noWork_Hours = (Element) elements.get("noWork_Hours");
		this.attendanceMins = (Element) elements.get("attendanceMins");
		this.baseSalaryAllowance10 = (Element) elements.get("baseSalaryAllowance10");
		this.totalSocialInsurance = (Element) elements.get("totalSocialInsurance");
		this.baseSalaryAllowance11 = (Element) elements.get("baseSalaryAllowance11");
		this.list_exceedSixMinute = (Element) elements.get("list_exceedSixMinute");
		this.nonTaxablePayment = (Element) elements.get("nonTaxablePayment");
		this.fixedPyroll5 = (Element) elements.get("fixedPyroll5");
		this.unemployeeBenefit5 = (Element) elements.get("unemployeeBenefit5");
		this.fixedPyroll4 = (Element) elements.get("fixedPyroll4");
		this.unemployeeBenefit4 = (Element) elements.get("unemployeeBenefit4");
		this.fixedPyroll3 = (Element) elements.get("fixedPyroll3");
		this.unemployeeBenefit7 = (Element) elements.get("unemployeeBenefit7");
		this.fixedPyroll2 = (Element) elements.get("fixedPyroll2");
		this.unemployeeBenefit6 = (Element) elements.get("unemployeeBenefit6");
		this.fixedPyroll9 = (Element) elements.get("fixedPyroll9");
		this.unemployeeBenefit1 = (Element) elements.get("unemployeeBenefit1");
		this.fixedPyroll8 = (Element) elements.get("fixedPyroll8");
		this.requestForSalaryTransfer = (Element) elements.get("requestForSalaryTransfer");
		this.fixedPyroll7 = (Element) elements.get("fixedPyroll7");
		this.unemployeeBenefit3 = (Element) elements.get("unemployeeBenefit3");
		this.fixedPyroll6 = (Element) elements.get("fixedPyroll6");
		this.unemployeeBenefit2 = (Element) elements.get("unemployeeBenefit2");
		this.absenceDays = (Element) elements.get("absenceDays");
		this.totalDeduction = (Element) elements.get("totalDeduction");
		this.fixedPyroll1 = (Element) elements.get("fixedPyroll1");
		this.unemployeeBenefit9 = (Element) elements.get("unemployeeBenefit9");
		this.unemployeeBenefit8 = (Element) elements.get("unemployeeBenefit8");
		this.employee1_InList = (Element) elements.get("employee1_InList");
		this.socialInsurance = (Element) elements.get("socialInsurance");
		this.fileMenu_Edit_edit = (Element) elements.get("fileMenu_Edit_edit");
		this.allowanceDeductionSettingPage = (Element) elements.get("allowanceDeductionSettingPage");
		this.cancel = (Element) elements.get("cancel");
		this.paymentForms_SubmissionForms = (Element) elements.get("paymentForms_SubmissionForms");
		this.close = (Element) elements.get("close");
		this.midnightStatutoryHolidayMinute = (Element) elements.get("midnightStatutoryHolidayMinute");
		this.employeePageSumm = (Element) elements.get("employeePageSumm");
		this.weekdayMins_disp = (Element) elements.get("weekdayMins_disp");
		this.insertExcessiveDeficitAmount = (Element) elements.get("insertExcessiveDeficitAmount");
		this.nonEmploymentDeduction = (Element) elements.get("nonEmploymentDeduction");
		this.adjustmentTwo = (Element) elements.get("adjustmentTwo");
		this.list_attendanceHours = (Element) elements.get("list_attendanceHours");
		this.overtimePay_Disp = (Element) elements.get("overtimePay_Disp");
		this.paymentFormsButton = (Element) elements.get("paymentFormsButton");
		this.exceedSixMinute = (Element) elements.get("exceedSixMinute");
		this.list_midnightOnWeekdaysMinute = (Element) elements.get("list_midnightOnWeekdaysMinute");
		this.attendanceDays_disp = (Element) elements.get("attendanceDays_disp");
		this.firstLockIcon = (Element) elements.get("firstLockIcon");
		this.unlockmonth1 = (Element) elements.get("unlockmonth1");
		this.unlockmonth2 = (Element) elements.get("unlockmonth2");
		this.unlockmonth3 = (Element) elements.get("unlockmonth3");
		this.unlockmonth4 = (Element) elements.get("unlockmonth4");
		this.unlockmonth5 = (Element) elements.get("unlockmonth5");
		this.unlockmonth6 = (Element) elements.get("unlockmonth6");
		this.unlockmonth7 = (Element) elements.get("unlockmonth7");
		this.unlockmonth8 = (Element) elements.get("unlockmonth8");
		this.unlockmonth9 = (Element) elements.get("unlockmonth9");
		this.reCalc = (Element) elements.get("reCalc");
		this.name = (Element) elements.get("name");
		this.taxablePayment = (Element) elements.get("taxablePayment");
		this.insertExcessive_choose = (Element) elements.get("insertExcessive_choose");
		this.withholdingIncomeTax11 = (Element) elements.get("withholdingIncomeTax11");
		this.withholdingIncomeTax10 = (Element) elements.get("withholdingIncomeTax10");
		this.offHoursHour = (Element) elements.get("offHoursHour");
		this.edit = (Element) elements.get("edit");
		this.withholdingIncomeTax4 = (Element) elements.get("withholdingIncomeTax4");
		this.list_ordinaryStatutoryHolidayHour = (Element) elements.get("list_ordinaryStatutoryHolidayHour");
		this.withholdingIncomeTax3 = (Element) elements.get("withholdingIncomeTax3");
		this.withholdingIncomeTax2 = (Element) elements.get("withholdingIncomeTax2");
		this.withholdingIncomeTax1 = (Element) elements.get("withholdingIncomeTax1");
		this.ordinaryStatutoryHolidayHour = (Element) elements.get("ordinaryStatutoryHolidayHour");
		this.normalWeekdayMinute = (Element) elements.get("normalWeekdayMinute");
		this.deductionName_Name6 = (Element) elements.get("deductionName_Name6");
		this.withholdingIncomeTax9 = (Element) elements.get("withholdingIncomeTax9");
		this.deductionName_Name7 = (Element) elements.get("deductionName_Name7");
		this.attendanceHours = (Element) elements.get("attendanceHours");
		this.deductionName_Name4 = (Element) elements.get("deductionName_Name4");
		this.withholdingIncomeTax7 = (Element) elements.get("withholdingIncomeTax7");
		this.deductionName_Name5 = (Element) elements.get("deductionName_Name5");
		this.withholdingIncomeTax8 = (Element) elements.get("withholdingIncomeTax8");
		this.deductionName_Name2 = (Element) elements.get("deductionName_Name2");
		this.withholdingIncomeTax5 = (Element) elements.get("withholdingIncomeTax5");
		this.deductionName_Name3 = (Element) elements.get("deductionName_Name3");
		this.withholdingIncomeTax6 = (Element) elements.get("withholdingIncomeTax6");
		this.fileMenu_Edit_edit2 = (Element) elements.get("fileMenu_Edit_edit2");
		this.list_overFourtyFiveMinute = (Element) elements.get("list_overFourtyFiveMinute");
		this.transferRequest_payeeCode = (Element) elements.get("transferRequest_payeeCode");
		this.ordinaryStatutoryHolidayMinute = (Element) elements.get("ordinaryStatutoryHolidayMinute");
		this.careInsurance = (Element) elements.get("careInsurance");
		this.Deduction1_dispName = (Element) elements.get("Deduction1_dispName");
		this.sumPay = (Element) elements.get("sumPay");
		this.restoreModifyForm = (Element) elements.get("restoreModifyForm");
		this.deductionName1_disp = (Element) elements.get("deductionName1_disp");
		this.list_attendanceDays = (Element) elements.get("list_attendanceDays");
		this.moneyTypeEmployeeName = (Element) elements.get("moneyTypeEmployeeName");
		this.fileMenu_Edit_recalculate = (Element) elements.get("fileMenu_Edit_recalculate");
		this.attendanceMinute_dayly_1 = (Element) elements.get("attendanceMinute_dayly_1");
		this.fileMenu_lockMonth = (Element) elements.get("fileMenu_lockMonth");
		this.attendanceMinute_dayly_3 = (Element) elements.get("attendanceMinute_dayly_3");
		this.attendanceMinute_dayly_2 = (Element) elements.get("attendanceMinute_dayly_2");
		this.ordinaryHolidayMinute = (Element) elements.get("ordinaryHolidayMinute");
		this.employee2_InList = (Element) elements.get("employee2_InList");
		this.allowanceName_Name8 = (Element) elements.get("allowanceName_Name8");
		this.exceedSixHours = (Element) elements.get("exceedSixHours");
		this.allowanceName_Name7 = (Element) elements.get("allowanceName_Name7");
		this.allowanceName_Name9 = (Element) elements.get("allowanceName_Name9");
		this.list_absenceDays = (Element) elements.get("list_absenceDays");
		this.insertEmployeeAll = (Element) elements.get("insertEmployeeAll");
		this.transferRequest_button = (Element) elements.get("transferRequest_button");
		this.noWork_Mins = (Element) elements.get("noWork_Mins");
		this.secondLockIcon = (Element) elements.get("secondLockIcon");
		this.list_attendanceMins = (Element) elements.get("list_attendanceMins");
		this.welfarePensionFund = (Element) elements.get("welfarePensionFund");
		this.lateNightHolidayHour = (Element) elements.get("lateNightHolidayHour");
		this.salary_button = (Element) elements.get("salary_button");
		this.tax = (Element) elements.get("tax");
		this.enterPayslip = (Element) elements.get("enterPayslip");
		this.lessPayment = (Element) elements.get("lessPayment");
		this.bankTransfer_dis = (Element) elements.get("bankTransfer_dis");
		this.allowanceName_Name2 = (Element) elements.get("allowanceName_Name2");
		this.insertExcessive_change = (Element) elements.get("insertExcessive_change");
		this.allowanceName_Name3 = (Element) elements.get("allowanceName_Name3");
		this.allowanceName_Name4 = (Element) elements.get("allowanceName_Name4");
		this.employeeInsurance_dis = (Element) elements.get("employeeInsurance_dis");
		this.allowanceName_Name5 = (Element) elements.get("allowanceName_Name5");
		this.allowanceName_Name6 = (Element) elements.get("allowanceName_Name6");
		this.list_noWork_Mins = (Element) elements.get("list_noWork_Mins");
		this.totalNumberOfFees = (Element) elements.get("totalNumberOfFees");
		this.salaryEmployeeInf = (Element) elements.get("salaryEmployeeInf");
		this.fileMenu = (Element) elements.get("fileMenu");
		this.list_ordinaryStatutoryHolidayMinute = (Element) elements.get("list_ordinaryStatutoryHolidayMinute");
		this.list_exceedSixHours = (Element) elements.get("list_exceedSixHours");
		this.weekdayHours_disp = (Element) elements.get("weekdayHours_disp");
		this.del = (Element) elements.get("del");
		this.sum_social_insurance = (Element) elements.get("sum_social_insurance");
		this.list_overFourtyFiveHours = (Element) elements.get("list_overFourtyFiveHours");
		this.salaryFirstMonth = (Element) elements.get("salaryFirstMonth");
		this.attendanceDays2 = (Element) elements.get("attendanceDays2");
		this.attendanceDays3 = (Element) elements.get("attendanceDays3");
		this.attendanceDays1 = (Element) elements.get("attendanceDays1");
		this.allowanceName_Name11 = (Element) elements.get("allowanceName_Name11");
		this.fixedPyroll10 = (Element) elements.get("fixedPyroll10");
		this.allowanceName_Name10 = (Element) elements.get("allowanceName_Name10");
		this.fixedPyroll11 = (Element) elements.get("fixedPyroll11");
		this.absenceAndNoWork10 = (Element) elements.get("absenceAndNoWork10");
		this.absenceAndNoWork4 = (Element) elements.get("absenceAndNoWork4");
		this.absenceAndNoWork5 = (Element) elements.get("absenceAndNoWork5");
		this.absenceAndNoWork6 = (Element) elements.get("absenceAndNoWork6");
		this.absenceAndNoWork7 = (Element) elements.get("absenceAndNoWork7");
		this.settingOfFixed7 = (Element) elements.get("settingOfFixed7");
		this.absenceAndNoWork8 = (Element) elements.get("absenceAndNoWork8");
		this.absenceAndNoWork9 = (Element) elements.get("absenceAndNoWork9");
		this.settingOfFixed5 = (Element) elements.get("settingOfFixed5");
		this.absenceDays_disp = (Element) elements.get("absenceDays_disp");
		this.settingOfFixed6 = (Element) elements.get("settingOfFixed6");
		this.absenceAndNoWork11 = (Element) elements.get("absenceAndNoWork11");
		this.settingOfFixed3 = (Element) elements.get("settingOfFixed3");
		this.baseSalaryAllowance = (Element) elements.get("baseSalaryAllowance");
		this.settingOfFixed4 = (Element) elements.get("settingOfFixed4");
		this.settingOfFixed1 = (Element) elements.get("settingOfFixed1");
		this.settingOfFixed2 = (Element) elements.get("settingOfFixed2");
		this.absenceAndNoWork1 = (Element) elements.get("absenceAndNoWork1");
		this.list_midnightStatutoryHolidayHour = (Element) elements.get("list_midnightStatutoryHolidayHour");
		this.absenceAndNoWork2 = (Element) elements.get("absenceAndNoWork2");
		this.absenceAndNoWork3 = (Element) elements.get("absenceAndNoWork3");
		this.save = (Element) elements.get("save");
		this.paymentStatementPrint = (Element) elements.get("paymentStatementPrint");
		this.list_ordinaryHolidayHour = (Element) elements.get("list_ordinaryHolidayHour");
		this.list_normalWeekdayHour = (Element) elements.get("list_normalWeekdayHour");
		this.baseSalary = (Element) elements.get("baseSalary");
		this.undefinPayment = (Element) elements.get("undefinPayment");
		this.list_normalWeekdayMinute = (Element) elements.get("list_normalWeekdayMinute");
		this.insertEmployee2 = (Element) elements.get("insertEmployee2");
		this.insertEmployee1 = (Element) elements.get("insertEmployee1");
		this.paySlipPage = (Element) elements.get("paySlipPage");
		this.annualAdjustmentAmount = (Element) elements.get("annualAdjustmentAmount");
		this.insertEmployee3 = (Element) elements.get("insertEmployee3");
		this.fee2_disp = (Element) elements.get("fee2_disp");
		this.midnightStatutoryHolidayHour = (Element) elements.get("midnightStatutoryHolidayHour");
		this.employee3_InList = (Element) elements.get("employee3_InList");
		this.allowanceDeductionSetting = (Element) elements.get("allowanceDeductionSetting");
		this.midnightOnWeekdaysHour = (Element) elements.get("midnightOnWeekdaysHour");
		this.allowanceName1 = (Element) elements.get("allowanceName1");
		this.lateNightHolidayMinute = (Element) elements.get("lateNightHolidayMinute");
		this.totalDeduction_input = (Element) elements.get("totalDeduction_input");
		this.healthInsurance = (Element) elements.get("healthInsurance");
		this.adjustmentOne = (Element) elements.get("adjustmentOne");
		this.salaryList = (Element) elements.get("salaryList");
		this.overFourtyFiveMinute = (Element) elements.get("overFourtyFiveMinute");
		this.attendanceDays = (Element) elements.get("attendanceDays");
		this.residentTax = (Element) elements.get("residentTax");
		this.insertExcessiveTitle = (Element) elements.get("insertExcessiveTitle");
		this.overtimePay = (Element) elements.get("overtimePay");
		this.payrollDeduction1 = (Element) elements.get("payrollDeduction1");
		this.payrollDeduction2 = (Element) elements.get("payrollDeduction2");
		this.offHoursMinute = (Element) elements.get("offHoursMinute");
		this.payrollDeduction3 = (Element) elements.get("payrollDeduction3");
		this.payrollDeduction4 = (Element) elements.get("payrollDeduction4");
		this.payrollDeduction5 = (Element) elements.get("payrollDeduction5");
		this.payrollDeduction6 = (Element) elements.get("payrollDeduction6");
		this.bankTransfer = (Element) elements.get("bankTransfer");
		this.payrollDeduction7 = (Element) elements.get("payrollDeduction7");
		this.unemployeeBenefit10 = (Element) elements.get("unemployeeBenefit10");
		this.totalTableLegalRecordSalaryIncome = (Element) elements.get("totalTableLegalRecordSalaryIncome");
		this.unemployeeBenefit11 = (Element) elements.get("unemployeeBenefit11");
		this.employeeInsurance = (Element) elements.get("employeeInsurance");
		this.attendanceHour_dayly_2 = (Element) elements.get("attendanceHour_dayly_2");
		this.deduction = (Element) elements.get("deduction");
		this.attendanceHour_dayly_3 = (Element) elements.get("attendanceHour_dayly_3");
		this.allowanceName1_dispName = (Element) elements.get("allowanceName1_dispName");
		this.list_lateNightHolidayMinute = (Element) elements.get("list_lateNightHolidayMinute");
		this.midnightOnWeekdaysMinute = (Element) elements.get("midnightOnWeekdaysMinute");
		this.attendanceHour_dayly_1 = (Element) elements.get("attendanceHour_dayly_1");
		this.list_lateNightHolidayHour = (Element) elements.get("list_lateNightHolidayHour");
		this.fee_disp = (Element) elements.get("fee_disp");
		this.deductionName1 = (Element) elements.get("deductionName1");
		this.definition = (Element) elements.get("definition");
		this.fileMenu_Edit = (Element) elements.get("fileMenu_Edit");
		this.allowanceName1_disp = (Element) elements.get("allowanceName1_disp");
		this.excute = (Element) elements.get("excute");
		this.synchronization = (Element) elements.get("synchronization");
		this.totalAmountOfFees = (Element) elements.get("totalAmountOfFees");
		this.print = (Element) elements.get("print");
		this.allowanceName_dis = (Element) elements.get("allowanceName_dis");
		this.unlockmonth10 = (Element) elements.get("unlockmonth10");
		this.unitPriceOfOverWork9 = (Element) elements.get("unitPriceOfOverWork9");
		this.baseSalaryAllowance4 = (Element) elements.get("baseSalaryAllowance4");
		this.baseSalaryAllowance3 = (Element) elements.get("baseSalaryAllowance3");
		this.unlockmonth11 = (Element) elements.get("unlockmonth11");
		this.list_midnightStatutoryHolidayMinute = (Element) elements.get("list_midnightStatutoryHolidayMinute");
		this.printPopUp_cancel = (Element) elements.get("printPopUp_cancel");
		this.baseSalaryAllowance2 = (Element) elements.get("baseSalaryAllowance2");
		this.cancelPayment = (Element) elements.get("cancelPayment");
		this.list_ordinaryHolidayMinute = (Element) elements.get("list_ordinaryHolidayMinute");
		this.unitPriceOfOverWork4 = (Element) elements.get("unitPriceOfOverWork4");
		this.baseSalaryAllowance8 = (Element) elements.get("baseSalaryAllowance8");
		this.unitPriceOfOverWork3 = (Element) elements.get("unitPriceOfOverWork3");
		this.baseSalaryAllowance7 = (Element) elements.get("baseSalaryAllowance7");
		this.unitPriceOfOverWork2 = (Element) elements.get("unitPriceOfOverWork2");
		this.baseSalaryAllowance6 = (Element) elements.get("baseSalaryAllowance6");
		this.unitPriceOfOverWork1 = (Element) elements.get("unitPriceOfOverWork1");
		this.baseSalaryAllowance5 = (Element) elements.get("baseSalaryAllowance5");
		this.unitPriceOfOverWork8 = (Element) elements.get("unitPriceOfOverWork8");
		this.unitPriceOfOverWork7 = (Element) elements.get("unitPriceOfOverWork7");
		this.unitPriceOfOverWork6 = (Element) elements.get("unitPriceOfOverWork6");
		this.unitPriceOfOverWork5 = (Element) elements.get("unitPriceOfOverWork5");
		this.baseSalaryAllowance9 = (Element) elements.get("baseSalaryAllowance9");
	}
}
