/**
 * 
 */
package com.asaas.test.util;

import java.util.HashMap;

/**
 * @author
 * 
 */
public class SocialInsuranceCalculation implements Page {
    // Declare variable
	public Element subject2displayOrder22amount3;
	public Element subject2displayOrder22amount2;
	public Element subject2displayOrder22amount10;
	public Element subject2displayOrder22amount5;
	public Element subject2displayOrder22amount11;
	public Element subject3displayOrder22amount;
	public Element subject2displayOrder22amount4;
	public Element subject2displayOrder22amount12;
	public Element subject2displayOrder22amount7;
	public Element subject2displayOrder22amount13;
	public Element subject2displayOrder22amount6;
	public Element subject2displayOrder22amount14;
	public Element InsuranceAmountFormSubject3Rate6;
	public Element subject2displayOrder22amount9;
	public Element subject2displayOrder22amount15;
	public Element InsuranceAmountFormSubject3Rate5;
	public Element subject2displayOrder22amount8;
	public Element InsuranceAmountFormSubject3Rate4;
	public Element InsuranceAmountFormSubject3Rate2;
	public Element subject2displayOrder22number2;
	public Element subject2displayOrder22number5;
	public Element subject2displayOrder22number6;
	public Element subject2displayOrder22number3;
	public Element subject2displayOrder22number4;
	public Element subject2displayOrder22number9;
	public Element Synchroinzation;
	public Element subject2displayOrder22number7;
	public Element subject2displayOrder22number8;
	public Element subject3displayOrder21amount15;
	public Element subject3displayOrder21amount14;
	public Element subject3displayOrder21amount13;
	public Element subject3displayOrder21amount12;
	public Element subject3displayOrder21amount11;
	public Element subject3displayOrder21amount10;
	public Element diffUnemploymentBenefit;
	public Element subject2displayOrder131amount;
	public Element InsuranceAmountForm;
	public Element subject2displayOrder23amount2;
	public Element exceptionFlag;
	public Element generalAppropriationAmount3;
	public Element subject2displayOrder23amount9;
	public Element subject2displayOrder23amount7;
	public Element subject2displayOrder23amount8;
	public Element subject2displayOrder23amount5;
	public Element subject2displayOrder23amount6;
	public Element subject2displayOrder23amount3;
	public Element employeeName;
	public Element subject2displayOrder23amount4;
	public Element subject2displayOrder22number11;
	public Element subject2displayOrder22number10;
	public Element unemploymentInsuranceType_other;
	public Element InsuranceAmountFormSubject4TotalAmount3;
	public Element ordinaryDecision;
	public Element InsuranceAmountFormSubject4TotalAmount2;
	public Element InsuranceAmountFormSubject4TotalAmount5;
	public Element unemploymentNumber;
	public Element InsuranceAmountFormSubject4TotalAmount4;
	public Element subject2displayOrder22number12;
	public Element InsuranceAmountFormCaption;
	public Element InsuranceAmountFormSubject3Rate;
	public Element calculationStartDate;
	public Element subject2displayOrder23number;
	public Element oDEmployeeName;
	public Element subject3displayOrder22amount13;
	public Element subject3displayOrder22amount12;
	public Element subject2displayOrder24amount;
	public Element subject3displayOrder22amount15;
	public Element subject3displayOrder22amount14;
	public Element SocialSecurityGeneralReward;
	public Element subject3displayOrder22amount11;
	public Element subject3displayOrder22amount10;
	public Element popup_ordinary_caption;
	public Element subject3displayOrder21amount;
	public Element subject2displayOrder23totalAmount;
	public Element unemploymentBenefit;
	public Element oDCaption;
	public Element oDpaymentDateDD3;
	public Element oDpaymentDateDD2;
	public Element close;
	public Element subject3displayOrder24number10;
	public Element oDsumTotalAmount;
	public Element subject3displayOrder24number12;
	public Element subject3displayOrder24number11;
	public Element subject3displayOrder21number12;
	public Element login;
	public Element subject3displayOrder21number10;
	public Element subject3displayOrder21number11;
	public Element unemploymentInsuranceType_general;
	public Element subject3displayOrder24number;
	public Element subject2displayOrder133amount;
	public Element HourlyAverageWorkingHours;
	public Element InsuranceAmountFormSubject4Amount5;
	public Element InsuranceAmountFormSubject4Amount2;
	public Element BaseAmountPayrollSummarySheet;
	public Element deficitAmount5;
	public Element deficitAmount4;
	public Element deficitAmount3;
	public Element deficitAmount2;
	public Element estimatedInsuranceAmount;
	public Element deficitAmount1;
	public Element subject2displayOrder22number;
	public Element ordinaryDecisionCaption;
	public Element oDfixedAverageAmount;
	public Element paymentDateDD3;
	public Element paymentDateDD2;
	public Element subject3displayOrder22number4;
	public Element subject2displayOrder24totalNumber;
	public Element subject3displayOrder22number5;
	public Element subject3displayOrder22number6;
	public Element subject3displayOrder22number12;
	public Element subject3displayOrder22number7;
	public Element subject3displayOrder22number11;
	public Element subject3displayOrder22number8;
	public Element subject3displayOrder22number10;
	public Element subject3displayOrder22number9;
	public Element InsuranceAmountFormSubject3Amount;
	public Element oDformerHealthInsuranceGeneralReward;
	public Element formerHealthInsuranceGeneralReward;
	public Element subject3displayOrder22number2;
	public Element subject3displayOrder22number3;
	public Element subject2displayOrder24number6;
	public Element subject2displayOrder23number6;
	public Element subject3displayOrder22amount3;
	public Element subject2displayOrder24number5;
	public Element subject2displayOrder23number7;
	public Element subject3displayOrder22amount4;
	public Element subject3displayOrder22amount5;
	public Element subject2displayOrder24number8;
	public Element subject2displayOrder23number4;
	public Element subject3displayOrder22amount6;
	public Element subject2displayOrder24number7;
	public Element subject2displayOrder23number5;
	public Element subject3displayOrder22amount7;
	public Element subject3displayOrder22amount8;
	public Element subject2displayOrder24number9;
	public Element subject3displayOrder22amount9;
	public Element subject2displayOrder23number8;
	public Element Cancel;
	public Element subject2displayOrder23number9;
	public Element name;
	public Element subject3displayOrder22totalNumber;
	public Element subject2displayOrder24number2;
	public Element subject2displayOrder23number2;
	public Element subject2displayOrder23number3;
	public Element subject2displayOrder24number4;
	public Element subject2displayOrder24number3;
	public Element subject3displayOrder22amount2;
	public Element calculateBasedData;
	public Element edit;
	public Element subject3displayOrder24amount;
	public Element olderUnemploymentBenefit;
	public Element oDHourlyAverageWorkingHours;
	public Element insuredOlderPersonTotalNumber;
	public Element insuredOlderPersonNumber;
	public Element subject2displayOrder24number12;
	public Element subject2displayOrder24number10;
	public Element subject2displayOrder24number11;
	public Element subject3displayOrder24amount12;
	public Element subject2displayOrder22amount;
	public Element subject3displayOrder24amount13;
	public Element oDcalculationStartDate;
	public Element subject3displayOrder24amount10;
	public Element occasionalDecision;
	public Element subject3displayOrder24amount11;
	public Element oDformerSocialSecurityGeneralReward;
	public Element averageAmount;
	public Element subject3displayOrder24number5;
	public Element subject3displayOrder24number4;
	public Element YES;
	public Element subject3displayOrder24number3;
	public Element subject3displayOrder24number2;
	public Element refundAmount3;
	public Element refundAmount2;
	public Element construction_2;
	public Element refundAmount1;
	public Element subject3displayOrder24amount15;
	public Element subject3displayOrder24amount14;
	public Element subject3displayOrder24number9;
	public Element construction_1;
	public Element subject3displayOrder24number8;
	public Element refundAmount5;
	public Element subject3displayOrder24number7;
	public Element refundAmount4;
	public Element subject3displayOrder24number6;
	public Element generalContributionsAmount;
	public Element subject2displayOrder23amount10;
	public Element subject2displayOrder23amount11;
	public Element subject2displayOrder23amount12;
	public Element subject2displayOrder23amount13;
	public Element subject2displayOrder23amount14;
	public Element subject2displayOrder23amount15;
	public Element Synchroinzation_syn;
	public Element employmentTotalNumber;
	public Element sumTotalAmount;
	public Element subject2displayOrder134amount;
	public Element subject3displayOrder23amount;
	public Element subject2displayOrder21amount;
	public Element appropriationAmount5;
	public Element appropriationAmount4;
	public Element NO;
	public Element subject2displayOrder21number12;
	public Element subject2displayOrder21number11;
	public Element OK;
	public Element subject2displayOrder21number10;
	public Element appropriationAmount2;
	public Element unemploymentTotalNumber;
	public Element appropriationAmount3;
	public Element appropriationAmount1;
	public Element InsuranceAmountFormSubject3TotalAmount;
	public Element subject2displayOrder21number;
	public Element InsuranceAmountFormSubject3TotalAmount5;
	public Element InsuranceAmountFormSubject3TotalAmount6;
	public Element InsuranceAmountFormSubject3TotalAmount3;
	public Element InsuranceAmountFormSubject3TotalAmount4;
	public Element workerAccidentInsurance;
	public Element EstimateAndDefiniteInsuranceAmountForm_1;
	public Element InsuranceAmountFormSubject3TotalAmount2;
	public Element EstimateAndDefiniteInsuranceAmountForm_2;
	public Element subject2displayOrder21amount10;
	public Element subject3displayOrder21amount9;
	public Element subject2displayOrder21amount11;
	public Element subject3displayOrder21amount8;
	public Element subject2displayOrder21amount12;
	public Element subject3displayOrder21amount7;
	public Element subject2displayOrder21amount13;
	public Element subject3displayOrder21amount6;
	public Element subject2displayOrder21amount14;
	public Element subject3displayOrder21amount5;
	public Element oDcalculationTime;
	public Element subject2displayOrder21amount15;
	public Element subject3displayOrder21amount4;
	public Element subject3displayOrder21amount3;
	public Element subject3displayOrder21amount2;
	public Element paymentDateDD;
	public Element HealthInsuranceGeneralReward;
	public Element subject2displayOrder132amount;
	public Element oDSocialSecurityGeneralReward;
	public Element subject3displayOrder22number;
	public Element save;
	public Element InsuranceAmountFormSubject4Rate;
	public Element ESC;
	public Element delayedPayment;
	public Element subject2displayOrder24number;
	public Element formerSocialSecurityGeneralReward;
	public Element subject3displayOrder22totalAmount;
	public Element subject3displayOrder21number2;
	public Element subject3displayOrder21number3;
	public Element subject3displayOrder21number4;
	public Element subject3displayOrder21number5;
	public Element subject3displayOrder21number6;
	public Element subject3displayOrder21number7;
	public Element subject3displayOrder21number8;
	public Element subject3displayOrder21number9;
	public Element subject2displayOrder23amount;
	public Element cancelSave;
	public Element appropriationIntent;
	public Element InsuranceAmountFormSubject4Amount;
	public Element subject3displayOrder24totalAmount;
	public Element SummarySheetCaption;
	public Element subject3displayOrder24totalNumber;
	public Element errorMessage;
	public Element InsuranceAmountFormSubject3Amount6;
	public Element InsuranceAmountFormSubject3Amount5;
	public Element subject3displayOrder21number;
	public Element oDHealthInsuranceGeneralReward;
	public Element empLogin;
	public Element subject3displayOrder24amount2;
	public Element oDaverageAmount;
	public Element subject3displayOrder24amount4;
	public Element subject3displayOrder24amount3;
	public Element subject3displayOrder24amount6;
	public Element subject2displayOrder23number12;
	public Element subject3displayOrder24amount5;
	public Element subject2displayOrder23number11;
	public Element subject3displayOrder24amount8;
	public Element subject3displayOrder24amount7;
	public Element subject3displayOrder24amount9;
	public Element subject2displayOrder23number10;
	public Element employmentNumber;
	public Element InsuranceAmountFormSubject4TotalAmount;
	public Element definition;
	public Element calculationDays3;
	public Element calculationDays2;
	public Element calculationDays1;
	public Element subject2displayOrder21amount6;
	public Element subject2displayOrder21amount5;
	public Element subject2displayOrder21amount8;
	public Element subject2displayOrder21amount7;
	public Element unemploymentInsuranceType_construction;
	public Element subject2displayOrder21amount2;
	public Element subject2displayOrder21amount4;
	public Element subject2displayOrder21amount3;
	public Element oDcalculationDays2;
	public Element oDcalculationDays1;
	public Element calculationMethod;
	public Element InsuranceAmountFormSubject4Rate5;
	public Element subject2displayOrder21amount9;
	public Element InsuranceAmountFormSubject4Rate2;
	public Element subject2displayOrder21number3;
	public Element subject2displayOrder21number2;
	public Element subject2displayOrder21number5;
	public Element subject2displayOrder21number4;
	public Element subject2displayOrder21number7;
	public Element InsuranceAmountFormSubject3Amount4;
	public Element subject2displayOrder21number6;
	public Element subject2displayOrder21number9;
	public Element oDcalculationDays3;
	public Element InsuranceAmountFormSubject3Amount2;
	public Element oDpaymentDateDD;
	public Element subject2displayOrder21number8;

    /*
     * @see com.asaas.test.util.Page#init(java.util.HashMap)
     */
    public void init(HashMap<String, Object> elements) {
        // Initialize variable
		this.subject2displayOrder22amount3 = (Element) elements.get("subject2displayOrder22amount3");
		this.subject2displayOrder22amount2 = (Element) elements.get("subject2displayOrder22amount2");
		this.subject2displayOrder22amount10 = (Element) elements.get("subject2displayOrder22amount10");
		this.subject2displayOrder22amount5 = (Element) elements.get("subject2displayOrder22amount5");
		this.subject2displayOrder22amount11 = (Element) elements.get("subject2displayOrder22amount11");
		this.subject3displayOrder22amount = (Element) elements.get("subject3displayOrder22amount");
		this.subject2displayOrder22amount4 = (Element) elements.get("subject2displayOrder22amount4");
		this.subject2displayOrder22amount12 = (Element) elements.get("subject2displayOrder22amount12");
		this.subject2displayOrder22amount7 = (Element) elements.get("subject2displayOrder22amount7");
		this.subject2displayOrder22amount13 = (Element) elements.get("subject2displayOrder22amount13");
		this.subject2displayOrder22amount6 = (Element) elements.get("subject2displayOrder22amount6");
		this.subject2displayOrder22amount14 = (Element) elements.get("subject2displayOrder22amount14");
		this.InsuranceAmountFormSubject3Rate6 = (Element) elements.get("InsuranceAmountFormSubject3Rate6");
		this.subject2displayOrder22amount9 = (Element) elements.get("subject2displayOrder22amount9");
		this.subject2displayOrder22amount15 = (Element) elements.get("subject2displayOrder22amount15");
		this.InsuranceAmountFormSubject3Rate5 = (Element) elements.get("InsuranceAmountFormSubject3Rate5");
		this.subject2displayOrder22amount8 = (Element) elements.get("subject2displayOrder22amount8");
		this.InsuranceAmountFormSubject3Rate4 = (Element) elements.get("InsuranceAmountFormSubject3Rate4");
		this.InsuranceAmountFormSubject3Rate2 = (Element) elements.get("InsuranceAmountFormSubject3Rate2");
		this.subject2displayOrder22number2 = (Element) elements.get("subject2displayOrder22number2");
		this.subject2displayOrder22number5 = (Element) elements.get("subject2displayOrder22number5");
		this.subject2displayOrder22number6 = (Element) elements.get("subject2displayOrder22number6");
		this.subject2displayOrder22number3 = (Element) elements.get("subject2displayOrder22number3");
		this.subject2displayOrder22number4 = (Element) elements.get("subject2displayOrder22number4");
		this.subject2displayOrder22number9 = (Element) elements.get("subject2displayOrder22number9");
		this.Synchroinzation = (Element) elements.get("Synchroinzation");
		this.subject2displayOrder22number7 = (Element) elements.get("subject2displayOrder22number7");
		this.subject2displayOrder22number8 = (Element) elements.get("subject2displayOrder22number8");
		this.subject3displayOrder21amount15 = (Element) elements.get("subject3displayOrder21amount15");
		this.subject3displayOrder21amount14 = (Element) elements.get("subject3displayOrder21amount14");
		this.subject3displayOrder21amount13 = (Element) elements.get("subject3displayOrder21amount13");
		this.subject3displayOrder21amount12 = (Element) elements.get("subject3displayOrder21amount12");
		this.subject3displayOrder21amount11 = (Element) elements.get("subject3displayOrder21amount11");
		this.subject3displayOrder21amount10 = (Element) elements.get("subject3displayOrder21amount10");
		this.diffUnemploymentBenefit = (Element) elements.get("diffUnemploymentBenefit");
		this.subject2displayOrder131amount = (Element) elements.get("subject2displayOrder131amount");
		this.InsuranceAmountForm = (Element) elements.get("InsuranceAmountForm");
		this.subject2displayOrder23amount2 = (Element) elements.get("subject2displayOrder23amount2");
		this.exceptionFlag = (Element) elements.get("exceptionFlag");
		this.generalAppropriationAmount3 = (Element) elements.get("generalAppropriationAmount3");
		this.subject2displayOrder23amount9 = (Element) elements.get("subject2displayOrder23amount9");
		this.subject2displayOrder23amount7 = (Element) elements.get("subject2displayOrder23amount7");
		this.subject2displayOrder23amount8 = (Element) elements.get("subject2displayOrder23amount8");
		this.subject2displayOrder23amount5 = (Element) elements.get("subject2displayOrder23amount5");
		this.subject2displayOrder23amount6 = (Element) elements.get("subject2displayOrder23amount6");
		this.subject2displayOrder23amount3 = (Element) elements.get("subject2displayOrder23amount3");
		this.employeeName = (Element) elements.get("employeeName");
		this.subject2displayOrder23amount4 = (Element) elements.get("subject2displayOrder23amount4");
		this.subject2displayOrder22number11 = (Element) elements.get("subject2displayOrder22number11");
		this.subject2displayOrder22number10 = (Element) elements.get("subject2displayOrder22number10");
		this.unemploymentInsuranceType_other = (Element) elements.get("unemploymentInsuranceType_other");
		this.InsuranceAmountFormSubject4TotalAmount3 = (Element) elements.get("InsuranceAmountFormSubject4TotalAmount3");
		this.ordinaryDecision = (Element) elements.get("ordinaryDecision");
		this.InsuranceAmountFormSubject4TotalAmount2 = (Element) elements.get("InsuranceAmountFormSubject4TotalAmount2");
		this.InsuranceAmountFormSubject4TotalAmount5 = (Element) elements.get("InsuranceAmountFormSubject4TotalAmount5");
		this.unemploymentNumber = (Element) elements.get("unemploymentNumber");
		this.InsuranceAmountFormSubject4TotalAmount4 = (Element) elements.get("InsuranceAmountFormSubject4TotalAmount4");
		this.subject2displayOrder22number12 = (Element) elements.get("subject2displayOrder22number12");
		this.InsuranceAmountFormCaption = (Element) elements.get("InsuranceAmountFormCaption");
		this.InsuranceAmountFormSubject3Rate = (Element) elements.get("InsuranceAmountFormSubject3Rate");
		this.calculationStartDate = (Element) elements.get("calculationStartDate");
		this.subject2displayOrder23number = (Element) elements.get("subject2displayOrder23number");
		this.oDEmployeeName = (Element) elements.get("oDEmployeeName");
		this.subject3displayOrder22amount13 = (Element) elements.get("subject3displayOrder22amount13");
		this.subject3displayOrder22amount12 = (Element) elements.get("subject3displayOrder22amount12");
		this.subject2displayOrder24amount = (Element) elements.get("subject2displayOrder24amount");
		this.subject3displayOrder22amount15 = (Element) elements.get("subject3displayOrder22amount15");
		this.subject3displayOrder22amount14 = (Element) elements.get("subject3displayOrder22amount14");
		this.SocialSecurityGeneralReward = (Element) elements.get("SocialSecurityGeneralReward");
		this.subject3displayOrder22amount11 = (Element) elements.get("subject3displayOrder22amount11");
		this.subject3displayOrder22amount10 = (Element) elements.get("subject3displayOrder22amount10");
		this.popup_ordinary_caption = (Element) elements.get("popup_ordinary_caption");
		this.subject3displayOrder21amount = (Element) elements.get("subject3displayOrder21amount");
		this.subject2displayOrder23totalAmount = (Element) elements.get("subject2displayOrder23totalAmount");
		this.unemploymentBenefit = (Element) elements.get("unemploymentBenefit");
		this.oDCaption = (Element) elements.get("oDCaption");
		this.oDpaymentDateDD3 = (Element) elements.get("oDpaymentDateDD3");
		this.oDpaymentDateDD2 = (Element) elements.get("oDpaymentDateDD2");
		this.close = (Element) elements.get("close");
		this.subject3displayOrder24number10 = (Element) elements.get("subject3displayOrder24number10");
		this.oDsumTotalAmount = (Element) elements.get("oDsumTotalAmount");
		this.subject3displayOrder24number12 = (Element) elements.get("subject3displayOrder24number12");
		this.subject3displayOrder24number11 = (Element) elements.get("subject3displayOrder24number11");
		this.subject3displayOrder21number12 = (Element) elements.get("subject3displayOrder21number12");
		this.login = (Element) elements.get("login");
		this.subject3displayOrder21number10 = (Element) elements.get("subject3displayOrder21number10");
		this.subject3displayOrder21number11 = (Element) elements.get("subject3displayOrder21number11");
		this.unemploymentInsuranceType_general = (Element) elements.get("unemploymentInsuranceType_general");
		this.subject3displayOrder24number = (Element) elements.get("subject3displayOrder24number");
		this.subject2displayOrder133amount = (Element) elements.get("subject2displayOrder133amount");
		this.HourlyAverageWorkingHours = (Element) elements.get("HourlyAverageWorkingHours");
		this.InsuranceAmountFormSubject4Amount5 = (Element) elements.get("InsuranceAmountFormSubject4Amount5");
		this.InsuranceAmountFormSubject4Amount2 = (Element) elements.get("InsuranceAmountFormSubject4Amount2");
		this.BaseAmountPayrollSummarySheet = (Element) elements.get("BaseAmountPayrollSummarySheet");
		this.deficitAmount5 = (Element) elements.get("deficitAmount5");
		this.deficitAmount4 = (Element) elements.get("deficitAmount4");
		this.deficitAmount3 = (Element) elements.get("deficitAmount3");
		this.deficitAmount2 = (Element) elements.get("deficitAmount2");
		this.estimatedInsuranceAmount = (Element) elements.get("estimatedInsuranceAmount");
		this.deficitAmount1 = (Element) elements.get("deficitAmount1");
		this.subject2displayOrder22number = (Element) elements.get("subject2displayOrder22number");
		this.ordinaryDecisionCaption = (Element) elements.get("ordinaryDecisionCaption");
		this.oDfixedAverageAmount = (Element) elements.get("oDfixedAverageAmount");
		this.paymentDateDD3 = (Element) elements.get("paymentDateDD3");
		this.paymentDateDD2 = (Element) elements.get("paymentDateDD2");
		this.subject3displayOrder22number4 = (Element) elements.get("subject3displayOrder22number4");
		this.subject2displayOrder24totalNumber = (Element) elements.get("subject2displayOrder24totalNumber");
		this.subject3displayOrder22number5 = (Element) elements.get("subject3displayOrder22number5");
		this.subject3displayOrder22number6 = (Element) elements.get("subject3displayOrder22number6");
		this.subject3displayOrder22number12 = (Element) elements.get("subject3displayOrder22number12");
		this.subject3displayOrder22number7 = (Element) elements.get("subject3displayOrder22number7");
		this.subject3displayOrder22number11 = (Element) elements.get("subject3displayOrder22number11");
		this.subject3displayOrder22number8 = (Element) elements.get("subject3displayOrder22number8");
		this.subject3displayOrder22number10 = (Element) elements.get("subject3displayOrder22number10");
		this.subject3displayOrder22number9 = (Element) elements.get("subject3displayOrder22number9");
		this.InsuranceAmountFormSubject3Amount = (Element) elements.get("InsuranceAmountFormSubject3Amount");
		this.oDformerHealthInsuranceGeneralReward = (Element) elements.get("oDformerHealthInsuranceGeneralReward");
		this.formerHealthInsuranceGeneralReward = (Element) elements.get("formerHealthInsuranceGeneralReward");
		this.subject3displayOrder22number2 = (Element) elements.get("subject3displayOrder22number2");
		this.subject3displayOrder22number3 = (Element) elements.get("subject3displayOrder22number3");
		this.subject2displayOrder24number6 = (Element) elements.get("subject2displayOrder24number6");
		this.subject2displayOrder23number6 = (Element) elements.get("subject2displayOrder23number6");
		this.subject3displayOrder22amount3 = (Element) elements.get("subject3displayOrder22amount3");
		this.subject2displayOrder24number5 = (Element) elements.get("subject2displayOrder24number5");
		this.subject2displayOrder23number7 = (Element) elements.get("subject2displayOrder23number7");
		this.subject3displayOrder22amount4 = (Element) elements.get("subject3displayOrder22amount4");
		this.subject3displayOrder22amount5 = (Element) elements.get("subject3displayOrder22amount5");
		this.subject2displayOrder24number8 = (Element) elements.get("subject2displayOrder24number8");
		this.subject2displayOrder23number4 = (Element) elements.get("subject2displayOrder23number4");
		this.subject3displayOrder22amount6 = (Element) elements.get("subject3displayOrder22amount6");
		this.subject2displayOrder24number7 = (Element) elements.get("subject2displayOrder24number7");
		this.subject2displayOrder23number5 = (Element) elements.get("subject2displayOrder23number5");
		this.subject3displayOrder22amount7 = (Element) elements.get("subject3displayOrder22amount7");
		this.subject3displayOrder22amount8 = (Element) elements.get("subject3displayOrder22amount8");
		this.subject2displayOrder24number9 = (Element) elements.get("subject2displayOrder24number9");
		this.subject3displayOrder22amount9 = (Element) elements.get("subject3displayOrder22amount9");
		this.subject2displayOrder23number8 = (Element) elements.get("subject2displayOrder23number8");
		this.Cancel = (Element) elements.get("Cancel");
		this.subject2displayOrder23number9 = (Element) elements.get("subject2displayOrder23number9");
		this.name = (Element) elements.get("name");
		this.subject3displayOrder22totalNumber = (Element) elements.get("subject3displayOrder22totalNumber");
		this.subject2displayOrder24number2 = (Element) elements.get("subject2displayOrder24number2");
		this.subject2displayOrder23number2 = (Element) elements.get("subject2displayOrder23number2");
		this.subject2displayOrder23number3 = (Element) elements.get("subject2displayOrder23number3");
		this.subject2displayOrder24number4 = (Element) elements.get("subject2displayOrder24number4");
		this.subject2displayOrder24number3 = (Element) elements.get("subject2displayOrder24number3");
		this.subject3displayOrder22amount2 = (Element) elements.get("subject3displayOrder22amount2");
		this.calculateBasedData = (Element) elements.get("calculateBasedData");
		this.edit = (Element) elements.get("edit");
		this.subject3displayOrder24amount = (Element) elements.get("subject3displayOrder24amount");
		this.olderUnemploymentBenefit = (Element) elements.get("olderUnemploymentBenefit");
		this.oDHourlyAverageWorkingHours = (Element) elements.get("oDHourlyAverageWorkingHours");
		this.insuredOlderPersonTotalNumber = (Element) elements.get("insuredOlderPersonTotalNumber");
		this.insuredOlderPersonNumber = (Element) elements.get("insuredOlderPersonNumber");
		this.subject2displayOrder24number12 = (Element) elements.get("subject2displayOrder24number12");
		this.subject2displayOrder24number10 = (Element) elements.get("subject2displayOrder24number10");
		this.subject2displayOrder24number11 = (Element) elements.get("subject2displayOrder24number11");
		this.subject3displayOrder24amount12 = (Element) elements.get("subject3displayOrder24amount12");
		this.subject2displayOrder22amount = (Element) elements.get("subject2displayOrder22amount");
		this.subject3displayOrder24amount13 = (Element) elements.get("subject3displayOrder24amount13");
		this.oDcalculationStartDate = (Element) elements.get("oDcalculationStartDate");
		this.subject3displayOrder24amount10 = (Element) elements.get("subject3displayOrder24amount10");
		this.occasionalDecision = (Element) elements.get("occasionalDecision");
		this.subject3displayOrder24amount11 = (Element) elements.get("subject3displayOrder24amount11");
		this.oDformerSocialSecurityGeneralReward = (Element) elements.get("oDformerSocialSecurityGeneralReward");
		this.averageAmount = (Element) elements.get("averageAmount");
		this.subject3displayOrder24number5 = (Element) elements.get("subject3displayOrder24number5");
		this.subject3displayOrder24number4 = (Element) elements.get("subject3displayOrder24number4");
		this.YES = (Element) elements.get("YES");
		this.subject3displayOrder24number3 = (Element) elements.get("subject3displayOrder24number3");
		this.subject3displayOrder24number2 = (Element) elements.get("subject3displayOrder24number2");
		this.refundAmount3 = (Element) elements.get("refundAmount3");
		this.refundAmount2 = (Element) elements.get("refundAmount2");
		this.construction_2 = (Element) elements.get("construction_2");
		this.refundAmount1 = (Element) elements.get("refundAmount1");
		this.subject3displayOrder24amount15 = (Element) elements.get("subject3displayOrder24amount15");
		this.subject3displayOrder24amount14 = (Element) elements.get("subject3displayOrder24amount14");
		this.subject3displayOrder24number9 = (Element) elements.get("subject3displayOrder24number9");
		this.construction_1 = (Element) elements.get("construction_1");
		this.subject3displayOrder24number8 = (Element) elements.get("subject3displayOrder24number8");
		this.refundAmount5 = (Element) elements.get("refundAmount5");
		this.subject3displayOrder24number7 = (Element) elements.get("subject3displayOrder24number7");
		this.refundAmount4 = (Element) elements.get("refundAmount4");
		this.subject3displayOrder24number6 = (Element) elements.get("subject3displayOrder24number6");
		this.generalContributionsAmount = (Element) elements.get("generalContributionsAmount");
		this.subject2displayOrder23amount10 = (Element) elements.get("subject2displayOrder23amount10");
		this.subject2displayOrder23amount11 = (Element) elements.get("subject2displayOrder23amount11");
		this.subject2displayOrder23amount12 = (Element) elements.get("subject2displayOrder23amount12");
		this.subject2displayOrder23amount13 = (Element) elements.get("subject2displayOrder23amount13");
		this.subject2displayOrder23amount14 = (Element) elements.get("subject2displayOrder23amount14");
		this.subject2displayOrder23amount15 = (Element) elements.get("subject2displayOrder23amount15");
		this.Synchroinzation_syn = (Element) elements.get("Synchroinzation_syn");
		this.employmentTotalNumber = (Element) elements.get("employmentTotalNumber");
		this.sumTotalAmount = (Element) elements.get("sumTotalAmount");
		this.subject2displayOrder134amount = (Element) elements.get("subject2displayOrder134amount");
		this.subject3displayOrder23amount = (Element) elements.get("subject3displayOrder23amount");
		this.subject2displayOrder21amount = (Element) elements.get("subject2displayOrder21amount");
		this.appropriationAmount5 = (Element) elements.get("appropriationAmount5");
		this.appropriationAmount4 = (Element) elements.get("appropriationAmount4");
		this.NO = (Element) elements.get("NO");
		this.subject2displayOrder21number12 = (Element) elements.get("subject2displayOrder21number12");
		this.subject2displayOrder21number11 = (Element) elements.get("subject2displayOrder21number11");
		this.OK = (Element) elements.get("OK");
		this.subject2displayOrder21number10 = (Element) elements.get("subject2displayOrder21number10");
		this.appropriationAmount2 = (Element) elements.get("appropriationAmount2");
		this.unemploymentTotalNumber = (Element) elements.get("unemploymentTotalNumber");
		this.appropriationAmount3 = (Element) elements.get("appropriationAmount3");
		this.appropriationAmount1 = (Element) elements.get("appropriationAmount1");
		this.InsuranceAmountFormSubject3TotalAmount = (Element) elements.get("InsuranceAmountFormSubject3TotalAmount");
		this.subject2displayOrder21number = (Element) elements.get("subject2displayOrder21number");
		this.InsuranceAmountFormSubject3TotalAmount5 = (Element) elements.get("InsuranceAmountFormSubject3TotalAmount5");
		this.InsuranceAmountFormSubject3TotalAmount6 = (Element) elements.get("InsuranceAmountFormSubject3TotalAmount6");
		this.InsuranceAmountFormSubject3TotalAmount3 = (Element) elements.get("InsuranceAmountFormSubject3TotalAmount3");
		this.InsuranceAmountFormSubject3TotalAmount4 = (Element) elements.get("InsuranceAmountFormSubject3TotalAmount4");
		this.workerAccidentInsurance = (Element) elements.get("workerAccidentInsurance");
		this.EstimateAndDefiniteInsuranceAmountForm_1 = (Element) elements.get("EstimateAndDefiniteInsuranceAmountForm_1");
		this.InsuranceAmountFormSubject3TotalAmount2 = (Element) elements.get("InsuranceAmountFormSubject3TotalAmount2");
		this.EstimateAndDefiniteInsuranceAmountForm_2 = (Element) elements.get("EstimateAndDefiniteInsuranceAmountForm_2");
		this.subject2displayOrder21amount10 = (Element) elements.get("subject2displayOrder21amount10");
		this.subject3displayOrder21amount9 = (Element) elements.get("subject3displayOrder21amount9");
		this.subject2displayOrder21amount11 = (Element) elements.get("subject2displayOrder21amount11");
		this.subject3displayOrder21amount8 = (Element) elements.get("subject3displayOrder21amount8");
		this.subject2displayOrder21amount12 = (Element) elements.get("subject2displayOrder21amount12");
		this.subject3displayOrder21amount7 = (Element) elements.get("subject3displayOrder21amount7");
		this.subject2displayOrder21amount13 = (Element) elements.get("subject2displayOrder21amount13");
		this.subject3displayOrder21amount6 = (Element) elements.get("subject3displayOrder21amount6");
		this.subject2displayOrder21amount14 = (Element) elements.get("subject2displayOrder21amount14");
		this.subject3displayOrder21amount5 = (Element) elements.get("subject3displayOrder21amount5");
		this.oDcalculationTime = (Element) elements.get("oDcalculationTime");
		this.subject2displayOrder21amount15 = (Element) elements.get("subject2displayOrder21amount15");
		this.subject3displayOrder21amount4 = (Element) elements.get("subject3displayOrder21amount4");
		this.subject3displayOrder21amount3 = (Element) elements.get("subject3displayOrder21amount3");
		this.subject3displayOrder21amount2 = (Element) elements.get("subject3displayOrder21amount2");
		this.paymentDateDD = (Element) elements.get("paymentDateDD");
		this.HealthInsuranceGeneralReward = (Element) elements.get("HealthInsuranceGeneralReward");
		this.subject2displayOrder132amount = (Element) elements.get("subject2displayOrder132amount");
		this.oDSocialSecurityGeneralReward = (Element) elements.get("oDSocialSecurityGeneralReward");
		this.subject3displayOrder22number = (Element) elements.get("subject3displayOrder22number");
		this.save = (Element) elements.get("save");
		this.InsuranceAmountFormSubject4Rate = (Element) elements.get("InsuranceAmountFormSubject4Rate");
		this.ESC = (Element) elements.get("ESC");
		this.delayedPayment = (Element) elements.get("delayedPayment");
		this.subject2displayOrder24number = (Element) elements.get("subject2displayOrder24number");
		this.formerSocialSecurityGeneralReward = (Element) elements.get("formerSocialSecurityGeneralReward");
		this.subject3displayOrder22totalAmount = (Element) elements.get("subject3displayOrder22totalAmount");
		this.subject3displayOrder21number2 = (Element) elements.get("subject3displayOrder21number2");
		this.subject3displayOrder21number3 = (Element) elements.get("subject3displayOrder21number3");
		this.subject3displayOrder21number4 = (Element) elements.get("subject3displayOrder21number4");
		this.subject3displayOrder21number5 = (Element) elements.get("subject3displayOrder21number5");
		this.subject3displayOrder21number6 = (Element) elements.get("subject3displayOrder21number6");
		this.subject3displayOrder21number7 = (Element) elements.get("subject3displayOrder21number7");
		this.subject3displayOrder21number8 = (Element) elements.get("subject3displayOrder21number8");
		this.subject3displayOrder21number9 = (Element) elements.get("subject3displayOrder21number9");
		this.subject2displayOrder23amount = (Element) elements.get("subject2displayOrder23amount");
		this.cancelSave = (Element) elements.get("cancelSave");
		this.appropriationIntent = (Element) elements.get("appropriationIntent");
		this.InsuranceAmountFormSubject4Amount = (Element) elements.get("InsuranceAmountFormSubject4Amount");
		this.subject3displayOrder24totalAmount = (Element) elements.get("subject3displayOrder24totalAmount");
		this.SummarySheetCaption = (Element) elements.get("SummarySheetCaption");
		this.subject3displayOrder24totalNumber = (Element) elements.get("subject3displayOrder24totalNumber");
		this.errorMessage = (Element) elements.get("errorMessage");
		this.InsuranceAmountFormSubject3Amount6 = (Element) elements.get("InsuranceAmountFormSubject3Amount6");
		this.InsuranceAmountFormSubject3Amount5 = (Element) elements.get("InsuranceAmountFormSubject3Amount5");
		this.subject3displayOrder21number = (Element) elements.get("subject3displayOrder21number");
		this.oDHealthInsuranceGeneralReward = (Element) elements.get("oDHealthInsuranceGeneralReward");
		this.empLogin = (Element) elements.get("empLogin");
		this.subject3displayOrder24amount2 = (Element) elements.get("subject3displayOrder24amount2");
		this.oDaverageAmount = (Element) elements.get("oDaverageAmount");
		this.subject3displayOrder24amount4 = (Element) elements.get("subject3displayOrder24amount4");
		this.subject3displayOrder24amount3 = (Element) elements.get("subject3displayOrder24amount3");
		this.subject3displayOrder24amount6 = (Element) elements.get("subject3displayOrder24amount6");
		this.subject2displayOrder23number12 = (Element) elements.get("subject2displayOrder23number12");
		this.subject3displayOrder24amount5 = (Element) elements.get("subject3displayOrder24amount5");
		this.subject2displayOrder23number11 = (Element) elements.get("subject2displayOrder23number11");
		this.subject3displayOrder24amount8 = (Element) elements.get("subject3displayOrder24amount8");
		this.subject3displayOrder24amount7 = (Element) elements.get("subject3displayOrder24amount7");
		this.subject3displayOrder24amount9 = (Element) elements.get("subject3displayOrder24amount9");
		this.subject2displayOrder23number10 = (Element) elements.get("subject2displayOrder23number10");
		this.employmentNumber = (Element) elements.get("employmentNumber");
		this.InsuranceAmountFormSubject4TotalAmount = (Element) elements.get("InsuranceAmountFormSubject4TotalAmount");
		this.definition = (Element) elements.get("definition");
		this.calculationDays3 = (Element) elements.get("calculationDays3");
		this.calculationDays2 = (Element) elements.get("calculationDays2");
		this.calculationDays1 = (Element) elements.get("calculationDays1");
		this.subject2displayOrder21amount6 = (Element) elements.get("subject2displayOrder21amount6");
		this.subject2displayOrder21amount5 = (Element) elements.get("subject2displayOrder21amount5");
		this.subject2displayOrder21amount8 = (Element) elements.get("subject2displayOrder21amount8");
		this.subject2displayOrder21amount7 = (Element) elements.get("subject2displayOrder21amount7");
		this.unemploymentInsuranceType_construction = (Element) elements.get("unemploymentInsuranceType_construction");
		this.subject2displayOrder21amount2 = (Element) elements.get("subject2displayOrder21amount2");
		this.subject2displayOrder21amount4 = (Element) elements.get("subject2displayOrder21amount4");
		this.subject2displayOrder21amount3 = (Element) elements.get("subject2displayOrder21amount3");
		this.oDcalculationDays2 = (Element) elements.get("oDcalculationDays2");
		this.oDcalculationDays1 = (Element) elements.get("oDcalculationDays1");
		this.calculationMethod = (Element) elements.get("calculationMethod");
		this.InsuranceAmountFormSubject4Rate5 = (Element) elements.get("InsuranceAmountFormSubject4Rate5");
		this.subject2displayOrder21amount9 = (Element) elements.get("subject2displayOrder21amount9");
		this.InsuranceAmountFormSubject4Rate2 = (Element) elements.get("InsuranceAmountFormSubject4Rate2");
		this.subject2displayOrder21number3 = (Element) elements.get("subject2displayOrder21number3");
		this.subject2displayOrder21number2 = (Element) elements.get("subject2displayOrder21number2");
		this.subject2displayOrder21number5 = (Element) elements.get("subject2displayOrder21number5");
		this.subject2displayOrder21number4 = (Element) elements.get("subject2displayOrder21number4");
		this.subject2displayOrder21number7 = (Element) elements.get("subject2displayOrder21number7");
		this.InsuranceAmountFormSubject3Amount4 = (Element) elements.get("InsuranceAmountFormSubject3Amount4");
		this.subject2displayOrder21number6 = (Element) elements.get("subject2displayOrder21number6");
		this.subject2displayOrder21number9 = (Element) elements.get("subject2displayOrder21number9");
		this.oDcalculationDays3 = (Element) elements.get("oDcalculationDays3");
		this.InsuranceAmountFormSubject3Amount2 = (Element) elements.get("InsuranceAmountFormSubject3Amount2");
		this.oDpaymentDateDD = (Element) elements.get("oDpaymentDateDD");
		this.subject2displayOrder21number8 = (Element) elements.get("subject2displayOrder21number8");
	}
}
