/**
 * 
 */
package com.asaas.test.util;

import java.util.HashMap;

/**
 * @author
 * 
 */
public class TopPage implements Page {
    // Declare variable
	public Element payrollDataTwo;
	public Element clientsList_Client_second;
	public Element returnDashboard;
	public Element popup_Asset_Account_SetName;
	public Element clientsList_Client_first;
	public Element popup_Asset_AddAccountData_Indiv;
	public Element popup_Asset_AddAccountData;
	public Element popup_Acount_AddClientData;
	public Element employeeReg;
	public Element ListForCounsel;
	public Element popup_Payroll_AddPayroll;
	public Element popup_Acount_Client_Cancel;
	public Element bonusCalc;
	public Element projectID;
	public Element Statements;
	public Element popup_ClientSetCode;
	public Element clientsList_Client_AddData_ConsumptionTax;
	public Element popup_Acount_Client_depManageBasicInfoTitle;
	public Element dep_Dep;
	public Element popup_Asset_Account_Cancel;
	public Element popup_Asset_status;
	public Element employeeInformation;
	public Element popup_Asset_Cancel;
	public Element popupOK;
	public Element popup_Acount_SetCode;
	public Element adviserList;
	public Element popup_Asset_name;
	public Element clientsList_AddClient;
	public Element serviceList;
	public Element clientsList_Client_AddData_CorporateTax;
	public Element popup_Asset_Account_name2;
	public Element popup_Acount_Client_Ok;
	public Element payrollPeriodOne;
	public Element clientsList_AssetData_Button;
	public Element popup_Payroll_SetName;
	public Element businessDepreciation_dis;
	public Element popup_Asset_list2_inside;
	public Element addMore;
	public Element popup_Asset_endindDate;
	public Element popup_ClientSetName;
	public Element clientsList_Client_AddData_Asset;
	public Element popup_Acount_Cancel;
	public Element clientsList;
	public Element popupCancel;
	public Element clientsList_Client_AddData_ConsumptionTax_FR;
	public Element clientList_AssetData_AssetBase;
	public Element pendingProgressBar;
	public Element clientsList_AssetData_AssetAccountSetting;
	public Element companyReg;
	public Element menuList;
	public Element clientsList_Client_laseAccessDare;
	public Element popup_Asset_endindDate_title;
	public Element clientsList_Client_AddData_CorporateTax_FR;
	public Element popup_Asset_list1;
	public Element popup_Payroll_Client_SetName;
	public Element popup_Asset_list3;
	public Element popup_Asset_list2;
	public Element popup_Asset_Account_Ok;
	public Element popup_Payroll_Client_Ok;
	public Element popup_Asset_SetName;
	public Element popup_Acount_Client_SetCode;
	public Element popup_Asset_Account_depManageBasicInfoTitle;
	public Element payrollPeriodTwo;
	public Element bonusCalculate;
	public Element popup_Asset_name2;
	public Element popup_Payroll_Client_SetCode;
	public Element payrollCalc;
	public Element popup_Asset_DataList;
	public Element popup_Asset_endDate;
	public Element payrollService;
	public Element popup_Acount_Ok;
	public Element corporateAdvisor;
	public Element clientsList_Client_AddData_CorporateTax_AR;
	public Element popup_Acount_DataList;
	public Element popup_Acount_SetName;
	public Element popup_Payroll_Cancel;
	public Element personalAdvisor;
	public Element dep_BasicInfo;
	public Element popup_Asset_AddAccountData_Comp;
	public Element popup_Asset_accountBasicInfoTitle;
	public Element clientsList_Client_Title;
	public Element popup_Acount_accountBasicInfoTitle;
	public Element popup_title;
	public Element clientsList_Client_AddData_Payroll;
	public Element clientsList_Code;
	public Element clientsList_Client_deatilList;
	public Element clientsList_Client_AddData_ConsumptionTax_AR;
	public Element clientsList_Client_AddData;
	public Element dep_Assets;
	public Element popup_Asset_endDate2;
	public Element popup_Payroll_SetCode;
	public Element clientsList_Client_AddData_ConsumptionTax_IR;
	public Element businessList;
	public Element employeeInformationRegistered;
	public Element popup_Acount_Client_SetName;
	public Element popup_Asset_list1_inside;
	public Element popup_Asset_Ok;
	public Element clientsList_Client_AddData_CorporateTax_IR;
	public Element clientsList_Client_AddData_ConsumptionTax_IAR;
	public Element popup_Asset_Account_name;
	public Element advisorService;
	public Element popup_Payroll_Client_Cancel;
	public Element dep_Location;
	public Element adviserReg;
	public Element popUp;
	public Element adviserList_AddMore;
	public Element dep_AssetsItem;
	public Element payrollDataOne;
	public Element name;
	public Element popup_Asset_Account_SetCode;
	public Element clientsList_Client_AddData_Account;
	public Element clientsList_Client_AddData_TaxProxy;
	public Element popup_Payroll_Ok;
	public Element popup_Asset_Account_endingDate;
	public Element adviserList_AddIndividual;
	public Element annualAdjustment;
	public Element annualAdj;
	public Element popup_Asset_SetCode;
	public Element businessDepreciation;
	public Element popup_Asset_Account_endingDate2;

    /*
     * @see com.asaas.test.util.Page#init(java.util.HashMap)
     */
    public void init(HashMap<String, Object> elements) {
        // Initialize variable
		this.payrollDataTwo = (Element) elements.get("payrollDataTwo");
		this.clientsList_Client_second = (Element) elements.get("clientsList_Client_second");
		this.returnDashboard = (Element) elements.get("returnDashboard");
		this.popup_Asset_Account_SetName = (Element) elements.get("popup_Asset_Account_SetName");
		this.clientsList_Client_first = (Element) elements.get("clientsList_Client_first");
		this.popup_Asset_AddAccountData_Indiv = (Element) elements.get("popup_Asset_AddAccountData_Indiv");
		this.popup_Asset_AddAccountData = (Element) elements.get("popup_Asset_AddAccountData");
		this.popup_Acount_AddClientData = (Element) elements.get("popup_Acount_AddClientData");
		this.employeeReg = (Element) elements.get("employeeReg");
		this.ListForCounsel = (Element) elements.get("ListForCounsel");
		this.popup_Payroll_AddPayroll = (Element) elements.get("popup_Payroll_AddPayroll");
		this.popup_Acount_Client_Cancel = (Element) elements.get("popup_Acount_Client_Cancel");
		this.bonusCalc = (Element) elements.get("bonusCalc");
		this.projectID = (Element) elements.get("projectID");
		this.Statements = (Element) elements.get("Statements");
		this.popup_ClientSetCode = (Element) elements.get("popup_ClientSetCode");
		this.clientsList_Client_AddData_ConsumptionTax = (Element) elements.get("clientsList_Client_AddData_ConsumptionTax");
		this.popup_Acount_Client_depManageBasicInfoTitle = (Element) elements.get("popup_Acount_Client_depManageBasicInfoTitle");
		this.dep_Dep = (Element) elements.get("dep_Dep");
		this.popup_Asset_Account_Cancel = (Element) elements.get("popup_Asset_Account_Cancel");
		this.popup_Asset_status = (Element) elements.get("popup_Asset_status");
		this.employeeInformation = (Element) elements.get("employeeInformation");
		this.popup_Asset_Cancel = (Element) elements.get("popup_Asset_Cancel");
		this.popupOK = (Element) elements.get("popupOK");
		this.popup_Acount_SetCode = (Element) elements.get("popup_Acount_SetCode");
		this.adviserList = (Element) elements.get("adviserList");
		this.popup_Asset_name = (Element) elements.get("popup_Asset_name");
		this.clientsList_AddClient = (Element) elements.get("clientsList_AddClient");
		this.serviceList = (Element) elements.get("serviceList");
		this.clientsList_Client_AddData_CorporateTax = (Element) elements.get("clientsList_Client_AddData_CorporateTax");
		this.popup_Asset_Account_name2 = (Element) elements.get("popup_Asset_Account_name2");
		this.popup_Acount_Client_Ok = (Element) elements.get("popup_Acount_Client_Ok");
		this.payrollPeriodOne = (Element) elements.get("payrollPeriodOne");
		this.clientsList_AssetData_Button = (Element) elements.get("clientsList_AssetData_Button");
		this.popup_Payroll_SetName = (Element) elements.get("popup_Payroll_SetName");
		this.businessDepreciation_dis = (Element) elements.get("businessDepreciation_dis");
		this.popup_Asset_list2_inside = (Element) elements.get("popup_Asset_list2_inside");
		this.addMore = (Element) elements.get("addMore");
		this.popup_Asset_endindDate = (Element) elements.get("popup_Asset_endindDate");
		this.popup_ClientSetName = (Element) elements.get("popup_ClientSetName");
		this.clientsList_Client_AddData_Asset = (Element) elements.get("clientsList_Client_AddData_Asset");
		this.popup_Acount_Cancel = (Element) elements.get("popup_Acount_Cancel");
		this.clientsList = (Element) elements.get("clientsList");
		this.popupCancel = (Element) elements.get("popupCancel");
		this.clientsList_Client_AddData_ConsumptionTax_FR = (Element) elements.get("clientsList_Client_AddData_ConsumptionTax_FR");
		this.clientList_AssetData_AssetBase = (Element) elements.get("clientList_AssetData_AssetBase");
		this.pendingProgressBar = (Element) elements.get("pendingProgressBar");
		this.clientsList_AssetData_AssetAccountSetting = (Element) elements.get("clientsList_AssetData_AssetAccountSetting");
		this.companyReg = (Element) elements.get("companyReg");
		this.menuList = (Element) elements.get("menuList");
		this.clientsList_Client_laseAccessDare = (Element) elements.get("clientsList_Client_laseAccessDare");
		this.popup_Asset_endindDate_title = (Element) elements.get("popup_Asset_endindDate_title");
		this.clientsList_Client_AddData_CorporateTax_FR = (Element) elements.get("clientsList_Client_AddData_CorporateTax_FR");
		this.popup_Asset_list1 = (Element) elements.get("popup_Asset_list1");
		this.popup_Payroll_Client_SetName = (Element) elements.get("popup_Payroll_Client_SetName");
		this.popup_Asset_list3 = (Element) elements.get("popup_Asset_list3");
		this.popup_Asset_list2 = (Element) elements.get("popup_Asset_list2");
		this.popup_Asset_Account_Ok = (Element) elements.get("popup_Asset_Account_Ok");
		this.popup_Payroll_Client_Ok = (Element) elements.get("popup_Payroll_Client_Ok");
		this.popup_Asset_SetName = (Element) elements.get("popup_Asset_SetName");
		this.popup_Acount_Client_SetCode = (Element) elements.get("popup_Acount_Client_SetCode");
		this.popup_Asset_Account_depManageBasicInfoTitle = (Element) elements.get("popup_Asset_Account_depManageBasicInfoTitle");
		this.payrollPeriodTwo = (Element) elements.get("payrollPeriodTwo");
		this.bonusCalculate = (Element) elements.get("bonusCalculate");
		this.popup_Asset_name2 = (Element) elements.get("popup_Asset_name2");
		this.popup_Payroll_Client_SetCode = (Element) elements.get("popup_Payroll_Client_SetCode");
		this.payrollCalc = (Element) elements.get("payrollCalc");
		this.popup_Asset_DataList = (Element) elements.get("popup_Asset_DataList");
		this.popup_Asset_endDate = (Element) elements.get("popup_Asset_endDate");
		this.payrollService = (Element) elements.get("payrollService");
		this.popup_Acount_Ok = (Element) elements.get("popup_Acount_Ok");
		this.corporateAdvisor = (Element) elements.get("corporateAdvisor");
		this.clientsList_Client_AddData_CorporateTax_AR = (Element) elements.get("clientsList_Client_AddData_CorporateTax_AR");
		this.popup_Acount_DataList = (Element) elements.get("popup_Acount_DataList");
		this.popup_Acount_SetName = (Element) elements.get("popup_Acount_SetName");
		this.popup_Payroll_Cancel = (Element) elements.get("popup_Payroll_Cancel");
		this.personalAdvisor = (Element) elements.get("personalAdvisor");
		this.dep_BasicInfo = (Element) elements.get("dep_BasicInfo");
		this.popup_Asset_AddAccountData_Comp = (Element) elements.get("popup_Asset_AddAccountData_Comp");
		this.popup_Asset_accountBasicInfoTitle = (Element) elements.get("popup_Asset_accountBasicInfoTitle");
		this.clientsList_Client_Title = (Element) elements.get("clientsList_Client_Title");
		this.popup_Acount_accountBasicInfoTitle = (Element) elements.get("popup_Acount_accountBasicInfoTitle");
		this.popup_title = (Element) elements.get("popup_title");
		this.clientsList_Client_AddData_Payroll = (Element) elements.get("clientsList_Client_AddData_Payroll");
		this.clientsList_Code = (Element) elements.get("clientsList_Code");
		this.clientsList_Client_deatilList = (Element) elements.get("clientsList_Client_deatilList");
		this.clientsList_Client_AddData_ConsumptionTax_AR = (Element) elements.get("clientsList_Client_AddData_ConsumptionTax_AR");
		this.clientsList_Client_AddData = (Element) elements.get("clientsList_Client_AddData");
		this.dep_Assets = (Element) elements.get("dep_Assets");
		this.popup_Asset_endDate2 = (Element) elements.get("popup_Asset_endDate2");
		this.popup_Payroll_SetCode = (Element) elements.get("popup_Payroll_SetCode");
		this.clientsList_Client_AddData_ConsumptionTax_IR = (Element) elements.get("clientsList_Client_AddData_ConsumptionTax_IR");
		this.businessList = (Element) elements.get("businessList");
		this.employeeInformationRegistered = (Element) elements.get("employeeInformationRegistered");
		this.popup_Acount_Client_SetName = (Element) elements.get("popup_Acount_Client_SetName");
		this.popup_Asset_list1_inside = (Element) elements.get("popup_Asset_list1_inside");
		this.popup_Asset_Ok = (Element) elements.get("popup_Asset_Ok");
		this.clientsList_Client_AddData_CorporateTax_IR = (Element) elements.get("clientsList_Client_AddData_CorporateTax_IR");
		this.clientsList_Client_AddData_ConsumptionTax_IAR = (Element) elements.get("clientsList_Client_AddData_ConsumptionTax_IAR");
		this.popup_Asset_Account_name = (Element) elements.get("popup_Asset_Account_name");
		this.advisorService = (Element) elements.get("advisorService");
		this.popup_Payroll_Client_Cancel = (Element) elements.get("popup_Payroll_Client_Cancel");
		this.dep_Location = (Element) elements.get("dep_Location");
		this.adviserReg = (Element) elements.get("adviserReg");
		this.popUp = (Element) elements.get("popUp");
		this.adviserList_AddMore = (Element) elements.get("adviserList_AddMore");
		this.dep_AssetsItem = (Element) elements.get("dep_AssetsItem");
		this.payrollDataOne = (Element) elements.get("payrollDataOne");
		this.name = (Element) elements.get("name");
		this.popup_Asset_Account_SetCode = (Element) elements.get("popup_Asset_Account_SetCode");
		this.clientsList_Client_AddData_Account = (Element) elements.get("clientsList_Client_AddData_Account");
		this.clientsList_Client_AddData_TaxProxy = (Element) elements.get("clientsList_Client_AddData_TaxProxy");
		this.popup_Payroll_Ok = (Element) elements.get("popup_Payroll_Ok");
		this.popup_Asset_Account_endingDate = (Element) elements.get("popup_Asset_Account_endingDate");
		this.adviserList_AddIndividual = (Element) elements.get("adviserList_AddIndividual");
		this.annualAdjustment = (Element) elements.get("annualAdjustment");
		this.annualAdj = (Element) elements.get("annualAdj");
		this.popup_Asset_SetCode = (Element) elements.get("popup_Asset_SetCode");
		this.businessDepreciation = (Element) elements.get("businessDepreciation");
		this.popup_Asset_Account_endingDate2 = (Element) elements.get("popup_Asset_Account_endingDate2");
	}
}
